/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { DaydreamError } from "./daydreamerror.js";

/**
 * Default Response
 */
export type InternalServerErrorData = {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;
};

/**
 * Default Response
 */
export class InternalServerError extends DaydreamError {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: InternalServerErrorData;

  constructor(
    err: InternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;
    this.code = err.code;
    this.status = err.status;
    if (err.details != null) this.details = err.details;
    if (err.requestId != null) this.requestId = err.requestId;
    if (err.traceId != null) this.traceId = err.traceId;

    this.name = "InternalServerError";
  }
}

/**
 * Default Response
 */
export type TooManyRequestsErrorData = {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;
};

/**
 * Default Response
 */
export class TooManyRequestsError extends DaydreamError {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: TooManyRequestsErrorData;

  constructor(
    err: TooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;
    this.code = err.code;
    this.status = err.status;
    if (err.details != null) this.details = err.details;
    if (err.requestId != null) this.requestId = err.requestId;
    if (err.traceId != null) this.traceId = err.traceId;

    this.name = "TooManyRequestsError";
  }
}

/**
 * Default Response
 */
export type ConflictErrorData = {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;
};

/**
 * Default Response
 */
export class ConflictError extends DaydreamError {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ConflictErrorData;

  constructor(
    err: ConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;
    this.code = err.code;
    this.status = err.status;
    if (err.details != null) this.details = err.details;
    if (err.requestId != null) this.requestId = err.requestId;
    if (err.traceId != null) this.traceId = err.traceId;

    this.name = "ConflictError";
  }
}

/**
 * Default Response
 */
export type NotFoundErrorData = {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;
};

/**
 * Default Response
 */
export class NotFoundError extends DaydreamError {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: NotFoundErrorData;

  constructor(
    err: NotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;
    this.code = err.code;
    this.status = err.status;
    if (err.details != null) this.details = err.details;
    if (err.requestId != null) this.requestId = err.requestId;
    if (err.traceId != null) this.traceId = err.traceId;

    this.name = "NotFoundError";
  }
}

/**
 * Default Response
 */
export type ForbiddenErrorData = {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;
};

/**
 * Default Response
 */
export class ForbiddenError extends DaydreamError {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ForbiddenErrorData;

  constructor(
    err: ForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;
    this.code = err.code;
    this.status = err.status;
    if (err.details != null) this.details = err.details;
    if (err.requestId != null) this.requestId = err.requestId;
    if (err.traceId != null) this.traceId = err.traceId;

    this.name = "ForbiddenError";
  }
}

/**
 * Default Response
 */
export type UnauthorizedErrorData = {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;
};

/**
 * Default Response
 */
export class UnauthorizedError extends DaydreamError {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UnauthorizedErrorData;

  constructor(
    err: UnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;
    this.code = err.code;
    this.status = err.status;
    if (err.details != null) this.details = err.details;
    if (err.requestId != null) this.requestId = err.requestId;
    if (err.traceId != null) this.traceId = err.traceId;

    this.name = "UnauthorizedError";
  }
}

/**
 * Default Response
 */
export type BadRequestErrorData = {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;
};

/**
 * Default Response
 */
export class BadRequestError extends DaydreamError {
  /**
   * Always false for error responses
   */
  success?: boolean | undefined;
  /**
   * User-facing error message
   */
  error: string;
  /**
   * Stable machine-readable error code, e.g., STREAMS/NOT_FOUND
   */
  code: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Optional structured details about the error
   */
  details?: any | undefined;
  /**
   * Request identifier for correlation
   */
  requestId?: string | undefined;
  /**
   * OpenTelemetry trace id for correlation
   */
  traceId?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: BadRequestErrorData;

  constructor(
    err: BadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;
    this.code = err.code;
    this.status = err.status;
    if (err.details != null) this.details = err.details;
    if (err.requestId != null) this.requestId = err.requestId;
    if (err.traceId != null) this.traceId = err.traceId;

    this.name = "BadRequestError";
  }
}

/** @internal */
export const InternalServerError$inboundSchema: z.ZodMiniType<
  InternalServerError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.boolean(), false),
    error: types.string(),
    code: types.string(),
    status: types.number(),
    details: types.optional(z.any()),
    requestId: types.optional(types.string()),
    traceId: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new InternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const TooManyRequestsError$inboundSchema: z.ZodMiniType<
  TooManyRequestsError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.boolean(), false),
    error: types.string(),
    code: types.string(),
    status: types.number(),
    details: types.optional(z.any()),
    requestId: types.optional(types.string()),
    traceId: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new TooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ConflictError$inboundSchema: z.ZodMiniType<
  ConflictError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.boolean(), false),
    error: types.string(),
    code: types.string(),
    status: types.number(),
    details: types.optional(z.any()),
    requestId: types.optional(types.string()),
    traceId: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ConflictError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const NotFoundError$inboundSchema: z.ZodMiniType<
  NotFoundError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.boolean(), false),
    error: types.string(),
    code: types.string(),
    status: types.number(),
    details: types.optional(z.any()),
    requestId: types.optional(types.string()),
    traceId: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new NotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ForbiddenError$inboundSchema: z.ZodMiniType<
  ForbiddenError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.boolean(), false),
    error: types.string(),
    code: types.string(),
    status: types.number(),
    details: types.optional(z.any()),
    requestId: types.optional(types.string()),
    traceId: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UnauthorizedError$inboundSchema: z.ZodMiniType<
  UnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.boolean(), false),
    error: types.string(),
    code: types.string(),
    status: types.number(),
    details: types.optional(z.any()),
    requestId: types.optional(types.string()),
    traceId: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const BadRequestError$inboundSchema: z.ZodMiniType<
  BadRequestError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.boolean(), false),
    error: types.string(),
    code: types.string(),
    status: types.number(),
    details: types.optional(z.any()),
    requestId: types.optional(types.string()),
    traceId: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new BadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
