/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { streamsCreate } from "../funcs/streamsCreate.js";
import { streamsDelete } from "../funcs/streamsDelete.js";
import { streamsGetAll } from "../funcs/streamsGetAll.js";
import { streamsGetById } from "../funcs/streamsGetById.js";
import { streamsUpdate } from "../funcs/streamsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Public extends ClientSDK {
  /**
   * Create a new stream
   *
   * @remarks
   * Creates a new video processing stream with the specified configuration
   */
  async create(
    request: operations.CreateStreamRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateStreamResponse> {
    return unwrapAsync(streamsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get all streams for user
   *
   * @remarks
   * Retrieves all streams belonging to the authenticated user
   */
  async getAll(
    request?: operations.GetAllStreamsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetAllStreamsResponse> {
    return unwrapAsync(streamsGetAll(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a stream
   *
   * @remarks
   * Deletes a specific stream by ID for the authenticated user
   */
  async delete(
    request: operations.DeleteStreamRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteStreamResponse> {
    return unwrapAsync(streamsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a stream
   *
   * @remarks
   * Updates pipeline parameters for a specific stream by ID for the authenticated user
   */
  async update(
    request: operations.UpdateStreamRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateStreamResponse> {
    return unwrapAsync(streamsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get stream by ID
   *
   * @remarks
   * Retrieves a specific stream by its ID. Users can only access their own streams unless they have admin privileges.
   */
  async getById(
    request: operations.GetStreamByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetStreamByIdResponse> {
    return unwrapAsync(streamsGetById(
      this,
      request,
      options,
    ));
  }
}
