/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as discriminatedUnionTypes from "../../types/discriminatedUnion.js";
import { discriminatedUnion } from "../../types/discriminatedUnion.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const CreateStreamPipelineRequest = {
  Streamdiffusion: "streamdiffusion",
} as const;
export type CreateStreamPipelineRequest = ClosedEnum<
  typeof CreateStreamPipelineRequest
>;

export type CreateStreamParamsRequest =
  | models.SDTurbo
  | models.Sdxl
  | (models.Sd15 & { modelId: "Lykon/dreamshaper-8" })
  | (models.Sd15 & { modelId: "prompthero/openjourney-v4" });

export type CreateStreamStreamDiffusion = {
  pipeline: CreateStreamPipelineRequest;
  params:
    | models.SDTurbo
    | models.Sdxl
    | (models.Sd15 & { modelId: "Lykon/dreamshaper-8" })
    | (models.Sd15 & { modelId: "prompthero/openjourney-v4" });
  /**
   * Human-readable name for the stream
   */
  name?: string | undefined;
  /**
   * Custom RTMP URL for stream output destination
   */
  outputRtmpUrl?: string | undefined;
};

export type CreateStreamRequest = CreateStreamStreamDiffusion;

export const CreateStreamPipelineResponse = {
  Streamdiffusion: "streamdiffusion",
} as const;
export type CreateStreamPipelineResponse = ClosedEnum<
  typeof CreateStreamPipelineResponse
>;

export type CreateStreamParamsResponse =
  | models.SDTurbo1
  | models.Sdxl1
  | (models.Sd151 & { modelId: "Lykon/dreamshaper-8" })
  | (models.Sd151 & { modelId: "prompthero/openjourney-v4" })
  | discriminatedUnionTypes.Unknown<"modelId">;

/**
 * Default Response
 */
export type CreateStreamResponse = {
  pipeline: CreateStreamPipelineResponse;
  params:
    | models.SDTurbo1
    | models.Sdxl1
    | (models.Sd151 & { modelId: "Lykon/dreamshaper-8" })
    | (models.Sd151 & { modelId: "prompthero/openjourney-v4" })
    | discriminatedUnionTypes.Unknown<"modelId">;
  /**
   * Unique identifier for the stream
   */
  id: string;
  /**
   * Unique key used for streaming to this endpoint
   */
  streamKey: string;
  /**
   * URL where the processed stream output can be accessed
   */
  outputStreamUrl?: string | undefined;
  /**
   * ISO timestamp when the stream was created
   */
  createdAt: string;
  /**
   * Playback ID for accessing the stream output
   */
  outputPlaybackId: string;
  /**
   * Human-readable name of the stream
   */
  name: string;
  /**
   * ID of the user who created this stream
   */
  author: string;
  /**
   * Whether this stream was created from the playground interface
   */
  fromPlayground: boolean;
  /**
   * Gateway server hostname handling this stream
   */
  gatewayHost: string;
  /**
   * Whether this is a smoke test stream
   */
  isSmokeTest: boolean;
  /**
   * WebRTC WHIP URL for stream ingestion
   */
  whipUrl: string;
};

/** @internal */
export const CreateStreamPipelineRequest$outboundSchema: z.ZodMiniEnum<
  typeof CreateStreamPipelineRequest
> = z.enum(CreateStreamPipelineRequest);

/** @internal */
export type CreateStreamParamsRequest$Outbound =
  | models.SDTurbo$Outbound
  | models.Sdxl$Outbound
  | (models.Sd15$Outbound & { model_id: "Lykon/dreamshaper-8" })
  | (models.Sd15$Outbound & { model_id: "prompthero/openjourney-v4" });

/** @internal */
export const CreateStreamParamsRequest$outboundSchema: z.ZodMiniType<
  CreateStreamParamsRequest$Outbound,
  CreateStreamParamsRequest
> = z.union([
  models.SDTurbo$outboundSchema,
  models.Sdxl$outboundSchema,
  z.intersection(
    models.Sd15$outboundSchema,
    z.pipe(
      z.object({ modelId: z.literal("Lykon/dreamshaper-8") }),
      z.transform((v) => ({ model_id: v.modelId })),
    ),
  ),
  z.intersection(
    models.Sd15$outboundSchema,
    z.pipe(
      z.object({ modelId: z.literal("prompthero/openjourney-v4") }),
      z.transform((v) => ({ model_id: v.modelId })),
    ),
  ),
]);

export function createStreamParamsRequestToJSON(
  createStreamParamsRequest: CreateStreamParamsRequest,
): string {
  return JSON.stringify(
    CreateStreamParamsRequest$outboundSchema.parse(createStreamParamsRequest),
  );
}

/** @internal */
export type CreateStreamStreamDiffusion$Outbound = {
  pipeline: string;
  params:
    | models.SDTurbo$Outbound
    | models.Sdxl$Outbound
    | (models.Sd15$Outbound & { model_id: "Lykon/dreamshaper-8" })
    | (models.Sd15$Outbound & { model_id: "prompthero/openjourney-v4" });
  name?: string | undefined;
  output_rtmp_url?: string | undefined;
};

/** @internal */
export const CreateStreamStreamDiffusion$outboundSchema: z.ZodMiniType<
  CreateStreamStreamDiffusion$Outbound,
  CreateStreamStreamDiffusion
> = z.pipe(
  z.object({
    pipeline: CreateStreamPipelineRequest$outboundSchema,
    params: z.union([
      models.SDTurbo$outboundSchema,
      models.Sdxl$outboundSchema,
      z.intersection(
        models.Sd15$outboundSchema,
        z.pipe(
          z.object({ modelId: z.literal("Lykon/dreamshaper-8") }),
          z.transform((v) => ({ model_id: v.modelId })),
        ),
      ),
      z.intersection(
        models.Sd15$outboundSchema,
        z.pipe(
          z.object({ modelId: z.literal("prompthero/openjourney-v4") }),
          z.transform((v) => ({ model_id: v.modelId })),
        ),
      ),
    ]),
    name: z.optional(z.string()),
    outputRtmpUrl: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      outputRtmpUrl: "output_rtmp_url",
    });
  }),
);

export function createStreamStreamDiffusionToJSON(
  createStreamStreamDiffusion: CreateStreamStreamDiffusion,
): string {
  return JSON.stringify(
    CreateStreamStreamDiffusion$outboundSchema.parse(
      createStreamStreamDiffusion,
    ),
  );
}

/** @internal */
export type CreateStreamRequest$Outbound = CreateStreamStreamDiffusion$Outbound;

/** @internal */
export const CreateStreamRequest$outboundSchema: z.ZodMiniType<
  CreateStreamRequest$Outbound,
  CreateStreamRequest
> = z.lazy(() => CreateStreamStreamDiffusion$outboundSchema);

export function createStreamRequestToJSON(
  createStreamRequest: CreateStreamRequest,
): string {
  return JSON.stringify(
    CreateStreamRequest$outboundSchema.parse(createStreamRequest),
  );
}

/** @internal */
export const CreateStreamPipelineResponse$inboundSchema: z.ZodMiniEnum<
  typeof CreateStreamPipelineResponse
> = z.enum(CreateStreamPipelineResponse);

/** @internal */
export const CreateStreamParamsResponse$inboundSchema: z.ZodMiniType<
  CreateStreamParamsResponse,
  unknown
> = discriminatedUnion("model_id", {
  ["stabilityai/sd-turbo"]: models.SDTurbo1$inboundSchema,
  ["stabilityai/sdxl-turbo"]: models.Sdxl1$inboundSchema,
  ["Lykon/dreamshaper-8"]: z.intersection(
    models.Sd151$inboundSchema,
    z.pipe(
      z.object({ model_id: z.literal("Lykon/dreamshaper-8") }),
      z.transform((v) => ({ modelId: v.model_id })),
    ),
  ),
  ["prompthero/openjourney-v4"]: z.intersection(
    models.Sd151$inboundSchema,
    z.pipe(
      z.object({ model_id: z.literal("prompthero/openjourney-v4") }),
      z.transform((v) => ({ modelId: v.model_id })),
    ),
  ),
}, { outputPropertyName: "modelId" });

export function createStreamParamsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateStreamParamsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateStreamParamsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateStreamParamsResponse' from JSON`,
  );
}

/** @internal */
export const CreateStreamResponse$inboundSchema: z.ZodMiniType<
  CreateStreamResponse,
  unknown
> = z.pipe(
  z.object({
    pipeline: CreateStreamPipelineResponse$inboundSchema,
    params: discriminatedUnion("model_id", {
      ["stabilityai/sd-turbo"]: models.SDTurbo1$inboundSchema,
      ["stabilityai/sdxl-turbo"]: models.Sdxl1$inboundSchema,
      ["Lykon/dreamshaper-8"]: z.intersection(
        models.Sd151$inboundSchema,
        z.pipe(
          z.object({ model_id: z.literal("Lykon/dreamshaper-8") }),
          z.transform((v) => ({ modelId: v.model_id })),
        ),
      ),
      ["prompthero/openjourney-v4"]: z.intersection(
        models.Sd151$inboundSchema,
        z.pipe(
          z.object({ model_id: z.literal("prompthero/openjourney-v4") }),
          z.transform((v) => ({ modelId: v.model_id })),
        ),
      ),
    }, { outputPropertyName: "modelId" }),
    id: types.string(),
    stream_key: types.string(),
    output_stream_url: types.optional(types.string()),
    created_at: types.string(),
    output_playback_id: types.string(),
    name: types.string(),
    author: types.string(),
    from_playground: types.boolean(),
    gateway_host: types.string(),
    is_smoke_test: types.boolean(),
    whip_url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "stream_key": "streamKey",
      "output_stream_url": "outputStreamUrl",
      "created_at": "createdAt",
      "output_playback_id": "outputPlaybackId",
      "from_playground": "fromPlayground",
      "gateway_host": "gatewayHost",
      "is_smoke_test": "isSmokeTest",
      "whip_url": "whipUrl",
    });
  }),
);

export function createStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateStreamResponse' from JSON`,
  );
}
