/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteStreamRequest = {
  /**
   * ID of the stream to delete
   */
  id: string;
};

/**
 * Empty object confirming successful deletion
 */
export type Data = {};

/**
 * Default Response
 */
export type DeleteStreamResponse = {
  /**
   * Whether the stream deletion was successful
   */
  success: boolean;
  /**
   * Empty object confirming successful deletion
   */
  data: Data;
};

/** @internal */
export type DeleteStreamRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteStreamRequest$outboundSchema: z.ZodMiniType<
  DeleteStreamRequest$Outbound,
  DeleteStreamRequest
> = z.object({
  id: z.string(),
});

export function deleteStreamRequestToJSON(
  deleteStreamRequest: DeleteStreamRequest,
): string {
  return JSON.stringify(
    DeleteStreamRequest$outboundSchema.parse(deleteStreamRequest),
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodMiniType<Data, unknown> = z.object({});

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const DeleteStreamResponse$inboundSchema: z.ZodMiniType<
  DeleteStreamResponse,
  unknown
> = z.object({
  success: types.boolean(),
  data: z.lazy(() => Data$inboundSchema),
});

export function deleteStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteStreamResponse' from JSON`,
  );
}
