/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAllStreamsRequest = {
  /**
   * Filter streams by the ID of the user who owns them
   */
  userId?: string | undefined;
};

/**
 * Default Response
 */
export type GetAllStreamsResponse = {
  /**
   * Whether the request was successful
   */
  success: boolean;
  /**
   * Array of stream objects
   */
  data: Array<any>;
};

/** @internal */
export type GetAllStreamsRequest$Outbound = {
  user_id?: string | undefined;
};

/** @internal */
export const GetAllStreamsRequest$outboundSchema: z.ZodMiniType<
  GetAllStreamsRequest$Outbound,
  GetAllStreamsRequest
> = z.pipe(
  z.object({
    userId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      userId: "user_id",
    });
  }),
);

export function getAllStreamsRequestToJSON(
  getAllStreamsRequest: GetAllStreamsRequest,
): string {
  return JSON.stringify(
    GetAllStreamsRequest$outboundSchema.parse(getAllStreamsRequest),
  );
}

/** @internal */
export const GetAllStreamsResponse$inboundSchema: z.ZodMiniType<
  GetAllStreamsResponse,
  unknown
> = z.object({
  success: types.boolean(),
  data: z.array(z.any()),
});

export function getAllStreamsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAllStreamsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllStreamsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllStreamsResponse' from JSON`,
  );
}
