/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as discriminatedUnionTypes from "../../types/discriminatedUnion.js";
import { discriminatedUnion } from "../../types/discriminatedUnion.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetStreamByIdRequest = {
  /**
   * ID of the stream to retrieve
   */
  id: string;
};

export const GetStreamByIdPipeline = {
  Streamdiffusion: "streamdiffusion",
} as const;
export type GetStreamByIdPipeline = ClosedEnum<typeof GetStreamByIdPipeline>;

export type GetStreamByIdParams =
  | models.SDTurbo4
  | models.Sdxl4
  | (models.Sd154 & { modelId: "Lykon/dreamshaper-8" })
  | (models.Sd154 & { modelId: "prompthero/openjourney-v4" })
  | discriminatedUnionTypes.Unknown<"modelId">;

/**
 * Default Response
 */
export type GetStreamByIdResponse = {
  pipeline: GetStreamByIdPipeline;
  params:
    | models.SDTurbo4
    | models.Sdxl4
    | (models.Sd154 & { modelId: "Lykon/dreamshaper-8" })
    | (models.Sd154 & { modelId: "prompthero/openjourney-v4" })
    | discriminatedUnionTypes.Unknown<"modelId">;
  /**
   * Unique identifier for the stream
   */
  id: string;
  /**
   * Unique key used for streaming to this endpoint
   */
  streamKey: string;
  /**
   * URL where the processed stream output can be accessed
   */
  outputStreamUrl?: string | undefined;
  /**
   * ISO timestamp when the stream was created
   */
  createdAt: string;
  /**
   * Playback ID for accessing the stream output
   */
  outputPlaybackId: string;
  /**
   * Human-readable name of the stream
   */
  name: string;
  /**
   * ID of the user who created this stream
   */
  author: string;
  /**
   * Whether this stream was created from the playground interface
   */
  fromPlayground: boolean;
  /**
   * Gateway server hostname handling this stream
   */
  gatewayHost: string;
  /**
   * Whether this is a smoke test stream
   */
  isSmokeTest: boolean;
  /**
   * WebRTC WHIP URL for stream ingestion
   */
  whipUrl: string;
};

/** @internal */
export type GetStreamByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetStreamByIdRequest$outboundSchema: z.ZodMiniType<
  GetStreamByIdRequest$Outbound,
  GetStreamByIdRequest
> = z.object({
  id: z.string(),
});

export function getStreamByIdRequestToJSON(
  getStreamByIdRequest: GetStreamByIdRequest,
): string {
  return JSON.stringify(
    GetStreamByIdRequest$outboundSchema.parse(getStreamByIdRequest),
  );
}

/** @internal */
export const GetStreamByIdPipeline$inboundSchema: z.ZodMiniEnum<
  typeof GetStreamByIdPipeline
> = z.enum(GetStreamByIdPipeline);

/** @internal */
export const GetStreamByIdParams$inboundSchema: z.ZodMiniType<
  GetStreamByIdParams,
  unknown
> = discriminatedUnion("model_id", {
  ["stabilityai/sd-turbo"]: models.SDTurbo4$inboundSchema,
  ["stabilityai/sdxl-turbo"]: models.Sdxl4$inboundSchema,
  ["Lykon/dreamshaper-8"]: z.intersection(
    models.Sd154$inboundSchema,
    z.pipe(
      z.object({ model_id: z.literal("Lykon/dreamshaper-8") }),
      z.transform((v) => ({ modelId: v.model_id })),
    ),
  ),
  ["prompthero/openjourney-v4"]: z.intersection(
    models.Sd154$inboundSchema,
    z.pipe(
      z.object({ model_id: z.literal("prompthero/openjourney-v4") }),
      z.transform((v) => ({ modelId: v.model_id })),
    ),
  ),
}, { outputPropertyName: "modelId" });

export function getStreamByIdParamsFromJSON(
  jsonString: string,
): SafeParseResult<GetStreamByIdParams, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStreamByIdParams$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStreamByIdParams' from JSON`,
  );
}

/** @internal */
export const GetStreamByIdResponse$inboundSchema: z.ZodMiniType<
  GetStreamByIdResponse,
  unknown
> = z.pipe(
  z.object({
    pipeline: GetStreamByIdPipeline$inboundSchema,
    params: discriminatedUnion("model_id", {
      ["stabilityai/sd-turbo"]: models.SDTurbo4$inboundSchema,
      ["stabilityai/sdxl-turbo"]: models.Sdxl4$inboundSchema,
      ["Lykon/dreamshaper-8"]: z.intersection(
        models.Sd154$inboundSchema,
        z.pipe(
          z.object({ model_id: z.literal("Lykon/dreamshaper-8") }),
          z.transform((v) => ({ modelId: v.model_id })),
        ),
      ),
      ["prompthero/openjourney-v4"]: z.intersection(
        models.Sd154$inboundSchema,
        z.pipe(
          z.object({ model_id: z.literal("prompthero/openjourney-v4") }),
          z.transform((v) => ({ modelId: v.model_id })),
        ),
      ),
    }, { outputPropertyName: "modelId" }),
    id: types.string(),
    stream_key: types.string(),
    output_stream_url: types.optional(types.string()),
    created_at: types.string(),
    output_playback_id: types.string(),
    name: types.string(),
    author: types.string(),
    from_playground: types.boolean(),
    gateway_host: types.string(),
    is_smoke_test: types.boolean(),
    whip_url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "stream_key": "streamKey",
      "output_stream_url": "outputStreamUrl",
      "created_at": "createdAt",
      "output_playback_id": "outputPlaybackId",
      "from_playground": "fromPlayground",
      "gateway_host": "gatewayHost",
      "is_smoke_test": "isSmokeTest",
      "whip_url": "whipUrl",
    });
  }),
);

export function getStreamByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetStreamByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStreamByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStreamByIdResponse' from JSON`,
  );
}
