/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as discriminatedUnionTypes from "../../types/discriminatedUnion.js";
import { discriminatedUnion } from "../../types/discriminatedUnion.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const UpdateStreamPipelineRequest = {
  Streamdiffusion: "streamdiffusion",
} as const;
export type UpdateStreamPipelineRequest = ClosedEnum<
  typeof UpdateStreamPipelineRequest
>;

export type UpdateStreamParamsRequest =
  | models.SDTurbo2
  | models.Sdxl2
  | (models.Sd152 & { modelId: "Lykon/dreamshaper-8" })
  | (models.Sd152 & { modelId: "prompthero/openjourney-v4" });

export type UpdateStreamStreamDiffusion = {
  pipeline: UpdateStreamPipelineRequest;
  params:
    | models.SDTurbo2
    | models.Sdxl2
    | (models.Sd152 & { modelId: "Lykon/dreamshaper-8" })
    | (models.Sd152 & { modelId: "prompthero/openjourney-v4" });
};

export type UpdateStreamRequestBody = UpdateStreamStreamDiffusion;

export type UpdateStreamRequest = {
  /**
   * ID of the stream to update
   */
  id: string;
  body: UpdateStreamStreamDiffusion;
};

export const UpdateStreamPipelineResponse = {
  Streamdiffusion: "streamdiffusion",
} as const;
export type UpdateStreamPipelineResponse = ClosedEnum<
  typeof UpdateStreamPipelineResponse
>;

export type UpdateStreamParamsResponse =
  | models.SDTurbo3
  | models.Sdxl3
  | (models.Sd153 & { modelId: "Lykon/dreamshaper-8" })
  | (models.Sd153 & { modelId: "prompthero/openjourney-v4" })
  | discriminatedUnionTypes.Unknown<"modelId">;

/**
 * Default Response
 */
export type UpdateStreamResponse = {
  pipeline: UpdateStreamPipelineResponse;
  params:
    | models.SDTurbo3
    | models.Sdxl3
    | (models.Sd153 & { modelId: "Lykon/dreamshaper-8" })
    | (models.Sd153 & { modelId: "prompthero/openjourney-v4" })
    | discriminatedUnionTypes.Unknown<"modelId">;
  /**
   * Unique identifier for the stream
   */
  id: string;
  /**
   * Unique key used for streaming to this endpoint
   */
  streamKey: string;
  /**
   * URL where the processed stream output can be accessed
   */
  outputStreamUrl?: string | undefined;
  /**
   * ISO timestamp when the stream was created
   */
  createdAt: string;
  /**
   * Playback ID for accessing the stream output
   */
  outputPlaybackId: string;
  /**
   * Human-readable name of the stream
   */
  name: string;
  /**
   * ID of the user who created this stream
   */
  author: string;
  /**
   * Whether this stream was created from the playground interface
   */
  fromPlayground: boolean;
  /**
   * Gateway server hostname handling this stream
   */
  gatewayHost: string;
  /**
   * Whether this is a smoke test stream
   */
  isSmokeTest: boolean;
  /**
   * WebRTC WHIP URL for stream ingestion
   */
  whipUrl: string;
};

/** @internal */
export const UpdateStreamPipelineRequest$outboundSchema: z.ZodMiniEnum<
  typeof UpdateStreamPipelineRequest
> = z.enum(UpdateStreamPipelineRequest);

/** @internal */
export type UpdateStreamParamsRequest$Outbound =
  | models.SDTurbo2$Outbound
  | models.Sdxl2$Outbound
  | (models.Sd152$Outbound & { model_id: "Lykon/dreamshaper-8" })
  | (models.Sd152$Outbound & { model_id: "prompthero/openjourney-v4" });

/** @internal */
export const UpdateStreamParamsRequest$outboundSchema: z.ZodMiniType<
  UpdateStreamParamsRequest$Outbound,
  UpdateStreamParamsRequest
> = z.union([
  models.SDTurbo2$outboundSchema,
  models.Sdxl2$outboundSchema,
  z.intersection(
    models.Sd152$outboundSchema,
    z.pipe(
      z.object({ modelId: z.literal("Lykon/dreamshaper-8") }),
      z.transform((v) => ({ model_id: v.modelId })),
    ),
  ),
  z.intersection(
    models.Sd152$outboundSchema,
    z.pipe(
      z.object({ modelId: z.literal("prompthero/openjourney-v4") }),
      z.transform((v) => ({ model_id: v.modelId })),
    ),
  ),
]);

export function updateStreamParamsRequestToJSON(
  updateStreamParamsRequest: UpdateStreamParamsRequest,
): string {
  return JSON.stringify(
    UpdateStreamParamsRequest$outboundSchema.parse(updateStreamParamsRequest),
  );
}

/** @internal */
export type UpdateStreamStreamDiffusion$Outbound = {
  pipeline: string;
  params:
    | models.SDTurbo2$Outbound
    | models.Sdxl2$Outbound
    | (models.Sd152$Outbound & { model_id: "Lykon/dreamshaper-8" })
    | (models.Sd152$Outbound & { model_id: "prompthero/openjourney-v4" });
};

/** @internal */
export const UpdateStreamStreamDiffusion$outboundSchema: z.ZodMiniType<
  UpdateStreamStreamDiffusion$Outbound,
  UpdateStreamStreamDiffusion
> = z.object({
  pipeline: UpdateStreamPipelineRequest$outboundSchema,
  params: z.union([
    models.SDTurbo2$outboundSchema,
    models.Sdxl2$outboundSchema,
    z.intersection(
      models.Sd152$outboundSchema,
      z.pipe(
        z.object({ modelId: z.literal("Lykon/dreamshaper-8") }),
        z.transform((v) => ({ model_id: v.modelId })),
      ),
    ),
    z.intersection(
      models.Sd152$outboundSchema,
      z.pipe(
        z.object({ modelId: z.literal("prompthero/openjourney-v4") }),
        z.transform((v) => ({ model_id: v.modelId })),
      ),
    ),
  ]),
});

export function updateStreamStreamDiffusionToJSON(
  updateStreamStreamDiffusion: UpdateStreamStreamDiffusion,
): string {
  return JSON.stringify(
    UpdateStreamStreamDiffusion$outboundSchema.parse(
      updateStreamStreamDiffusion,
    ),
  );
}

/** @internal */
export type UpdateStreamRequestBody$Outbound =
  UpdateStreamStreamDiffusion$Outbound;

/** @internal */
export const UpdateStreamRequestBody$outboundSchema: z.ZodMiniType<
  UpdateStreamRequestBody$Outbound,
  UpdateStreamRequestBody
> = z.lazy(() => UpdateStreamStreamDiffusion$outboundSchema);

export function updateStreamRequestBodyToJSON(
  updateStreamRequestBody: UpdateStreamRequestBody,
): string {
  return JSON.stringify(
    UpdateStreamRequestBody$outboundSchema.parse(updateStreamRequestBody),
  );
}

/** @internal */
export type UpdateStreamRequest$Outbound = {
  id: string;
  body: UpdateStreamStreamDiffusion$Outbound;
};

/** @internal */
export const UpdateStreamRequest$outboundSchema: z.ZodMiniType<
  UpdateStreamRequest$Outbound,
  UpdateStreamRequest
> = z.object({
  id: z.string(),
  body: z.lazy(() => UpdateStreamStreamDiffusion$outboundSchema),
});

export function updateStreamRequestToJSON(
  updateStreamRequest: UpdateStreamRequest,
): string {
  return JSON.stringify(
    UpdateStreamRequest$outboundSchema.parse(updateStreamRequest),
  );
}

/** @internal */
export const UpdateStreamPipelineResponse$inboundSchema: z.ZodMiniEnum<
  typeof UpdateStreamPipelineResponse
> = z.enum(UpdateStreamPipelineResponse);

/** @internal */
export const UpdateStreamParamsResponse$inboundSchema: z.ZodMiniType<
  UpdateStreamParamsResponse,
  unknown
> = discriminatedUnion("model_id", {
  ["stabilityai/sd-turbo"]: models.SDTurbo3$inboundSchema,
  ["stabilityai/sdxl-turbo"]: models.Sdxl3$inboundSchema,
  ["Lykon/dreamshaper-8"]: z.intersection(
    models.Sd153$inboundSchema,
    z.pipe(
      z.object({ model_id: z.literal("Lykon/dreamshaper-8") }),
      z.transform((v) => ({ modelId: v.model_id })),
    ),
  ),
  ["prompthero/openjourney-v4"]: z.intersection(
    models.Sd153$inboundSchema,
    z.pipe(
      z.object({ model_id: z.literal("prompthero/openjourney-v4") }),
      z.transform((v) => ({ modelId: v.model_id })),
    ),
  ),
}, { outputPropertyName: "modelId" });

export function updateStreamParamsResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateStreamParamsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateStreamParamsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateStreamParamsResponse' from JSON`,
  );
}

/** @internal */
export const UpdateStreamResponse$inboundSchema: z.ZodMiniType<
  UpdateStreamResponse,
  unknown
> = z.pipe(
  z.object({
    pipeline: UpdateStreamPipelineResponse$inboundSchema,
    params: discriminatedUnion("model_id", {
      ["stabilityai/sd-turbo"]: models.SDTurbo3$inboundSchema,
      ["stabilityai/sdxl-turbo"]: models.Sdxl3$inboundSchema,
      ["Lykon/dreamshaper-8"]: z.intersection(
        models.Sd153$inboundSchema,
        z.pipe(
          z.object({ model_id: z.literal("Lykon/dreamshaper-8") }),
          z.transform((v) => ({ modelId: v.model_id })),
        ),
      ),
      ["prompthero/openjourney-v4"]: z.intersection(
        models.Sd153$inboundSchema,
        z.pipe(
          z.object({ model_id: z.literal("prompthero/openjourney-v4") }),
          z.transform((v) => ({ modelId: v.model_id })),
        ),
      ),
    }, { outputPropertyName: "modelId" }),
    id: types.string(),
    stream_key: types.string(),
    output_stream_url: types.optional(types.string()),
    created_at: types.string(),
    output_playback_id: types.string(),
    name: types.string(),
    author: types.string(),
    from_playground: types.boolean(),
    gateway_host: types.string(),
    is_smoke_test: types.boolean(),
    whip_url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "stream_key": "streamKey",
      "output_stream_url": "outputStreamUrl",
      "created_at": "createdAt",
      "output_playback_id": "outputPlaybackId",
      "from_playground": "fromPlayground",
      "gateway_host": "gatewayHost",
      "is_smoke_test": "isSmokeTest",
      "whip_url": "whipUrl",
    });
  }),
);

export function updateStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateStreamResponse' from JSON`,
  );
}
