/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Model to use for generation
 */
export const Sd151ModelId = {
  LykonDreamshaper8: "Lykon/dreamshaper-8",
  PromptheroOpenjourneyV4: "prompthero/openjourney-v4",
} as const;
/**
 * Model to use for generation
 */
export type Sd151ModelId = OpenEnum<typeof Sd151ModelId>;

export type Sd151Prompt1 = string | number;

/**
 * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
 */
export type Sd151Prompt2 = string | Array<Array<string | number>>;

/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export const Sd151PromptInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export type Sd151PromptInterpolationMethod = OpenEnum<
  typeof Sd151PromptInterpolationMethod
>;

/**
 * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
 */
export type Sd151LoraDict = {};

/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export const Sd151Acceleration = {
  None: "none",
  Xformers: "xformers",
  Tensorrt: "tensorrt",
} as const;
/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export type Sd151Acceleration = OpenEnum<typeof Sd151Acceleration>;

export type Sd151Seed1 = number | number;

/**
 * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
 */
export type Sd151Seed2 = number | Array<Array<number | number>>;

/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export const Sd151SeedInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export type Sd151SeedInterpolationMethod = OpenEnum<
  typeof Sd151SeedInterpolationMethod
>;

export const Sd151ImagePreprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type Sd151ImagePreprocessingType = OpenEnum<
  typeof Sd151ImagePreprocessingType
>;

export type Sd151ImagePreprocessingProcessor = {
  type: Sd151ImagePreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image preprocessor configurations for image processing
 */
export type Sd151ImagePreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<Sd151ImagePreprocessingProcessor>;
};

export const Sd151ImagePostprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type Sd151ImagePostprocessingType = OpenEnum<
  typeof Sd151ImagePostprocessingType
>;

export type Sd151ImagePostprocessingProcessor = {
  type: Sd151ImagePostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image postprocessor configurations for image processing
 *
 * @remarks
 *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
 */
export type Sd151ImagePostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<Sd151ImagePostprocessingProcessor>;
};

export const Sd151LatentPreprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type Sd151LatentPreprocessingType = ClosedEnum<
  typeof Sd151LatentPreprocessingType
>;

export type Sd151LatentPreprocessingProcessor = {
  type: Sd151LatentPreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent preprocessor configurations for latent processing
 */
export type Sd151LatentPreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<Sd151LatentPreprocessingProcessor>;
};

export const Sd151LatentPostprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type Sd151LatentPostprocessingType = ClosedEnum<
  typeof Sd151LatentPostprocessingType
>;

export type Sd151LatentPostprocessingProcessor = {
  type: Sd151LatentPostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent postprocessor configurations for latent processing
 */
export type Sd151LatentPostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<Sd151LatentPostprocessingProcessor>;
};

/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export const Sd151ControlnetModelId = {
  LllyasvielControlV11f1pSd15Depth: "lllyasviel/control_v11f1p_sd15_depth",
  LllyasvielControlV11f1eSd15Tile: "lllyasviel/control_v11f1e_sd15_tile",
  LllyasvielControlV11pSd15Canny: "lllyasviel/control_v11p_sd15_canny",
  DaydreamliveTemporalNet2StableDiffusionV15:
    "daydreamlive/TemporalNet2-stable-diffusion-v1-5",
} as const;
/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export type Sd151ControlnetModelId = OpenEnum<typeof Sd151ControlnetModelId>;

/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export const Sd151Preprocessor = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export type Sd151Preprocessor = OpenEnum<typeof Sd151Preprocessor>;

export type Sd151Controlnet = {
  /**
   * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
   */
  modelId: Sd151ControlnetModelId;
  /**
   * Strength of the ControlNet's influence on generation. Higher values make the model follow the control signal more strictly. Typical range 0.0-1.0, where 0.0 disables the control and 1.0 applies full control. Default: 1.0
   */
  conditioningScale: number;
  /**
   * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
   */
  preprocessor: Sd151Preprocessor;
  /**
   * Preprocessor parameters
   */
  preprocessorParams?: { [k: string]: any } | undefined;
  /**
   * Whether this ControlNet is active. Disabled ControlNets are not loaded. Default: true
   */
  enabled: boolean;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance begins. 0.0 means guidance starts from the beginning.
   */
  controlGuidanceStart?: number | undefined;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance ends. 1.0 means guidance continues until the end.
   */
  controlGuidanceEnd?: number | undefined;
};

/**
 * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
 */
export const Sd151TypeRegular = {
  Regular: "regular",
} as const;
/**
 * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
 */
export type Sd151TypeRegular = ClosedEnum<typeof Sd151TypeRegular>;

/**
 * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
 */
export const Sd151WeightType = {
  Linear: "linear",
  EaseIn: "ease in",
  EaseOut: "ease out",
  EaseInOut: "ease in-out",
  ReverseInOut: "reverse in-out",
  WeakInput: "weak input",
  WeakOutput: "weak output",
  WeakMiddle: "weak middle",
  StrongMiddle: "strong middle",
  StyleTransfer: "style transfer",
  Composition: "composition",
  StrongStyleTransfer: "strong style transfer",
  StyleAndComposition: "style and composition",
  StyleTransferPrecise: "style transfer precise",
  CompositionPrecise: "composition precise",
} as const;
/**
 * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
 */
export type Sd151WeightType = OpenEnum<typeof Sd151WeightType>;

/**
 * IP adapter — Turns on IP-Adapter style conditioning and is fully hot-swappable. Available for SDXL, SDXL-faceid, SD1.5
 */
export type Sd151IpAdapter = {
  /**
   * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
   */
  type: Sd151TypeRegular;
  /**
   * Whether IP adapter is enabled
   */
  enabled?: boolean | undefined;
  /**
   * Strength of IP adapter style conditioning
   */
  scale?: number | undefined;
  /**
   * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
   */
  weightType?: Sd151WeightType | undefined;
};

/**
 * Cached attention (StreamV2V) configuration. Enable cached attention to reuse key/value tensors across frames. ⚠️ NOTE: Enabling or disabling cached_attention requires a pipeline reload as it uses a different pipeline.
 */
export type Sd151CachedAttention = {
  /**
   * Whether this cached attention is active. Enable cached attention to reuse key/value tensors across frames.
   */
  enabled: boolean;
  /**
   * Number of frames retained in the attention cache. Number of historical K/V frames to retain. Limited by TensorRT engine exports.
   */
  maxFrames: number;
  /**
   * Cadence (number of frames) for refreshing cached key/value tensors i.e How often (in number of frames) to refresh the cache.
   *
   * @remarks
   *       It is now **frame-based** (not seconds). It accepts integers 1-240, representing how many frames elapse between cache refreshes.
   */
  interval: number;
};

export type Sd151 = {
  /**
   * Model to use for generation
   */
  modelId: Sd151ModelId;
  /**
   * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
   */
  prompt?: string | Array<Array<string | number>> | undefined;
  /**
   * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
   */
  promptInterpolationMethod?: Sd151PromptInterpolationMethod | undefined;
  /**
   * Whether to normalize prompt weights to sum to 1.0 for consistent generation.
   */
  normalizePromptWeights?: boolean | undefined;
  /**
   * Whether to normalize seed weights to sum to 1.0 for consistent generation.
   */
  normalizeSeedWeights?: boolean | undefined;
  /**
   * Text describing what to avoid in the generated image.
   */
  negativePrompt?: string | undefined;
  /**
   * Strength of prompt adherence. Higher values make the model follow the prompt more strictly.
   */
  guidanceScale?: number | undefined;
  /**
   * Delta sets per-frame denoising progress: lower delta means steadier, less flicker but slower/softer; higher delta means faster, sharper but more flicker/artifacts (often reduce CFG).
   */
  delta?: number | undefined;
  /**
   * Builds the full denoising schedule (the 'grid' of possible refinement steps). Changing it changes what each step number (t_index_list value) means. Keep it fixed for a session and only adjust if you're deliberately redefining the schedule; if you do, proportionally remap your t_index_list. Typical range 10-100 with default being 50.
   */
  numInferenceSteps?: number | undefined;
  /**
   * The ordered list of step indices from the num_inference_steps schedule to execute per frame. Each index is one model pass, so latency scales with the list length. Higher indices (e.g., 40–49 on a 50-step grid) mainly polish and preserve structure (lower flicker), while lower indices (<20) rewrite structure (more flicker, creative). Values must be non-decreasing, and each between 0 and num_inference_steps.
   *
   * @remarks
   *
   * ⚠️ NOTE: t_index_list must have 1–4 elements, non-decreasing, and within [0, num_inference_steps]. The value should not go above 50.
   */
  tIndexList?: Array<number> | undefined;
  /**
   * Whether to use safety checker for content filtering
   */
  useSafetyChecker?: boolean | undefined;
  /**
   * Output image width in pixels. Must be divisible by 64 and between 384-1024.
   */
  width?: number | undefined;
  /**
   * Output image height in pixels. Must be divisible by 64 and between 384-1024.
   */
  height?: number | undefined;
  /**
   * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
   */
  loraDict?: Sd151LoraDict | null | undefined;
  /**
   * Whether to use Latent Consistency Model LoRA for faster inference.
   */
  useLcmLora?: boolean | undefined;
  /**
   * Identifier for the LCM LoRA model to use. Example: "latent-consistency/lcm-lora-sdv1-5"
   */
  lcmLoraId?: string | undefined;
  /**
   * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
   */
  acceleration?: Sd151Acceleration | undefined;
  /**
   * Whether to process multiple denoising steps in a single batch for efficiency.
   */
  useDenoisingBatch?: boolean | undefined;
  /**
   * Whether to add noise to input frames before processing. Enabling this slightly re-noises each frame to improve temporal stability, reduce ghosting/texture sticking, and prevent drift; disabling can yield sharper, lower-latency results but may increase flicker and artifact accumulation over time.
   */
  doAddNoise?: boolean | undefined;
  /**
   * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
   */
  seed?: number | Array<Array<number | number>> | undefined;
  /**
   * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
   */
  seedInterpolationMethod?: Sd151SeedInterpolationMethod | undefined;
  /**
   * Whether to skip frames that are too similar to the previous output to reduce flicker.
   */
  enableSimilarImageFilter?: boolean | undefined;
  /**
   * Similarity threshold for the image filter. Higher values allow more variation between frames.
   */
  similarImageFilterThreshold?: number | undefined;
  /**
   * Maximum number of consecutive frames that can be skipped by the similarity filter.
   */
  similarImageFilterMaxSkipFrame?: number | undefined;
  /**
   * Whether to skip the diffusion process. Any ControlNets or diffusion-only parameters are ignored when enabled.
   *
   * @remarks
   *         Example use cases:
   *         - Stream the output of a preprocessor (e.g. live depth maps or pose skeletons),
   *         - Run post-processors like RealESRGAN upscaler on externally provided frames,
   *         - Warm a pipeline without paying the diffusion cost.
   *       ⚠️ NOTE: skip_diffusion is evaluated at pipeline creation time; switching mid-stream triggers a pipeline reload.
   */
  skipDiffusion?: boolean | undefined;
  /**
   * List of image preprocessor configurations for image processing
   */
  imagePreprocessing?: Sd151ImagePreprocessing | undefined;
  /**
   * List of image postprocessor configurations for image processing
   *
   * @remarks
   *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
   */
  imagePostprocessing?: Sd151ImagePostprocessing | undefined;
  /**
   * List of latent preprocessor configurations for latent processing
   */
  latentPreprocessing?: Sd151LatentPreprocessing | undefined;
  /**
   * List of latent postprocessor configurations for latent processing
   */
  latentPostprocessing?: Sd151LatentPostprocessing | undefined;
  /**
   * List of ControlNet configurations for guided generation. Each ControlNet provides different types of conditioning (pose, edges, depth, etc.). Dynamic updates limited to conditioning_scale changes only; cannot add new ControlNets or change model_id/preprocessor/params without reload.
   */
  controlnets?: Array<Sd151Controlnet> | undefined;
  /**
   * IP adapter — Turns on IP-Adapter style conditioning and is fully hot-swappable. Available for SDXL, SDXL-faceid, SD1.5
   */
  ipAdapter?: Sd151IpAdapter | undefined;
  /**
   * HTTPS URL or base64-encoded data URI (data:image/[type];base64,...) of the style image to use. Base64 images are automatically cached and uploaded to storage with content-based deduplication. Maximum size: 5MB. When set, the runtime downloads the image and configures the pipeline; if omitted, a default style image is used. For 'faceid' type, the image must contain a clear face. Available for SDXL, SDXL-faceid, SD1.5
   */
  ipAdapterStyleImageUrl?: string | undefined;
  /**
   * Cached attention (StreamV2V) configuration. Enable cached attention to reuse key/value tensors across frames. ⚠️ NOTE: Enabling or disabling cached_attention requires a pipeline reload as it uses a different pipeline.
   */
  cachedAttention?: Sd151CachedAttention | undefined;
};

/** @internal */
export const Sd151ModelId$inboundSchema: z.ZodMiniType<Sd151ModelId, unknown> =
  openEnums.inboundSchema(Sd151ModelId);

/** @internal */
export const Sd151Prompt1$inboundSchema: z.ZodMiniType<Sd151Prompt1, unknown> =
  smartUnion([types.string(), types.number()]);

export function sd151Prompt1FromJSON(
  jsonString: string,
): SafeParseResult<Sd151Prompt1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151Prompt1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151Prompt1' from JSON`,
  );
}

/** @internal */
export const Sd151Prompt2$inboundSchema: z.ZodMiniType<Sd151Prompt2, unknown> =
  smartUnion([
    types.string(),
    z.array(z.array(smartUnion([types.string(), types.number()]))),
  ]);

export function sd151Prompt2FromJSON(
  jsonString: string,
): SafeParseResult<Sd151Prompt2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151Prompt2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151Prompt2' from JSON`,
  );
}

/** @internal */
export const Sd151PromptInterpolationMethod$inboundSchema: z.ZodMiniType<
  Sd151PromptInterpolationMethod,
  unknown
> = openEnums.inboundSchema(Sd151PromptInterpolationMethod);

/** @internal */
export const Sd151LoraDict$inboundSchema: z.ZodMiniType<
  Sd151LoraDict,
  unknown
> = z.object({});

export function sd151LoraDictFromJSON(
  jsonString: string,
): SafeParseResult<Sd151LoraDict, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151LoraDict$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151LoraDict' from JSON`,
  );
}

/** @internal */
export const Sd151Acceleration$inboundSchema: z.ZodMiniType<
  Sd151Acceleration,
  unknown
> = openEnums.inboundSchema(Sd151Acceleration);

/** @internal */
export const Sd151Seed1$inboundSchema: z.ZodMiniType<Sd151Seed1, unknown> =
  smartUnion([types.number(), types.number()]);

export function sd151Seed1FromJSON(
  jsonString: string,
): SafeParseResult<Sd151Seed1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151Seed1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151Seed1' from JSON`,
  );
}

/** @internal */
export const Sd151Seed2$inboundSchema: z.ZodMiniType<Sd151Seed2, unknown> =
  smartUnion([
    types.number(),
    z.array(z.array(smartUnion([types.number(), types.number()]))),
  ]);

export function sd151Seed2FromJSON(
  jsonString: string,
): SafeParseResult<Sd151Seed2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151Seed2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151Seed2' from JSON`,
  );
}

/** @internal */
export const Sd151SeedInterpolationMethod$inboundSchema: z.ZodMiniType<
  Sd151SeedInterpolationMethod,
  unknown
> = openEnums.inboundSchema(Sd151SeedInterpolationMethod);

/** @internal */
export const Sd151ImagePreprocessingType$inboundSchema: z.ZodMiniType<
  Sd151ImagePreprocessingType,
  unknown
> = openEnums.inboundSchema(Sd151ImagePreprocessingType);

/** @internal */
export const Sd151ImagePreprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sd151ImagePreprocessingProcessor,
  unknown
> = z.object({
  type: Sd151ImagePreprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sd151ImagePreprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sd151ImagePreprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151ImagePreprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151ImagePreprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sd151ImagePreprocessing$inboundSchema: z.ZodMiniType<
  Sd151ImagePreprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sd151ImagePreprocessingProcessor$inboundSchema),
  ),
});

export function sd151ImagePreprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sd151ImagePreprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151ImagePreprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151ImagePreprocessing' from JSON`,
  );
}

/** @internal */
export const Sd151ImagePostprocessingType$inboundSchema: z.ZodMiniType<
  Sd151ImagePostprocessingType,
  unknown
> = openEnums.inboundSchema(Sd151ImagePostprocessingType);

/** @internal */
export const Sd151ImagePostprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sd151ImagePostprocessingProcessor,
  unknown
> = z.object({
  type: Sd151ImagePostprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sd151ImagePostprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sd151ImagePostprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151ImagePostprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151ImagePostprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sd151ImagePostprocessing$inboundSchema: z.ZodMiniType<
  Sd151ImagePostprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sd151ImagePostprocessingProcessor$inboundSchema),
  ),
});

export function sd151ImagePostprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sd151ImagePostprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151ImagePostprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151ImagePostprocessing' from JSON`,
  );
}

/** @internal */
export const Sd151LatentPreprocessingType$inboundSchema: z.ZodMiniEnum<
  typeof Sd151LatentPreprocessingType
> = z.enum(Sd151LatentPreprocessingType);

/** @internal */
export const Sd151LatentPreprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sd151LatentPreprocessingProcessor,
  unknown
> = z.object({
  type: Sd151LatentPreprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sd151LatentPreprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sd151LatentPreprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151LatentPreprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151LatentPreprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sd151LatentPreprocessing$inboundSchema: z.ZodMiniType<
  Sd151LatentPreprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sd151LatentPreprocessingProcessor$inboundSchema),
  ),
});

export function sd151LatentPreprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sd151LatentPreprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151LatentPreprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151LatentPreprocessing' from JSON`,
  );
}

/** @internal */
export const Sd151LatentPostprocessingType$inboundSchema: z.ZodMiniEnum<
  typeof Sd151LatentPostprocessingType
> = z.enum(Sd151LatentPostprocessingType);

/** @internal */
export const Sd151LatentPostprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sd151LatentPostprocessingProcessor,
  unknown
> = z.object({
  type: Sd151LatentPostprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sd151LatentPostprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sd151LatentPostprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      Sd151LatentPostprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151LatentPostprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sd151LatentPostprocessing$inboundSchema: z.ZodMiniType<
  Sd151LatentPostprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sd151LatentPostprocessingProcessor$inboundSchema),
  ),
});

export function sd151LatentPostprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sd151LatentPostprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151LatentPostprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151LatentPostprocessing' from JSON`,
  );
}

/** @internal */
export const Sd151ControlnetModelId$inboundSchema: z.ZodMiniType<
  Sd151ControlnetModelId,
  unknown
> = openEnums.inboundSchema(Sd151ControlnetModelId);

/** @internal */
export const Sd151Preprocessor$inboundSchema: z.ZodMiniType<
  Sd151Preprocessor,
  unknown
> = openEnums.inboundSchema(Sd151Preprocessor);

/** @internal */
export const Sd151Controlnet$inboundSchema: z.ZodMiniType<
  Sd151Controlnet,
  unknown
> = z.pipe(
  z.object({
    model_id: Sd151ControlnetModelId$inboundSchema,
    conditioning_scale: types.number(),
    preprocessor: Sd151Preprocessor$inboundSchema,
    preprocessor_params: types.optional(z.record(z.string(), z.any())),
    enabled: types.boolean(),
    control_guidance_start: types.optional(types.number()),
    control_guidance_end: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_id": "modelId",
      "conditioning_scale": "conditioningScale",
      "preprocessor_params": "preprocessorParams",
      "control_guidance_start": "controlGuidanceStart",
      "control_guidance_end": "controlGuidanceEnd",
    });
  }),
);

export function sd151ControlnetFromJSON(
  jsonString: string,
): SafeParseResult<Sd151Controlnet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151Controlnet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151Controlnet' from JSON`,
  );
}

/** @internal */
export const Sd151TypeRegular$inboundSchema: z.ZodMiniEnum<
  typeof Sd151TypeRegular
> = z.enum(Sd151TypeRegular);

/** @internal */
export const Sd151WeightType$inboundSchema: z.ZodMiniType<
  Sd151WeightType,
  unknown
> = openEnums.inboundSchema(Sd151WeightType);

/** @internal */
export const Sd151IpAdapter$inboundSchema: z.ZodMiniType<
  Sd151IpAdapter,
  unknown
> = z.pipe(
  z.object({
    type: z._default(Sd151TypeRegular$inboundSchema, "regular"),
    enabled: types.optional(types.boolean()),
    scale: types.optional(types.number()),
    weight_type: types.optional(Sd151WeightType$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "weight_type": "weightType",
    });
  }),
);

export function sd151IpAdapterFromJSON(
  jsonString: string,
): SafeParseResult<Sd151IpAdapter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151IpAdapter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151IpAdapter' from JSON`,
  );
}

/** @internal */
export const Sd151CachedAttention$inboundSchema: z.ZodMiniType<
  Sd151CachedAttention,
  unknown
> = z.pipe(
  z.object({
    enabled: types.boolean(),
    max_frames: types.number(),
    interval: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "max_frames": "maxFrames",
    });
  }),
);

export function sd151CachedAttentionFromJSON(
  jsonString: string,
): SafeParseResult<Sd151CachedAttention, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151CachedAttention$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151CachedAttention' from JSON`,
  );
}

/** @internal */
export const Sd151$inboundSchema: z.ZodMiniType<Sd151, unknown> = z.pipe(
  z.object({
    model_id: Sd151ModelId$inboundSchema,
    prompt: types.optional(
      smartUnion([
        types.string(),
        z.array(z.array(smartUnion([types.string(), types.number()]))),
      ]),
    ),
    prompt_interpolation_method: types.optional(
      Sd151PromptInterpolationMethod$inboundSchema,
    ),
    normalize_prompt_weights: types.optional(types.boolean()),
    normalize_seed_weights: types.optional(types.boolean()),
    negative_prompt: types.optional(types.string()),
    guidance_scale: types.optional(types.number()),
    delta: types.optional(types.number()),
    num_inference_steps: types.optional(types.number()),
    t_index_list: types.optional(z.array(types.number())),
    use_safety_checker: types.optional(types.boolean()),
    width: types.optional(types.number()),
    height: types.optional(types.number()),
    lora_dict: z.optional(
      z.nullable(z.lazy(() => Sd151LoraDict$inboundSchema)),
    ),
    use_lcm_lora: types.optional(types.boolean()),
    lcm_lora_id: types.optional(types.string()),
    acceleration: types.optional(Sd151Acceleration$inboundSchema),
    use_denoising_batch: types.optional(types.boolean()),
    do_add_noise: types.optional(types.boolean()),
    seed: types.optional(
      smartUnion([
        types.number(),
        z.array(z.array(smartUnion([types.number(), types.number()]))),
      ]),
    ),
    seed_interpolation_method: types.optional(
      Sd151SeedInterpolationMethod$inboundSchema,
    ),
    enable_similar_image_filter: types.optional(types.boolean()),
    similar_image_filter_threshold: types.optional(types.number()),
    similar_image_filter_max_skip_frame: types.optional(types.number()),
    skip_diffusion: types.optional(types.boolean()),
    image_preprocessing: types.optional(
      z.lazy(() => Sd151ImagePreprocessing$inboundSchema),
    ),
    image_postprocessing: types.optional(
      z.lazy(() => Sd151ImagePostprocessing$inboundSchema),
    ),
    latent_preprocessing: types.optional(
      z.lazy(() => Sd151LatentPreprocessing$inboundSchema),
    ),
    latent_postprocessing: types.optional(
      z.lazy(() => Sd151LatentPostprocessing$inboundSchema),
    ),
    controlnets: types.optional(
      z.array(z.lazy(() => Sd151Controlnet$inboundSchema)),
    ),
    ip_adapter: types.optional(z.lazy(() => Sd151IpAdapter$inboundSchema)),
    ip_adapter_style_image_url: types.optional(types.string()),
    cached_attention: types.optional(
      z.lazy(() => Sd151CachedAttention$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_id": "modelId",
      "prompt_interpolation_method": "promptInterpolationMethod",
      "normalize_prompt_weights": "normalizePromptWeights",
      "normalize_seed_weights": "normalizeSeedWeights",
      "negative_prompt": "negativePrompt",
      "guidance_scale": "guidanceScale",
      "num_inference_steps": "numInferenceSteps",
      "t_index_list": "tIndexList",
      "use_safety_checker": "useSafetyChecker",
      "lora_dict": "loraDict",
      "use_lcm_lora": "useLcmLora",
      "lcm_lora_id": "lcmLoraId",
      "use_denoising_batch": "useDenoisingBatch",
      "do_add_noise": "doAddNoise",
      "seed_interpolation_method": "seedInterpolationMethod",
      "enable_similar_image_filter": "enableSimilarImageFilter",
      "similar_image_filter_threshold": "similarImageFilterThreshold",
      "similar_image_filter_max_skip_frame": "similarImageFilterMaxSkipFrame",
      "skip_diffusion": "skipDiffusion",
      "image_preprocessing": "imagePreprocessing",
      "image_postprocessing": "imagePostprocessing",
      "latent_preprocessing": "latentPreprocessing",
      "latent_postprocessing": "latentPostprocessing",
      "ip_adapter": "ipAdapter",
      "ip_adapter_style_image_url": "ipAdapterStyleImageUrl",
      "cached_attention": "cachedAttention",
    });
  }),
);

export function sd151FromJSON(
  jsonString: string,
): SafeParseResult<Sd151, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd151$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd151' from JSON`,
  );
}
