/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Model to use for generation
 */
export const Sd153ModelId = {
  LykonDreamshaper8: "Lykon/dreamshaper-8",
  PromptheroOpenjourneyV4: "prompthero/openjourney-v4",
} as const;
/**
 * Model to use for generation
 */
export type Sd153ModelId = OpenEnum<typeof Sd153ModelId>;

export type Sd153Prompt1 = string | number;

/**
 * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
 */
export type Sd153Prompt2 = string | Array<Array<string | number>>;

/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export const Sd153PromptInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export type Sd153PromptInterpolationMethod = OpenEnum<
  typeof Sd153PromptInterpolationMethod
>;

/**
 * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
 */
export type Sd153LoraDict = {};

/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export const Sd153Acceleration = {
  None: "none",
  Xformers: "xformers",
  Tensorrt: "tensorrt",
} as const;
/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export type Sd153Acceleration = OpenEnum<typeof Sd153Acceleration>;

export type Sd153Seed1 = number | number;

/**
 * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
 */
export type Sd153Seed2 = number | Array<Array<number | number>>;

/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export const Sd153SeedInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export type Sd153SeedInterpolationMethod = OpenEnum<
  typeof Sd153SeedInterpolationMethod
>;

export const Sd153ImagePreprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type Sd153ImagePreprocessingType = OpenEnum<
  typeof Sd153ImagePreprocessingType
>;

export type Sd153ImagePreprocessingProcessor = {
  type: Sd153ImagePreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image preprocessor configurations for image processing
 */
export type Sd153ImagePreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<Sd153ImagePreprocessingProcessor>;
};

export const Sd153ImagePostprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type Sd153ImagePostprocessingType = OpenEnum<
  typeof Sd153ImagePostprocessingType
>;

export type Sd153ImagePostprocessingProcessor = {
  type: Sd153ImagePostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image postprocessor configurations for image processing
 *
 * @remarks
 *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
 */
export type Sd153ImagePostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<Sd153ImagePostprocessingProcessor>;
};

export const Sd153LatentPreprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type Sd153LatentPreprocessingType = ClosedEnum<
  typeof Sd153LatentPreprocessingType
>;

export type Sd153LatentPreprocessingProcessor = {
  type: Sd153LatentPreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent preprocessor configurations for latent processing
 */
export type Sd153LatentPreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<Sd153LatentPreprocessingProcessor>;
};

export const Sd153LatentPostprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type Sd153LatentPostprocessingType = ClosedEnum<
  typeof Sd153LatentPostprocessingType
>;

export type Sd153LatentPostprocessingProcessor = {
  type: Sd153LatentPostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent postprocessor configurations for latent processing
 */
export type Sd153LatentPostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<Sd153LatentPostprocessingProcessor>;
};

/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export const Sd153ControlnetModelId = {
  LllyasvielControlV11f1pSd15Depth: "lllyasviel/control_v11f1p_sd15_depth",
  LllyasvielControlV11f1eSd15Tile: "lllyasviel/control_v11f1e_sd15_tile",
  LllyasvielControlV11pSd15Canny: "lllyasviel/control_v11p_sd15_canny",
  DaydreamliveTemporalNet2StableDiffusionV15:
    "daydreamlive/TemporalNet2-stable-diffusion-v1-5",
} as const;
/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export type Sd153ControlnetModelId = OpenEnum<typeof Sd153ControlnetModelId>;

/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export const Sd153Preprocessor = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export type Sd153Preprocessor = OpenEnum<typeof Sd153Preprocessor>;

export type Sd153Controlnet = {
  /**
   * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
   */
  modelId: Sd153ControlnetModelId;
  /**
   * Strength of the ControlNet's influence on generation. Higher values make the model follow the control signal more strictly. Typical range 0.0-1.0, where 0.0 disables the control and 1.0 applies full control. Default: 1.0
   */
  conditioningScale: number;
  /**
   * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
   */
  preprocessor: Sd153Preprocessor;
  /**
   * Preprocessor parameters
   */
  preprocessorParams?: { [k: string]: any } | undefined;
  /**
   * Whether this ControlNet is active. Disabled ControlNets are not loaded. Default: true
   */
  enabled: boolean;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance begins. 0.0 means guidance starts from the beginning.
   */
  controlGuidanceStart?: number | undefined;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance ends. 1.0 means guidance continues until the end.
   */
  controlGuidanceEnd?: number | undefined;
};

/**
 * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
 */
export const Sd153TypeRegular = {
  Regular: "regular",
} as const;
/**
 * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
 */
export type Sd153TypeRegular = ClosedEnum<typeof Sd153TypeRegular>;

/**
 * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
 */
export const Sd153WeightType = {
  Linear: "linear",
  EaseIn: "ease in",
  EaseOut: "ease out",
  EaseInOut: "ease in-out",
  ReverseInOut: "reverse in-out",
  WeakInput: "weak input",
  WeakOutput: "weak output",
  WeakMiddle: "weak middle",
  StrongMiddle: "strong middle",
  StyleTransfer: "style transfer",
  Composition: "composition",
  StrongStyleTransfer: "strong style transfer",
  StyleAndComposition: "style and composition",
  StyleTransferPrecise: "style transfer precise",
  CompositionPrecise: "composition precise",
} as const;
/**
 * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
 */
export type Sd153WeightType = OpenEnum<typeof Sd153WeightType>;

/**
 * IP adapter — Turns on IP-Adapter style conditioning and is fully hot-swappable. Available for SDXL, SDXL-faceid, SD1.5
 */
export type Sd153IpAdapter = {
  /**
   * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
   */
  type: Sd153TypeRegular;
  /**
   * Whether IP adapter is enabled
   */
  enabled?: boolean | undefined;
  /**
   * Strength of IP adapter style conditioning
   */
  scale?: number | undefined;
  /**
   * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
   */
  weightType?: Sd153WeightType | undefined;
};

/**
 * Cached attention (StreamV2V) configuration. Enable cached attention to reuse key/value tensors across frames. ⚠️ NOTE: Enabling or disabling cached_attention requires a pipeline reload as it uses a different pipeline.
 */
export type Sd153CachedAttention = {
  /**
   * Whether this cached attention is active. Enable cached attention to reuse key/value tensors across frames.
   */
  enabled: boolean;
  /**
   * Number of frames retained in the attention cache. Number of historical K/V frames to retain. Limited by TensorRT engine exports.
   */
  maxFrames: number;
  /**
   * Cadence (number of frames) for refreshing cached key/value tensors i.e How often (in number of frames) to refresh the cache.
   *
   * @remarks
   *       It is now **frame-based** (not seconds). It accepts integers 1-240, representing how many frames elapse between cache refreshes.
   */
  interval: number;
};

export type Sd153 = {
  /**
   * Model to use for generation
   */
  modelId: Sd153ModelId;
  /**
   * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
   */
  prompt?: string | Array<Array<string | number>> | undefined;
  /**
   * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
   */
  promptInterpolationMethod?: Sd153PromptInterpolationMethod | undefined;
  /**
   * Whether to normalize prompt weights to sum to 1.0 for consistent generation.
   */
  normalizePromptWeights?: boolean | undefined;
  /**
   * Whether to normalize seed weights to sum to 1.0 for consistent generation.
   */
  normalizeSeedWeights?: boolean | undefined;
  /**
   * Text describing what to avoid in the generated image.
   */
  negativePrompt?: string | undefined;
  /**
   * Strength of prompt adherence. Higher values make the model follow the prompt more strictly.
   */
  guidanceScale?: number | undefined;
  /**
   * Delta sets per-frame denoising progress: lower delta means steadier, less flicker but slower/softer; higher delta means faster, sharper but more flicker/artifacts (often reduce CFG).
   */
  delta?: number | undefined;
  /**
   * Builds the full denoising schedule (the 'grid' of possible refinement steps). Changing it changes what each step number (t_index_list value) means. Keep it fixed for a session and only adjust if you're deliberately redefining the schedule; if you do, proportionally remap your t_index_list. Typical range 10-100 with default being 50.
   */
  numInferenceSteps?: number | undefined;
  /**
   * The ordered list of step indices from the num_inference_steps schedule to execute per frame. Each index is one model pass, so latency scales with the list length. Higher indices (e.g., 40–49 on a 50-step grid) mainly polish and preserve structure (lower flicker), while lower indices (<20) rewrite structure (more flicker, creative). Values must be non-decreasing, and each between 0 and num_inference_steps.
   *
   * @remarks
   *
   * ⚠️ NOTE: t_index_list must have 1–4 elements, non-decreasing, and within [0, num_inference_steps]. The value should not go above 50.
   */
  tIndexList?: Array<number> | undefined;
  /**
   * Whether to use safety checker for content filtering
   */
  useSafetyChecker?: boolean | undefined;
  /**
   * Output image width in pixels. Must be divisible by 64 and between 384-1024.
   */
  width?: number | undefined;
  /**
   * Output image height in pixels. Must be divisible by 64 and between 384-1024.
   */
  height?: number | undefined;
  /**
   * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
   */
  loraDict?: Sd153LoraDict | null | undefined;
  /**
   * Whether to use Latent Consistency Model LoRA for faster inference.
   */
  useLcmLora?: boolean | undefined;
  /**
   * Identifier for the LCM LoRA model to use. Example: "latent-consistency/lcm-lora-sdv1-5"
   */
  lcmLoraId?: string | undefined;
  /**
   * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
   */
  acceleration?: Sd153Acceleration | undefined;
  /**
   * Whether to process multiple denoising steps in a single batch for efficiency.
   */
  useDenoisingBatch?: boolean | undefined;
  /**
   * Whether to add noise to input frames before processing. Enabling this slightly re-noises each frame to improve temporal stability, reduce ghosting/texture sticking, and prevent drift; disabling can yield sharper, lower-latency results but may increase flicker and artifact accumulation over time.
   */
  doAddNoise?: boolean | undefined;
  /**
   * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
   */
  seed?: number | Array<Array<number | number>> | undefined;
  /**
   * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
   */
  seedInterpolationMethod?: Sd153SeedInterpolationMethod | undefined;
  /**
   * Whether to skip frames that are too similar to the previous output to reduce flicker.
   */
  enableSimilarImageFilter?: boolean | undefined;
  /**
   * Similarity threshold for the image filter. Higher values allow more variation between frames.
   */
  similarImageFilterThreshold?: number | undefined;
  /**
   * Maximum number of consecutive frames that can be skipped by the similarity filter.
   */
  similarImageFilterMaxSkipFrame?: number | undefined;
  /**
   * Whether to skip the diffusion process. Any ControlNets or diffusion-only parameters are ignored when enabled.
   *
   * @remarks
   *         Example use cases:
   *         - Stream the output of a preprocessor (e.g. live depth maps or pose skeletons),
   *         - Run post-processors like RealESRGAN upscaler on externally provided frames,
   *         - Warm a pipeline without paying the diffusion cost.
   *       ⚠️ NOTE: skip_diffusion is evaluated at pipeline creation time; switching mid-stream triggers a pipeline reload.
   */
  skipDiffusion?: boolean | undefined;
  /**
   * List of image preprocessor configurations for image processing
   */
  imagePreprocessing?: Sd153ImagePreprocessing | undefined;
  /**
   * List of image postprocessor configurations for image processing
   *
   * @remarks
   *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
   */
  imagePostprocessing?: Sd153ImagePostprocessing | undefined;
  /**
   * List of latent preprocessor configurations for latent processing
   */
  latentPreprocessing?: Sd153LatentPreprocessing | undefined;
  /**
   * List of latent postprocessor configurations for latent processing
   */
  latentPostprocessing?: Sd153LatentPostprocessing | undefined;
  /**
   * List of ControlNet configurations for guided generation. Each ControlNet provides different types of conditioning (pose, edges, depth, etc.). Dynamic updates limited to conditioning_scale changes only; cannot add new ControlNets or change model_id/preprocessor/params without reload.
   */
  controlnets?: Array<Sd153Controlnet> | undefined;
  /**
   * IP adapter — Turns on IP-Adapter style conditioning and is fully hot-swappable. Available for SDXL, SDXL-faceid, SD1.5
   */
  ipAdapter?: Sd153IpAdapter | undefined;
  /**
   * HTTPS URL or base64-encoded data URI (data:image/[type];base64,...) of the style image to use. Base64 images are automatically cached and uploaded to storage with content-based deduplication. Maximum size: 5MB. When set, the runtime downloads the image and configures the pipeline; if omitted, a default style image is used. For 'faceid' type, the image must contain a clear face. Available for SDXL, SDXL-faceid, SD1.5
   */
  ipAdapterStyleImageUrl?: string | undefined;
  /**
   * Cached attention (StreamV2V) configuration. Enable cached attention to reuse key/value tensors across frames. ⚠️ NOTE: Enabling or disabling cached_attention requires a pipeline reload as it uses a different pipeline.
   */
  cachedAttention?: Sd153CachedAttention | undefined;
};

/** @internal */
export const Sd153ModelId$inboundSchema: z.ZodMiniType<Sd153ModelId, unknown> =
  openEnums.inboundSchema(Sd153ModelId);

/** @internal */
export const Sd153Prompt1$inboundSchema: z.ZodMiniType<Sd153Prompt1, unknown> =
  smartUnion([types.string(), types.number()]);

export function sd153Prompt1FromJSON(
  jsonString: string,
): SafeParseResult<Sd153Prompt1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153Prompt1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153Prompt1' from JSON`,
  );
}

/** @internal */
export const Sd153Prompt2$inboundSchema: z.ZodMiniType<Sd153Prompt2, unknown> =
  smartUnion([
    types.string(),
    z.array(z.array(smartUnion([types.string(), types.number()]))),
  ]);

export function sd153Prompt2FromJSON(
  jsonString: string,
): SafeParseResult<Sd153Prompt2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153Prompt2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153Prompt2' from JSON`,
  );
}

/** @internal */
export const Sd153PromptInterpolationMethod$inboundSchema: z.ZodMiniType<
  Sd153PromptInterpolationMethod,
  unknown
> = openEnums.inboundSchema(Sd153PromptInterpolationMethod);

/** @internal */
export const Sd153LoraDict$inboundSchema: z.ZodMiniType<
  Sd153LoraDict,
  unknown
> = z.object({});

export function sd153LoraDictFromJSON(
  jsonString: string,
): SafeParseResult<Sd153LoraDict, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153LoraDict$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153LoraDict' from JSON`,
  );
}

/** @internal */
export const Sd153Acceleration$inboundSchema: z.ZodMiniType<
  Sd153Acceleration,
  unknown
> = openEnums.inboundSchema(Sd153Acceleration);

/** @internal */
export const Sd153Seed1$inboundSchema: z.ZodMiniType<Sd153Seed1, unknown> =
  smartUnion([types.number(), types.number()]);

export function sd153Seed1FromJSON(
  jsonString: string,
): SafeParseResult<Sd153Seed1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153Seed1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153Seed1' from JSON`,
  );
}

/** @internal */
export const Sd153Seed2$inboundSchema: z.ZodMiniType<Sd153Seed2, unknown> =
  smartUnion([
    types.number(),
    z.array(z.array(smartUnion([types.number(), types.number()]))),
  ]);

export function sd153Seed2FromJSON(
  jsonString: string,
): SafeParseResult<Sd153Seed2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153Seed2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153Seed2' from JSON`,
  );
}

/** @internal */
export const Sd153SeedInterpolationMethod$inboundSchema: z.ZodMiniType<
  Sd153SeedInterpolationMethod,
  unknown
> = openEnums.inboundSchema(Sd153SeedInterpolationMethod);

/** @internal */
export const Sd153ImagePreprocessingType$inboundSchema: z.ZodMiniType<
  Sd153ImagePreprocessingType,
  unknown
> = openEnums.inboundSchema(Sd153ImagePreprocessingType);

/** @internal */
export const Sd153ImagePreprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sd153ImagePreprocessingProcessor,
  unknown
> = z.object({
  type: Sd153ImagePreprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sd153ImagePreprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sd153ImagePreprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153ImagePreprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153ImagePreprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sd153ImagePreprocessing$inboundSchema: z.ZodMiniType<
  Sd153ImagePreprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sd153ImagePreprocessingProcessor$inboundSchema),
  ),
});

export function sd153ImagePreprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sd153ImagePreprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153ImagePreprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153ImagePreprocessing' from JSON`,
  );
}

/** @internal */
export const Sd153ImagePostprocessingType$inboundSchema: z.ZodMiniType<
  Sd153ImagePostprocessingType,
  unknown
> = openEnums.inboundSchema(Sd153ImagePostprocessingType);

/** @internal */
export const Sd153ImagePostprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sd153ImagePostprocessingProcessor,
  unknown
> = z.object({
  type: Sd153ImagePostprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sd153ImagePostprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sd153ImagePostprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153ImagePostprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153ImagePostprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sd153ImagePostprocessing$inboundSchema: z.ZodMiniType<
  Sd153ImagePostprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sd153ImagePostprocessingProcessor$inboundSchema),
  ),
});

export function sd153ImagePostprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sd153ImagePostprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153ImagePostprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153ImagePostprocessing' from JSON`,
  );
}

/** @internal */
export const Sd153LatentPreprocessingType$inboundSchema: z.ZodMiniEnum<
  typeof Sd153LatentPreprocessingType
> = z.enum(Sd153LatentPreprocessingType);

/** @internal */
export const Sd153LatentPreprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sd153LatentPreprocessingProcessor,
  unknown
> = z.object({
  type: Sd153LatentPreprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sd153LatentPreprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sd153LatentPreprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153LatentPreprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153LatentPreprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sd153LatentPreprocessing$inboundSchema: z.ZodMiniType<
  Sd153LatentPreprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sd153LatentPreprocessingProcessor$inboundSchema),
  ),
});

export function sd153LatentPreprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sd153LatentPreprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153LatentPreprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153LatentPreprocessing' from JSON`,
  );
}

/** @internal */
export const Sd153LatentPostprocessingType$inboundSchema: z.ZodMiniEnum<
  typeof Sd153LatentPostprocessingType
> = z.enum(Sd153LatentPostprocessingType);

/** @internal */
export const Sd153LatentPostprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sd153LatentPostprocessingProcessor,
  unknown
> = z.object({
  type: Sd153LatentPostprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sd153LatentPostprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sd153LatentPostprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      Sd153LatentPostprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153LatentPostprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sd153LatentPostprocessing$inboundSchema: z.ZodMiniType<
  Sd153LatentPostprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sd153LatentPostprocessingProcessor$inboundSchema),
  ),
});

export function sd153LatentPostprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sd153LatentPostprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153LatentPostprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153LatentPostprocessing' from JSON`,
  );
}

/** @internal */
export const Sd153ControlnetModelId$inboundSchema: z.ZodMiniType<
  Sd153ControlnetModelId,
  unknown
> = openEnums.inboundSchema(Sd153ControlnetModelId);

/** @internal */
export const Sd153Preprocessor$inboundSchema: z.ZodMiniType<
  Sd153Preprocessor,
  unknown
> = openEnums.inboundSchema(Sd153Preprocessor);

/** @internal */
export const Sd153Controlnet$inboundSchema: z.ZodMiniType<
  Sd153Controlnet,
  unknown
> = z.pipe(
  z.object({
    model_id: Sd153ControlnetModelId$inboundSchema,
    conditioning_scale: types.number(),
    preprocessor: Sd153Preprocessor$inboundSchema,
    preprocessor_params: types.optional(z.record(z.string(), z.any())),
    enabled: types.boolean(),
    control_guidance_start: types.optional(types.number()),
    control_guidance_end: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_id": "modelId",
      "conditioning_scale": "conditioningScale",
      "preprocessor_params": "preprocessorParams",
      "control_guidance_start": "controlGuidanceStart",
      "control_guidance_end": "controlGuidanceEnd",
    });
  }),
);

export function sd153ControlnetFromJSON(
  jsonString: string,
): SafeParseResult<Sd153Controlnet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153Controlnet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153Controlnet' from JSON`,
  );
}

/** @internal */
export const Sd153TypeRegular$inboundSchema: z.ZodMiniEnum<
  typeof Sd153TypeRegular
> = z.enum(Sd153TypeRegular);

/** @internal */
export const Sd153WeightType$inboundSchema: z.ZodMiniType<
  Sd153WeightType,
  unknown
> = openEnums.inboundSchema(Sd153WeightType);

/** @internal */
export const Sd153IpAdapter$inboundSchema: z.ZodMiniType<
  Sd153IpAdapter,
  unknown
> = z.pipe(
  z.object({
    type: z._default(Sd153TypeRegular$inboundSchema, "regular"),
    enabled: types.optional(types.boolean()),
    scale: types.optional(types.number()),
    weight_type: types.optional(Sd153WeightType$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "weight_type": "weightType",
    });
  }),
);

export function sd153IpAdapterFromJSON(
  jsonString: string,
): SafeParseResult<Sd153IpAdapter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153IpAdapter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153IpAdapter' from JSON`,
  );
}

/** @internal */
export const Sd153CachedAttention$inboundSchema: z.ZodMiniType<
  Sd153CachedAttention,
  unknown
> = z.pipe(
  z.object({
    enabled: types.boolean(),
    max_frames: types.number(),
    interval: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "max_frames": "maxFrames",
    });
  }),
);

export function sd153CachedAttentionFromJSON(
  jsonString: string,
): SafeParseResult<Sd153CachedAttention, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153CachedAttention$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153CachedAttention' from JSON`,
  );
}

/** @internal */
export const Sd153$inboundSchema: z.ZodMiniType<Sd153, unknown> = z.pipe(
  z.object({
    model_id: Sd153ModelId$inboundSchema,
    prompt: types.optional(
      smartUnion([
        types.string(),
        z.array(z.array(smartUnion([types.string(), types.number()]))),
      ]),
    ),
    prompt_interpolation_method: types.optional(
      Sd153PromptInterpolationMethod$inboundSchema,
    ),
    normalize_prompt_weights: types.optional(types.boolean()),
    normalize_seed_weights: types.optional(types.boolean()),
    negative_prompt: types.optional(types.string()),
    guidance_scale: types.optional(types.number()),
    delta: types.optional(types.number()),
    num_inference_steps: types.optional(types.number()),
    t_index_list: types.optional(z.array(types.number())),
    use_safety_checker: types.optional(types.boolean()),
    width: types.optional(types.number()),
    height: types.optional(types.number()),
    lora_dict: z.optional(
      z.nullable(z.lazy(() => Sd153LoraDict$inboundSchema)),
    ),
    use_lcm_lora: types.optional(types.boolean()),
    lcm_lora_id: types.optional(types.string()),
    acceleration: types.optional(Sd153Acceleration$inboundSchema),
    use_denoising_batch: types.optional(types.boolean()),
    do_add_noise: types.optional(types.boolean()),
    seed: types.optional(
      smartUnion([
        types.number(),
        z.array(z.array(smartUnion([types.number(), types.number()]))),
      ]),
    ),
    seed_interpolation_method: types.optional(
      Sd153SeedInterpolationMethod$inboundSchema,
    ),
    enable_similar_image_filter: types.optional(types.boolean()),
    similar_image_filter_threshold: types.optional(types.number()),
    similar_image_filter_max_skip_frame: types.optional(types.number()),
    skip_diffusion: types.optional(types.boolean()),
    image_preprocessing: types.optional(
      z.lazy(() => Sd153ImagePreprocessing$inboundSchema),
    ),
    image_postprocessing: types.optional(
      z.lazy(() => Sd153ImagePostprocessing$inboundSchema),
    ),
    latent_preprocessing: types.optional(
      z.lazy(() => Sd153LatentPreprocessing$inboundSchema),
    ),
    latent_postprocessing: types.optional(
      z.lazy(() => Sd153LatentPostprocessing$inboundSchema),
    ),
    controlnets: types.optional(
      z.array(z.lazy(() => Sd153Controlnet$inboundSchema)),
    ),
    ip_adapter: types.optional(z.lazy(() => Sd153IpAdapter$inboundSchema)),
    ip_adapter_style_image_url: types.optional(types.string()),
    cached_attention: types.optional(
      z.lazy(() => Sd153CachedAttention$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_id": "modelId",
      "prompt_interpolation_method": "promptInterpolationMethod",
      "normalize_prompt_weights": "normalizePromptWeights",
      "normalize_seed_weights": "normalizeSeedWeights",
      "negative_prompt": "negativePrompt",
      "guidance_scale": "guidanceScale",
      "num_inference_steps": "numInferenceSteps",
      "t_index_list": "tIndexList",
      "use_safety_checker": "useSafetyChecker",
      "lora_dict": "loraDict",
      "use_lcm_lora": "useLcmLora",
      "lcm_lora_id": "lcmLoraId",
      "use_denoising_batch": "useDenoisingBatch",
      "do_add_noise": "doAddNoise",
      "seed_interpolation_method": "seedInterpolationMethod",
      "enable_similar_image_filter": "enableSimilarImageFilter",
      "similar_image_filter_threshold": "similarImageFilterThreshold",
      "similar_image_filter_max_skip_frame": "similarImageFilterMaxSkipFrame",
      "skip_diffusion": "skipDiffusion",
      "image_preprocessing": "imagePreprocessing",
      "image_postprocessing": "imagePostprocessing",
      "latent_preprocessing": "latentPreprocessing",
      "latent_postprocessing": "latentPostprocessing",
      "ip_adapter": "ipAdapter",
      "ip_adapter_style_image_url": "ipAdapterStyleImageUrl",
      "cached_attention": "cachedAttention",
    });
  }),
);

export function sd153FromJSON(
  jsonString: string,
): SafeParseResult<Sd153, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sd153$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sd153' from JSON`,
  );
}
