/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smartUnion.js";

/**
 * Model to use for generation
 */
export const Sd152ModelId = {
  LykonDreamshaper8: "Lykon/dreamshaper-8",
  PromptheroOpenjourneyV4: "prompthero/openjourney-v4",
} as const;
/**
 * Model to use for generation
 */
export type Sd152ModelId = ClosedEnum<typeof Sd152ModelId>;

export type Sd152Prompt1 = string | number;

/**
 * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
 */
export type Sd152Prompt2 = string | Array<Array<string | number>>;

/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export const Sd152PromptInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export type Sd152PromptInterpolationMethod = ClosedEnum<
  typeof Sd152PromptInterpolationMethod
>;

/**
 * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
 */
export type Sd152LoraDict = {};

/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export const Sd152Acceleration = {
  None: "none",
  Xformers: "xformers",
  Tensorrt: "tensorrt",
} as const;
/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export type Sd152Acceleration = ClosedEnum<typeof Sd152Acceleration>;

export type Sd152Seed1 = number | number;

/**
 * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
 */
export type Sd152Seed2 = number | Array<Array<number | number>>;

/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export const Sd152SeedInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export type Sd152SeedInterpolationMethod = ClosedEnum<
  typeof Sd152SeedInterpolationMethod
>;

export const Sd152ImagePreprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type Sd152ImagePreprocessingType = ClosedEnum<
  typeof Sd152ImagePreprocessingType
>;

export type Sd152ImagePreprocessingProcessor = {
  type: Sd152ImagePreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image preprocessor configurations for image processing
 */
export type Sd152ImagePreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<Sd152ImagePreprocessingProcessor>;
};

export const Sd152ImagePostprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type Sd152ImagePostprocessingType = ClosedEnum<
  typeof Sd152ImagePostprocessingType
>;

export type Sd152ImagePostprocessingProcessor = {
  type: Sd152ImagePostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image postprocessor configurations for image processing
 *
 * @remarks
 *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
 */
export type Sd152ImagePostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<Sd152ImagePostprocessingProcessor>;
};

export const Sd152LatentPreprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type Sd152LatentPreprocessingType = ClosedEnum<
  typeof Sd152LatentPreprocessingType
>;

export type Sd152LatentPreprocessingProcessor = {
  type: Sd152LatentPreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent preprocessor configurations for latent processing
 */
export type Sd152LatentPreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<Sd152LatentPreprocessingProcessor>;
};

export const Sd152LatentPostprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type Sd152LatentPostprocessingType = ClosedEnum<
  typeof Sd152LatentPostprocessingType
>;

export type Sd152LatentPostprocessingProcessor = {
  type: Sd152LatentPostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent postprocessor configurations for latent processing
 */
export type Sd152LatentPostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<Sd152LatentPostprocessingProcessor>;
};

/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export const Sd152ControlnetModelId = {
  LllyasvielControlV11f1pSd15Depth: "lllyasviel/control_v11f1p_sd15_depth",
  LllyasvielControlV11f1eSd15Tile: "lllyasviel/control_v11f1e_sd15_tile",
  LllyasvielControlV11pSd15Canny: "lllyasviel/control_v11p_sd15_canny",
  DaydreamliveTemporalNet2StableDiffusionV15:
    "daydreamlive/TemporalNet2-stable-diffusion-v1-5",
} as const;
/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export type Sd152ControlnetModelId = ClosedEnum<typeof Sd152ControlnetModelId>;

/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export const Sd152Preprocessor = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export type Sd152Preprocessor = ClosedEnum<typeof Sd152Preprocessor>;

export type Sd152Controlnet = {
  /**
   * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
   */
  modelId: Sd152ControlnetModelId;
  /**
   * Strength of the ControlNet's influence on generation. Higher values make the model follow the control signal more strictly. Typical range 0.0-1.0, where 0.0 disables the control and 1.0 applies full control. Default: 1.0
   */
  conditioningScale: number;
  /**
   * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
   */
  preprocessor: Sd152Preprocessor;
  /**
   * Preprocessor parameters
   */
  preprocessorParams?: { [k: string]: any } | undefined;
  /**
   * Whether this ControlNet is active. Disabled ControlNets are not loaded. Default: true
   */
  enabled: boolean;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance begins. 0.0 means guidance starts from the beginning.
   */
  controlGuidanceStart?: number | undefined;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance ends. 1.0 means guidance continues until the end.
   */
  controlGuidanceEnd?: number | undefined;
};

/**
 * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
 */
export const Sd152TypeRegular = {
  Regular: "regular",
} as const;
/**
 * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
 */
export type Sd152TypeRegular = ClosedEnum<typeof Sd152TypeRegular>;

/**
 * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
 */
export const Sd152WeightType = {
  Linear: "linear",
  EaseIn: "ease in",
  EaseOut: "ease out",
  EaseInOut: "ease in-out",
  ReverseInOut: "reverse in-out",
  WeakInput: "weak input",
  WeakOutput: "weak output",
  WeakMiddle: "weak middle",
  StrongMiddle: "strong middle",
  StyleTransfer: "style transfer",
  Composition: "composition",
  StrongStyleTransfer: "strong style transfer",
  StyleAndComposition: "style and composition",
  StyleTransferPrecise: "style transfer precise",
  CompositionPrecise: "composition precise",
} as const;
/**
 * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
 */
export type Sd152WeightType = ClosedEnum<typeof Sd152WeightType>;

/**
 * IP adapter — Turns on IP-Adapter style conditioning and is fully hot-swappable. Available for SDXL, SDXL-faceid, SD1.5
 */
export type Sd152IpAdapter = {
  /**
   * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
   */
  type?: Sd152TypeRegular | undefined;
  /**
   * Whether IP adapter is enabled
   */
  enabled?: boolean | undefined;
  /**
   * Strength of IP adapter style conditioning
   */
  scale?: number | undefined;
  /**
   * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
   */
  weightType?: Sd152WeightType | undefined;
};

/**
 * Cached attention (StreamV2V) configuration. Enable cached attention to reuse key/value tensors across frames. ⚠️ NOTE: Enabling or disabling cached_attention requires a pipeline reload as it uses a different pipeline.
 */
export type Sd152CachedAttention = {
  /**
   * Whether this cached attention is active. Enable cached attention to reuse key/value tensors across frames.
   */
  enabled: boolean;
  /**
   * Number of frames retained in the attention cache. Number of historical K/V frames to retain. Limited by TensorRT engine exports.
   */
  maxFrames: number;
  /**
   * Cadence (number of frames) for refreshing cached key/value tensors i.e How often (in number of frames) to refresh the cache.
   *
   * @remarks
   *       It is now **frame-based** (not seconds). It accepts integers 1-240, representing how many frames elapse between cache refreshes.
   */
  interval: number;
};

export type Sd152 = {
  /**
   * Model to use for generation
   */
  modelId: Sd152ModelId;
  /**
   * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
   */
  prompt?: string | Array<Array<string | number>> | undefined;
  /**
   * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
   */
  promptInterpolationMethod?: Sd152PromptInterpolationMethod | undefined;
  /**
   * Whether to normalize prompt weights to sum to 1.0 for consistent generation.
   */
  normalizePromptWeights?: boolean | undefined;
  /**
   * Whether to normalize seed weights to sum to 1.0 for consistent generation.
   */
  normalizeSeedWeights?: boolean | undefined;
  /**
   * Text describing what to avoid in the generated image.
   */
  negativePrompt?: string | undefined;
  /**
   * Strength of prompt adherence. Higher values make the model follow the prompt more strictly.
   */
  guidanceScale?: number | undefined;
  /**
   * Delta sets per-frame denoising progress: lower delta means steadier, less flicker but slower/softer; higher delta means faster, sharper but more flicker/artifacts (often reduce CFG).
   */
  delta?: number | undefined;
  /**
   * Builds the full denoising schedule (the 'grid' of possible refinement steps). Changing it changes what each step number (t_index_list value) means. Keep it fixed for a session and only adjust if you're deliberately redefining the schedule; if you do, proportionally remap your t_index_list. Typical range 10-100 with default being 50.
   */
  numInferenceSteps?: number | undefined;
  /**
   * The ordered list of step indices from the num_inference_steps schedule to execute per frame. Each index is one model pass, so latency scales with the list length. Higher indices (e.g., 40–49 on a 50-step grid) mainly polish and preserve structure (lower flicker), while lower indices (<20) rewrite structure (more flicker, creative). Values must be non-decreasing, and each between 0 and num_inference_steps.
   *
   * @remarks
   *
   * ⚠️ NOTE: t_index_list must have 1–4 elements, non-decreasing, and within [0, num_inference_steps]. The value should not go above 50.
   */
  tIndexList?: Array<number> | undefined;
  /**
   * Whether to use safety checker for content filtering
   */
  useSafetyChecker?: boolean | undefined;
  /**
   * Output image width in pixels. Must be divisible by 64 and between 384-1024.
   */
  width?: number | undefined;
  /**
   * Output image height in pixels. Must be divisible by 64 and between 384-1024.
   */
  height?: number | undefined;
  /**
   * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
   */
  loraDict?: Sd152LoraDict | null | undefined;
  /**
   * Whether to use Latent Consistency Model LoRA for faster inference.
   */
  useLcmLora?: boolean | undefined;
  /**
   * Identifier for the LCM LoRA model to use. Example: "latent-consistency/lcm-lora-sdv1-5"
   */
  lcmLoraId?: string | undefined;
  /**
   * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
   */
  acceleration?: Sd152Acceleration | undefined;
  /**
   * Whether to process multiple denoising steps in a single batch for efficiency.
   */
  useDenoisingBatch?: boolean | undefined;
  /**
   * Whether to add noise to input frames before processing. Enabling this slightly re-noises each frame to improve temporal stability, reduce ghosting/texture sticking, and prevent drift; disabling can yield sharper, lower-latency results but may increase flicker and artifact accumulation over time.
   */
  doAddNoise?: boolean | undefined;
  /**
   * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
   */
  seed?: number | Array<Array<number | number>> | undefined;
  /**
   * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
   */
  seedInterpolationMethod?: Sd152SeedInterpolationMethod | undefined;
  /**
   * Whether to skip frames that are too similar to the previous output to reduce flicker.
   */
  enableSimilarImageFilter?: boolean | undefined;
  /**
   * Similarity threshold for the image filter. Higher values allow more variation between frames.
   */
  similarImageFilterThreshold?: number | undefined;
  /**
   * Maximum number of consecutive frames that can be skipped by the similarity filter.
   */
  similarImageFilterMaxSkipFrame?: number | undefined;
  /**
   * Whether to skip the diffusion process. Any ControlNets or diffusion-only parameters are ignored when enabled.
   *
   * @remarks
   *         Example use cases:
   *         - Stream the output of a preprocessor (e.g. live depth maps or pose skeletons),
   *         - Run post-processors like RealESRGAN upscaler on externally provided frames,
   *         - Warm a pipeline without paying the diffusion cost.
   *       ⚠️ NOTE: skip_diffusion is evaluated at pipeline creation time; switching mid-stream triggers a pipeline reload.
   */
  skipDiffusion?: boolean | undefined;
  /**
   * List of image preprocessor configurations for image processing
   */
  imagePreprocessing?: Sd152ImagePreprocessing | undefined;
  /**
   * List of image postprocessor configurations for image processing
   *
   * @remarks
   *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
   */
  imagePostprocessing?: Sd152ImagePostprocessing | undefined;
  /**
   * List of latent preprocessor configurations for latent processing
   */
  latentPreprocessing?: Sd152LatentPreprocessing | undefined;
  /**
   * List of latent postprocessor configurations for latent processing
   */
  latentPostprocessing?: Sd152LatentPostprocessing | undefined;
  /**
   * List of ControlNet configurations for guided generation. Each ControlNet provides different types of conditioning (pose, edges, depth, etc.). Dynamic updates limited to conditioning_scale changes only; cannot add new ControlNets or change model_id/preprocessor/params without reload.
   */
  controlnets?: Array<Sd152Controlnet> | undefined;
  /**
   * IP adapter — Turns on IP-Adapter style conditioning and is fully hot-swappable. Available for SDXL, SDXL-faceid, SD1.5
   */
  ipAdapter?: Sd152IpAdapter | undefined;
  /**
   * HTTPS URL or base64-encoded data URI (data:image/[type];base64,...) of the style image to use. Base64 images are automatically cached and uploaded to storage with content-based deduplication. Maximum size: 5MB. When set, the runtime downloads the image and configures the pipeline; if omitted, a default style image is used. For 'faceid' type, the image must contain a clear face. Available for SDXL, SDXL-faceid, SD1.5
   */
  ipAdapterStyleImageUrl?: string | undefined;
  /**
   * Cached attention (StreamV2V) configuration. Enable cached attention to reuse key/value tensors across frames. ⚠️ NOTE: Enabling or disabling cached_attention requires a pipeline reload as it uses a different pipeline.
   */
  cachedAttention?: Sd152CachedAttention | undefined;
};

/** @internal */
export const Sd152ModelId$outboundSchema: z.ZodMiniEnum<typeof Sd152ModelId> = z
  .enum(Sd152ModelId);

/** @internal */
export type Sd152Prompt1$Outbound = string | number;

/** @internal */
export const Sd152Prompt1$outboundSchema: z.ZodMiniType<
  Sd152Prompt1$Outbound,
  Sd152Prompt1
> = smartUnion([z.string(), z.number()]);

export function sd152Prompt1ToJSON(sd152Prompt1: Sd152Prompt1): string {
  return JSON.stringify(Sd152Prompt1$outboundSchema.parse(sd152Prompt1));
}

/** @internal */
export type Sd152Prompt2$Outbound = string | Array<Array<string | number>>;

/** @internal */
export const Sd152Prompt2$outboundSchema: z.ZodMiniType<
  Sd152Prompt2$Outbound,
  Sd152Prompt2
> = smartUnion([
  z.string(),
  z.array(z.array(smartUnion([z.string(), z.number()]))),
]);

export function sd152Prompt2ToJSON(sd152Prompt2: Sd152Prompt2): string {
  return JSON.stringify(Sd152Prompt2$outboundSchema.parse(sd152Prompt2));
}

/** @internal */
export const Sd152PromptInterpolationMethod$outboundSchema: z.ZodMiniEnum<
  typeof Sd152PromptInterpolationMethod
> = z.enum(Sd152PromptInterpolationMethod);

/** @internal */
export type Sd152LoraDict$Outbound = {};

/** @internal */
export const Sd152LoraDict$outboundSchema: z.ZodMiniType<
  Sd152LoraDict$Outbound,
  Sd152LoraDict
> = z.object({});

export function sd152LoraDictToJSON(sd152LoraDict: Sd152LoraDict): string {
  return JSON.stringify(Sd152LoraDict$outboundSchema.parse(sd152LoraDict));
}

/** @internal */
export const Sd152Acceleration$outboundSchema: z.ZodMiniEnum<
  typeof Sd152Acceleration
> = z.enum(Sd152Acceleration);

/** @internal */
export type Sd152Seed1$Outbound = number | number;

/** @internal */
export const Sd152Seed1$outboundSchema: z.ZodMiniType<
  Sd152Seed1$Outbound,
  Sd152Seed1
> = smartUnion([z.int(), z.number()]);

export function sd152Seed1ToJSON(sd152Seed1: Sd152Seed1): string {
  return JSON.stringify(Sd152Seed1$outboundSchema.parse(sd152Seed1));
}

/** @internal */
export type Sd152Seed2$Outbound = number | Array<Array<number | number>>;

/** @internal */
export const Sd152Seed2$outboundSchema: z.ZodMiniType<
  Sd152Seed2$Outbound,
  Sd152Seed2
> = smartUnion([z.int(), z.array(z.array(smartUnion([z.int(), z.number()])))]);

export function sd152Seed2ToJSON(sd152Seed2: Sd152Seed2): string {
  return JSON.stringify(Sd152Seed2$outboundSchema.parse(sd152Seed2));
}

/** @internal */
export const Sd152SeedInterpolationMethod$outboundSchema: z.ZodMiniEnum<
  typeof Sd152SeedInterpolationMethod
> = z.enum(Sd152SeedInterpolationMethod);

/** @internal */
export const Sd152ImagePreprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof Sd152ImagePreprocessingType
> = z.enum(Sd152ImagePreprocessingType);

/** @internal */
export type Sd152ImagePreprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const Sd152ImagePreprocessingProcessor$outboundSchema: z.ZodMiniType<
  Sd152ImagePreprocessingProcessor$Outbound,
  Sd152ImagePreprocessingProcessor
> = z.object({
  type: Sd152ImagePreprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sd152ImagePreprocessingProcessorToJSON(
  sd152ImagePreprocessingProcessor: Sd152ImagePreprocessingProcessor,
): string {
  return JSON.stringify(
    Sd152ImagePreprocessingProcessor$outboundSchema.parse(
      sd152ImagePreprocessingProcessor,
    ),
  );
}

/** @internal */
export type Sd152ImagePreprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<Sd152ImagePreprocessingProcessor$Outbound>;
};

/** @internal */
export const Sd152ImagePreprocessing$outboundSchema: z.ZodMiniType<
  Sd152ImagePreprocessing$Outbound,
  Sd152ImagePreprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => Sd152ImagePreprocessingProcessor$outboundSchema),
  ),
});

export function sd152ImagePreprocessingToJSON(
  sd152ImagePreprocessing: Sd152ImagePreprocessing,
): string {
  return JSON.stringify(
    Sd152ImagePreprocessing$outboundSchema.parse(sd152ImagePreprocessing),
  );
}

/** @internal */
export const Sd152ImagePostprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof Sd152ImagePostprocessingType
> = z.enum(Sd152ImagePostprocessingType);

/** @internal */
export type Sd152ImagePostprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const Sd152ImagePostprocessingProcessor$outboundSchema: z.ZodMiniType<
  Sd152ImagePostprocessingProcessor$Outbound,
  Sd152ImagePostprocessingProcessor
> = z.object({
  type: Sd152ImagePostprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sd152ImagePostprocessingProcessorToJSON(
  sd152ImagePostprocessingProcessor: Sd152ImagePostprocessingProcessor,
): string {
  return JSON.stringify(
    Sd152ImagePostprocessingProcessor$outboundSchema.parse(
      sd152ImagePostprocessingProcessor,
    ),
  );
}

/** @internal */
export type Sd152ImagePostprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<Sd152ImagePostprocessingProcessor$Outbound>;
};

/** @internal */
export const Sd152ImagePostprocessing$outboundSchema: z.ZodMiniType<
  Sd152ImagePostprocessing$Outbound,
  Sd152ImagePostprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => Sd152ImagePostprocessingProcessor$outboundSchema),
  ),
});

export function sd152ImagePostprocessingToJSON(
  sd152ImagePostprocessing: Sd152ImagePostprocessing,
): string {
  return JSON.stringify(
    Sd152ImagePostprocessing$outboundSchema.parse(sd152ImagePostprocessing),
  );
}

/** @internal */
export const Sd152LatentPreprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof Sd152LatentPreprocessingType
> = z.enum(Sd152LatentPreprocessingType);

/** @internal */
export type Sd152LatentPreprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const Sd152LatentPreprocessingProcessor$outboundSchema: z.ZodMiniType<
  Sd152LatentPreprocessingProcessor$Outbound,
  Sd152LatentPreprocessingProcessor
> = z.object({
  type: Sd152LatentPreprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sd152LatentPreprocessingProcessorToJSON(
  sd152LatentPreprocessingProcessor: Sd152LatentPreprocessingProcessor,
): string {
  return JSON.stringify(
    Sd152LatentPreprocessingProcessor$outboundSchema.parse(
      sd152LatentPreprocessingProcessor,
    ),
  );
}

/** @internal */
export type Sd152LatentPreprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<Sd152LatentPreprocessingProcessor$Outbound>;
};

/** @internal */
export const Sd152LatentPreprocessing$outboundSchema: z.ZodMiniType<
  Sd152LatentPreprocessing$Outbound,
  Sd152LatentPreprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => Sd152LatentPreprocessingProcessor$outboundSchema),
  ),
});

export function sd152LatentPreprocessingToJSON(
  sd152LatentPreprocessing: Sd152LatentPreprocessing,
): string {
  return JSON.stringify(
    Sd152LatentPreprocessing$outboundSchema.parse(sd152LatentPreprocessing),
  );
}

/** @internal */
export const Sd152LatentPostprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof Sd152LatentPostprocessingType
> = z.enum(Sd152LatentPostprocessingType);

/** @internal */
export type Sd152LatentPostprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const Sd152LatentPostprocessingProcessor$outboundSchema: z.ZodMiniType<
  Sd152LatentPostprocessingProcessor$Outbound,
  Sd152LatentPostprocessingProcessor
> = z.object({
  type: Sd152LatentPostprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sd152LatentPostprocessingProcessorToJSON(
  sd152LatentPostprocessingProcessor: Sd152LatentPostprocessingProcessor,
): string {
  return JSON.stringify(
    Sd152LatentPostprocessingProcessor$outboundSchema.parse(
      sd152LatentPostprocessingProcessor,
    ),
  );
}

/** @internal */
export type Sd152LatentPostprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<Sd152LatentPostprocessingProcessor$Outbound>;
};

/** @internal */
export const Sd152LatentPostprocessing$outboundSchema: z.ZodMiniType<
  Sd152LatentPostprocessing$Outbound,
  Sd152LatentPostprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => Sd152LatentPostprocessingProcessor$outboundSchema),
  ),
});

export function sd152LatentPostprocessingToJSON(
  sd152LatentPostprocessing: Sd152LatentPostprocessing,
): string {
  return JSON.stringify(
    Sd152LatentPostprocessing$outboundSchema.parse(sd152LatentPostprocessing),
  );
}

/** @internal */
export const Sd152ControlnetModelId$outboundSchema: z.ZodMiniEnum<
  typeof Sd152ControlnetModelId
> = z.enum(Sd152ControlnetModelId);

/** @internal */
export const Sd152Preprocessor$outboundSchema: z.ZodMiniEnum<
  typeof Sd152Preprocessor
> = z.enum(Sd152Preprocessor);

/** @internal */
export type Sd152Controlnet$Outbound = {
  model_id: string;
  conditioning_scale: number;
  preprocessor: string;
  preprocessor_params?: { [k: string]: any } | undefined;
  enabled: boolean;
  control_guidance_start?: number | undefined;
  control_guidance_end?: number | undefined;
};

/** @internal */
export const Sd152Controlnet$outboundSchema: z.ZodMiniType<
  Sd152Controlnet$Outbound,
  Sd152Controlnet
> = z.pipe(
  z.object({
    modelId: Sd152ControlnetModelId$outboundSchema,
    conditioningScale: z.number(),
    preprocessor: Sd152Preprocessor$outboundSchema,
    preprocessorParams: z.optional(z.record(z.string(), z.any())),
    enabled: z.boolean(),
    controlGuidanceStart: z.optional(z.number()),
    controlGuidanceEnd: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      modelId: "model_id",
      conditioningScale: "conditioning_scale",
      preprocessorParams: "preprocessor_params",
      controlGuidanceStart: "control_guidance_start",
      controlGuidanceEnd: "control_guidance_end",
    });
  }),
);

export function sd152ControlnetToJSON(
  sd152Controlnet: Sd152Controlnet,
): string {
  return JSON.stringify(Sd152Controlnet$outboundSchema.parse(sd152Controlnet));
}

/** @internal */
export const Sd152TypeRegular$outboundSchema: z.ZodMiniEnum<
  typeof Sd152TypeRegular
> = z.enum(Sd152TypeRegular);

/** @internal */
export const Sd152WeightType$outboundSchema: z.ZodMiniEnum<
  typeof Sd152WeightType
> = z.enum(Sd152WeightType);

/** @internal */
export type Sd152IpAdapter$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  scale?: number | undefined;
  weight_type?: string | undefined;
};

/** @internal */
export const Sd152IpAdapter$outboundSchema: z.ZodMiniType<
  Sd152IpAdapter$Outbound,
  Sd152IpAdapter
> = z.pipe(
  z.object({
    type: z._default(Sd152TypeRegular$outboundSchema, "regular"),
    enabled: z.optional(z.boolean()),
    scale: z.optional(z.number()),
    weightType: z.optional(Sd152WeightType$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      weightType: "weight_type",
    });
  }),
);

export function sd152IpAdapterToJSON(sd152IpAdapter: Sd152IpAdapter): string {
  return JSON.stringify(Sd152IpAdapter$outboundSchema.parse(sd152IpAdapter));
}

/** @internal */
export type Sd152CachedAttention$Outbound = {
  enabled: boolean;
  max_frames: number;
  interval: number;
};

/** @internal */
export const Sd152CachedAttention$outboundSchema: z.ZodMiniType<
  Sd152CachedAttention$Outbound,
  Sd152CachedAttention
> = z.pipe(
  z.object({
    enabled: z.boolean(),
    maxFrames: z.int(),
    interval: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      maxFrames: "max_frames",
    });
  }),
);

export function sd152CachedAttentionToJSON(
  sd152CachedAttention: Sd152CachedAttention,
): string {
  return JSON.stringify(
    Sd152CachedAttention$outboundSchema.parse(sd152CachedAttention),
  );
}

/** @internal */
export type Sd152$Outbound = {
  model_id: string;
  prompt?: string | Array<Array<string | number>> | undefined;
  prompt_interpolation_method?: string | undefined;
  normalize_prompt_weights?: boolean | undefined;
  normalize_seed_weights?: boolean | undefined;
  negative_prompt?: string | undefined;
  guidance_scale?: number | undefined;
  delta?: number | undefined;
  num_inference_steps?: number | undefined;
  t_index_list?: Array<number> | undefined;
  use_safety_checker?: boolean | undefined;
  width?: number | undefined;
  height?: number | undefined;
  lora_dict?: Sd152LoraDict$Outbound | null | undefined;
  use_lcm_lora?: boolean | undefined;
  lcm_lora_id?: string | undefined;
  acceleration?: string | undefined;
  use_denoising_batch?: boolean | undefined;
  do_add_noise?: boolean | undefined;
  seed?: number | Array<Array<number | number>> | undefined;
  seed_interpolation_method?: string | undefined;
  enable_similar_image_filter?: boolean | undefined;
  similar_image_filter_threshold?: number | undefined;
  similar_image_filter_max_skip_frame?: number | undefined;
  skip_diffusion?: boolean | undefined;
  image_preprocessing?: Sd152ImagePreprocessing$Outbound | undefined;
  image_postprocessing?: Sd152ImagePostprocessing$Outbound | undefined;
  latent_preprocessing?: Sd152LatentPreprocessing$Outbound | undefined;
  latent_postprocessing?: Sd152LatentPostprocessing$Outbound | undefined;
  controlnets?: Array<Sd152Controlnet$Outbound> | undefined;
  ip_adapter?: Sd152IpAdapter$Outbound | undefined;
  ip_adapter_style_image_url?: string | undefined;
  cached_attention?: Sd152CachedAttention$Outbound | undefined;
};

/** @internal */
export const Sd152$outboundSchema: z.ZodMiniType<Sd152$Outbound, Sd152> = z
  .pipe(
    z.object({
      modelId: Sd152ModelId$outboundSchema,
      prompt: z.optional(
        smartUnion([
          z.string(),
          z.array(z.array(smartUnion([z.string(), z.number()]))),
        ]),
      ),
      promptInterpolationMethod: z.optional(
        Sd152PromptInterpolationMethod$outboundSchema,
      ),
      normalizePromptWeights: z.optional(z.boolean()),
      normalizeSeedWeights: z.optional(z.boolean()),
      negativePrompt: z.optional(z.string()),
      guidanceScale: z.optional(z.number()),
      delta: z.optional(z.number()),
      numInferenceSteps: z.optional(z.int()),
      tIndexList: z.optional(z.array(z.int())),
      useSafetyChecker: z.optional(z.boolean()),
      width: z.optional(z.int()),
      height: z.optional(z.int()),
      loraDict: z.optional(
        z.nullable(z.lazy(() => Sd152LoraDict$outboundSchema)),
      ),
      useLcmLora: z.optional(z.boolean()),
      lcmLoraId: z.optional(z.string()),
      acceleration: z.optional(Sd152Acceleration$outboundSchema),
      useDenoisingBatch: z.optional(z.boolean()),
      doAddNoise: z.optional(z.boolean()),
      seed: z.optional(
        smartUnion([
          z.int(),
          z.array(z.array(smartUnion([z.int(), z.number()]))),
        ]),
      ),
      seedInterpolationMethod: z.optional(
        Sd152SeedInterpolationMethod$outboundSchema,
      ),
      enableSimilarImageFilter: z.optional(z.boolean()),
      similarImageFilterThreshold: z.optional(z.number()),
      similarImageFilterMaxSkipFrame: z.optional(z.int()),
      skipDiffusion: z.optional(z.boolean()),
      imagePreprocessing: z.optional(
        z.lazy(() => Sd152ImagePreprocessing$outboundSchema),
      ),
      imagePostprocessing: z.optional(
        z.lazy(() => Sd152ImagePostprocessing$outboundSchema),
      ),
      latentPreprocessing: z.optional(
        z.lazy(() => Sd152LatentPreprocessing$outboundSchema),
      ),
      latentPostprocessing: z.optional(
        z.lazy(() => Sd152LatentPostprocessing$outboundSchema),
      ),
      controlnets: z.optional(
        z.array(z.lazy(() => Sd152Controlnet$outboundSchema)),
      ),
      ipAdapter: z.optional(z.lazy(() => Sd152IpAdapter$outboundSchema)),
      ipAdapterStyleImageUrl: z.optional(z.string()),
      cachedAttention: z.optional(
        z.lazy(() => Sd152CachedAttention$outboundSchema),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        modelId: "model_id",
        promptInterpolationMethod: "prompt_interpolation_method",
        normalizePromptWeights: "normalize_prompt_weights",
        normalizeSeedWeights: "normalize_seed_weights",
        negativePrompt: "negative_prompt",
        guidanceScale: "guidance_scale",
        numInferenceSteps: "num_inference_steps",
        tIndexList: "t_index_list",
        useSafetyChecker: "use_safety_checker",
        loraDict: "lora_dict",
        useLcmLora: "use_lcm_lora",
        lcmLoraId: "lcm_lora_id",
        useDenoisingBatch: "use_denoising_batch",
        doAddNoise: "do_add_noise",
        seedInterpolationMethod: "seed_interpolation_method",
        enableSimilarImageFilter: "enable_similar_image_filter",
        similarImageFilterThreshold: "similar_image_filter_threshold",
        similarImageFilterMaxSkipFrame: "similar_image_filter_max_skip_frame",
        skipDiffusion: "skip_diffusion",
        imagePreprocessing: "image_preprocessing",
        imagePostprocessing: "image_postprocessing",
        latentPreprocessing: "latent_preprocessing",
        latentPostprocessing: "latent_postprocessing",
        ipAdapter: "ip_adapter",
        ipAdapterStyleImageUrl: "ip_adapter_style_image_url",
        cachedAttention: "cached_attention",
      });
    }),
  );

export function sd152ToJSON(sd152: Sd152): string {
  return JSON.stringify(Sd152$outboundSchema.parse(sd152));
}
