/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smartUnion.js";

export type SDTurbo2Prompt1 = string | number;

/**
 * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
 */
export type SDTurbo2Prompt2 = string | Array<Array<string | number>>;

/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export const SDTurbo2PromptInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export type SDTurbo2PromptInterpolationMethod = ClosedEnum<
  typeof SDTurbo2PromptInterpolationMethod
>;

/**
 * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
 */
export type SDTurbo2LoraDict = {};

/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export const SDTurbo2Acceleration = {
  None: "none",
  Xformers: "xformers",
  Tensorrt: "tensorrt",
} as const;
/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export type SDTurbo2Acceleration = ClosedEnum<typeof SDTurbo2Acceleration>;

export type SDTurbo2Seed1 = number | number;

/**
 * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
 */
export type SDTurbo2Seed2 = number | Array<Array<number | number>>;

/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export const SDTurbo2SeedInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export type SDTurbo2SeedInterpolationMethod = ClosedEnum<
  typeof SDTurbo2SeedInterpolationMethod
>;

export const SDTurbo2ImagePreprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type SDTurbo2ImagePreprocessingType = ClosedEnum<
  typeof SDTurbo2ImagePreprocessingType
>;

export type SDTurbo2ImagePreprocessingProcessor = {
  type: SDTurbo2ImagePreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image preprocessor configurations for image processing
 */
export type SDTurbo2ImagePreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<SDTurbo2ImagePreprocessingProcessor>;
};

export const SDTurbo2ImagePostprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type SDTurbo2ImagePostprocessingType = ClosedEnum<
  typeof SDTurbo2ImagePostprocessingType
>;

export type SDTurbo2ImagePostprocessingProcessor = {
  type: SDTurbo2ImagePostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image postprocessor configurations for image processing
 *
 * @remarks
 *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
 */
export type SDTurbo2ImagePostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<SDTurbo2ImagePostprocessingProcessor>;
};

export const SDTurbo2LatentPreprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type SDTurbo2LatentPreprocessingType = ClosedEnum<
  typeof SDTurbo2LatentPreprocessingType
>;

export type SDTurbo2LatentPreprocessingProcessor = {
  type: SDTurbo2LatentPreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent preprocessor configurations for latent processing
 */
export type SDTurbo2LatentPreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<SDTurbo2LatentPreprocessingProcessor>;
};

export const SDTurbo2LatentPostprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type SDTurbo2LatentPostprocessingType = ClosedEnum<
  typeof SDTurbo2LatentPostprocessingType
>;

export type SDTurbo2LatentPostprocessingProcessor = {
  type: SDTurbo2LatentPostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent postprocessor configurations for latent processing
 */
export type SDTurbo2LatentPostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<SDTurbo2LatentPostprocessingProcessor>;
};

/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export const SDTurbo2ControlnetModelId = {
  ThibaudControlnetSd21OpenposeDiffusers:
    "thibaud/controlnet-sd21-openpose-diffusers",
  ThibaudControlnetSd21HedDiffusers: "thibaud/controlnet-sd21-hed-diffusers",
  ThibaudControlnetSd21CannyDiffusers:
    "thibaud/controlnet-sd21-canny-diffusers",
  ThibaudControlnetSd21DepthDiffusers:
    "thibaud/controlnet-sd21-depth-diffusers",
  ThibaudControlnetSd21ColorDiffusers:
    "thibaud/controlnet-sd21-color-diffusers",
  DaydreamliveTemporalNet2StableDiffusion21:
    "daydreamlive/TemporalNet2-stable-diffusion-2-1",
} as const;
/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export type SDTurbo2ControlnetModelId = ClosedEnum<
  typeof SDTurbo2ControlnetModelId
>;

/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export const SDTurbo2Preprocessor = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export type SDTurbo2Preprocessor = ClosedEnum<typeof SDTurbo2Preprocessor>;

export type SDTurbo2Controlnet = {
  /**
   * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
   */
  modelId: SDTurbo2ControlnetModelId;
  /**
   * Strength of the ControlNet's influence on generation. Higher values make the model follow the control signal more strictly. Typical range 0.0-1.0, where 0.0 disables the control and 1.0 applies full control. Default: 1.0
   */
  conditioningScale: number;
  /**
   * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
   */
  preprocessor: SDTurbo2Preprocessor;
  /**
   * Additional parameters for the preprocessor. For example, canny edge detection uses 'low_threshold' and 'high_threshold' values.
   */
  preprocessorParams?: { [k: string]: any } | undefined;
  /**
   * Whether this ControlNet is active. Disabled ControlNets are not loaded. Default: true
   */
  enabled: boolean;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance begins. 0.0 means guidance starts from the beginning.
   */
  controlGuidanceStart?: number | undefined;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance ends. 1.0 means guidance continues until the end.
   */
  controlGuidanceEnd?: number | undefined;
};

export type SDTurbo2 = {
  modelId: "stabilityai/sd-turbo";
  /**
   * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
   */
  prompt?: string | Array<Array<string | number>> | undefined;
  /**
   * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
   */
  promptInterpolationMethod?: SDTurbo2PromptInterpolationMethod | undefined;
  /**
   * Whether to normalize prompt weights to sum to 1.0 for consistent generation.
   */
  normalizePromptWeights?: boolean | undefined;
  /**
   * Whether to normalize seed weights to sum to 1.0 for consistent generation.
   */
  normalizeSeedWeights?: boolean | undefined;
  /**
   * Text describing what to avoid in the generated image.
   */
  negativePrompt?: string | undefined;
  /**
   * Strength of prompt adherence. Higher values make the model follow the prompt more strictly.
   */
  guidanceScale?: number | undefined;
  /**
   * Delta sets per-frame denoising progress: lower delta means steadier, less flicker but slower/softer; higher delta means faster, sharper but more flicker/artifacts (often reduce CFG).
   */
  delta?: number | undefined;
  /**
   * Builds the full denoising schedule (the 'grid' of possible refinement steps). Changing it changes what each step number (t_index_list value) means. Keep it fixed for a session and only adjust if you're deliberately redefining the schedule; if you do, proportionally remap your t_index_list. Typical range 10-100 with default being 50.
   */
  numInferenceSteps?: number | undefined;
  /**
   * The ordered list of step indices from the num_inference_steps schedule to execute per frame. Each index is one model pass, so latency scales with the list length. Higher indices (e.g., 40–49 on a 50-step grid) mainly polish and preserve structure (lower flicker), while lower indices (<20) rewrite structure (more flicker, creative). Values must be non-decreasing, and each between 0 and num_inference_steps.
   *
   * @remarks
   *
   * ⚠️ NOTE: t_index_list must have 1–4 elements, non-decreasing, and within [0, num_inference_steps]. The value should not go above 50.
   */
  tIndexList?: Array<number> | undefined;
  /**
   * Whether to use safety checker for content filtering
   */
  useSafetyChecker?: boolean | undefined;
  /**
   * Output image width in pixels. Must be divisible by 64 and between 384-1024.
   */
  width?: number | undefined;
  /**
   * Output image height in pixels. Must be divisible by 64 and between 384-1024.
   */
  height?: number | undefined;
  /**
   * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
   */
  loraDict?: SDTurbo2LoraDict | null | undefined;
  /**
   * Whether to use Latent Consistency Model LoRA for faster inference.
   */
  useLcmLora?: boolean | undefined;
  /**
   * Identifier for the LCM LoRA model to use. Example: "latent-consistency/lcm-lora-sdv1-5"
   */
  lcmLoraId?: string | undefined;
  /**
   * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
   */
  acceleration?: SDTurbo2Acceleration | undefined;
  /**
   * Whether to process multiple denoising steps in a single batch for efficiency.
   */
  useDenoisingBatch?: boolean | undefined;
  /**
   * Whether to add noise to input frames before processing. Enabling this slightly re-noises each frame to improve temporal stability, reduce ghosting/texture sticking, and prevent drift; disabling can yield sharper, lower-latency results but may increase flicker and artifact accumulation over time.
   */
  doAddNoise?: boolean | undefined;
  /**
   * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
   */
  seed?: number | Array<Array<number | number>> | undefined;
  /**
   * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
   */
  seedInterpolationMethod?: SDTurbo2SeedInterpolationMethod | undefined;
  /**
   * Whether to skip frames that are too similar to the previous output to reduce flicker.
   */
  enableSimilarImageFilter?: boolean | undefined;
  /**
   * Similarity threshold for the image filter. Higher values allow more variation between frames.
   */
  similarImageFilterThreshold?: number | undefined;
  /**
   * Maximum number of consecutive frames that can be skipped by the similarity filter.
   */
  similarImageFilterMaxSkipFrame?: number | undefined;
  /**
   * Whether to skip the diffusion process. Any ControlNets or diffusion-only parameters are ignored when enabled.
   *
   * @remarks
   *         Example use cases:
   *         - Stream the output of a preprocessor (e.g. live depth maps or pose skeletons),
   *         - Run post-processors like RealESRGAN upscaler on externally provided frames,
   *         - Warm a pipeline without paying the diffusion cost.
   *       ⚠️ NOTE: skip_diffusion is evaluated at pipeline creation time; switching mid-stream triggers a pipeline reload.
   */
  skipDiffusion?: boolean | undefined;
  /**
   * List of image preprocessor configurations for image processing
   */
  imagePreprocessing?: SDTurbo2ImagePreprocessing | undefined;
  /**
   * List of image postprocessor configurations for image processing
   *
   * @remarks
   *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
   */
  imagePostprocessing?: SDTurbo2ImagePostprocessing | undefined;
  /**
   * List of latent preprocessor configurations for latent processing
   */
  latentPreprocessing?: SDTurbo2LatentPreprocessing | undefined;
  /**
   * List of latent postprocessor configurations for latent processing
   */
  latentPostprocessing?: SDTurbo2LatentPostprocessing | undefined;
  /**
   * List of ControlNet configurations for guided generation. Each ControlNet provides different types of conditioning (pose, edges, depth, etc.). Dynamic updates limited to conditioning_scale changes only; cannot add new ControlNets or change model_id/preprocessor/params without reload.
   */
  controlnets?: Array<SDTurbo2Controlnet> | undefined;
};

/** @internal */
export type SDTurbo2Prompt1$Outbound = string | number;

/** @internal */
export const SDTurbo2Prompt1$outboundSchema: z.ZodMiniType<
  SDTurbo2Prompt1$Outbound,
  SDTurbo2Prompt1
> = smartUnion([z.string(), z.number()]);

export function sdTurbo2Prompt1ToJSON(
  sdTurbo2Prompt1: SDTurbo2Prompt1,
): string {
  return JSON.stringify(SDTurbo2Prompt1$outboundSchema.parse(sdTurbo2Prompt1));
}

/** @internal */
export type SDTurbo2Prompt2$Outbound = string | Array<Array<string | number>>;

/** @internal */
export const SDTurbo2Prompt2$outboundSchema: z.ZodMiniType<
  SDTurbo2Prompt2$Outbound,
  SDTurbo2Prompt2
> = smartUnion([
  z.string(),
  z.array(z.array(smartUnion([z.string(), z.number()]))),
]);

export function sdTurbo2Prompt2ToJSON(
  sdTurbo2Prompt2: SDTurbo2Prompt2,
): string {
  return JSON.stringify(SDTurbo2Prompt2$outboundSchema.parse(sdTurbo2Prompt2));
}

/** @internal */
export const SDTurbo2PromptInterpolationMethod$outboundSchema: z.ZodMiniEnum<
  typeof SDTurbo2PromptInterpolationMethod
> = z.enum(SDTurbo2PromptInterpolationMethod);

/** @internal */
export type SDTurbo2LoraDict$Outbound = {};

/** @internal */
export const SDTurbo2LoraDict$outboundSchema: z.ZodMiniType<
  SDTurbo2LoraDict$Outbound,
  SDTurbo2LoraDict
> = z.object({});

export function sdTurbo2LoraDictToJSON(
  sdTurbo2LoraDict: SDTurbo2LoraDict,
): string {
  return JSON.stringify(
    SDTurbo2LoraDict$outboundSchema.parse(sdTurbo2LoraDict),
  );
}

/** @internal */
export const SDTurbo2Acceleration$outboundSchema: z.ZodMiniEnum<
  typeof SDTurbo2Acceleration
> = z.enum(SDTurbo2Acceleration);

/** @internal */
export type SDTurbo2Seed1$Outbound = number | number;

/** @internal */
export const SDTurbo2Seed1$outboundSchema: z.ZodMiniType<
  SDTurbo2Seed1$Outbound,
  SDTurbo2Seed1
> = smartUnion([z.int(), z.number()]);

export function sdTurbo2Seed1ToJSON(sdTurbo2Seed1: SDTurbo2Seed1): string {
  return JSON.stringify(SDTurbo2Seed1$outboundSchema.parse(sdTurbo2Seed1));
}

/** @internal */
export type SDTurbo2Seed2$Outbound = number | Array<Array<number | number>>;

/** @internal */
export const SDTurbo2Seed2$outboundSchema: z.ZodMiniType<
  SDTurbo2Seed2$Outbound,
  SDTurbo2Seed2
> = smartUnion([z.int(), z.array(z.array(smartUnion([z.int(), z.number()])))]);

export function sdTurbo2Seed2ToJSON(sdTurbo2Seed2: SDTurbo2Seed2): string {
  return JSON.stringify(SDTurbo2Seed2$outboundSchema.parse(sdTurbo2Seed2));
}

/** @internal */
export const SDTurbo2SeedInterpolationMethod$outboundSchema: z.ZodMiniEnum<
  typeof SDTurbo2SeedInterpolationMethod
> = z.enum(SDTurbo2SeedInterpolationMethod);

/** @internal */
export const SDTurbo2ImagePreprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof SDTurbo2ImagePreprocessingType
> = z.enum(SDTurbo2ImagePreprocessingType);

/** @internal */
export type SDTurbo2ImagePreprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const SDTurbo2ImagePreprocessingProcessor$outboundSchema: z.ZodMiniType<
  SDTurbo2ImagePreprocessingProcessor$Outbound,
  SDTurbo2ImagePreprocessingProcessor
> = z.object({
  type: SDTurbo2ImagePreprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sdTurbo2ImagePreprocessingProcessorToJSON(
  sdTurbo2ImagePreprocessingProcessor: SDTurbo2ImagePreprocessingProcessor,
): string {
  return JSON.stringify(
    SDTurbo2ImagePreprocessingProcessor$outboundSchema.parse(
      sdTurbo2ImagePreprocessingProcessor,
    ),
  );
}

/** @internal */
export type SDTurbo2ImagePreprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<SDTurbo2ImagePreprocessingProcessor$Outbound>;
};

/** @internal */
export const SDTurbo2ImagePreprocessing$outboundSchema: z.ZodMiniType<
  SDTurbo2ImagePreprocessing$Outbound,
  SDTurbo2ImagePreprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => SDTurbo2ImagePreprocessingProcessor$outboundSchema),
  ),
});

export function sdTurbo2ImagePreprocessingToJSON(
  sdTurbo2ImagePreprocessing: SDTurbo2ImagePreprocessing,
): string {
  return JSON.stringify(
    SDTurbo2ImagePreprocessing$outboundSchema.parse(sdTurbo2ImagePreprocessing),
  );
}

/** @internal */
export const SDTurbo2ImagePostprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof SDTurbo2ImagePostprocessingType
> = z.enum(SDTurbo2ImagePostprocessingType);

/** @internal */
export type SDTurbo2ImagePostprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const SDTurbo2ImagePostprocessingProcessor$outboundSchema: z.ZodMiniType<
  SDTurbo2ImagePostprocessingProcessor$Outbound,
  SDTurbo2ImagePostprocessingProcessor
> = z.object({
  type: SDTurbo2ImagePostprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sdTurbo2ImagePostprocessingProcessorToJSON(
  sdTurbo2ImagePostprocessingProcessor: SDTurbo2ImagePostprocessingProcessor,
): string {
  return JSON.stringify(
    SDTurbo2ImagePostprocessingProcessor$outboundSchema.parse(
      sdTurbo2ImagePostprocessingProcessor,
    ),
  );
}

/** @internal */
export type SDTurbo2ImagePostprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<SDTurbo2ImagePostprocessingProcessor$Outbound>;
};

/** @internal */
export const SDTurbo2ImagePostprocessing$outboundSchema: z.ZodMiniType<
  SDTurbo2ImagePostprocessing$Outbound,
  SDTurbo2ImagePostprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => SDTurbo2ImagePostprocessingProcessor$outboundSchema),
  ),
});

export function sdTurbo2ImagePostprocessingToJSON(
  sdTurbo2ImagePostprocessing: SDTurbo2ImagePostprocessing,
): string {
  return JSON.stringify(
    SDTurbo2ImagePostprocessing$outboundSchema.parse(
      sdTurbo2ImagePostprocessing,
    ),
  );
}

/** @internal */
export const SDTurbo2LatentPreprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof SDTurbo2LatentPreprocessingType
> = z.enum(SDTurbo2LatentPreprocessingType);

/** @internal */
export type SDTurbo2LatentPreprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const SDTurbo2LatentPreprocessingProcessor$outboundSchema: z.ZodMiniType<
  SDTurbo2LatentPreprocessingProcessor$Outbound,
  SDTurbo2LatentPreprocessingProcessor
> = z.object({
  type: SDTurbo2LatentPreprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sdTurbo2LatentPreprocessingProcessorToJSON(
  sdTurbo2LatentPreprocessingProcessor: SDTurbo2LatentPreprocessingProcessor,
): string {
  return JSON.stringify(
    SDTurbo2LatentPreprocessingProcessor$outboundSchema.parse(
      sdTurbo2LatentPreprocessingProcessor,
    ),
  );
}

/** @internal */
export type SDTurbo2LatentPreprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<SDTurbo2LatentPreprocessingProcessor$Outbound>;
};

/** @internal */
export const SDTurbo2LatentPreprocessing$outboundSchema: z.ZodMiniType<
  SDTurbo2LatentPreprocessing$Outbound,
  SDTurbo2LatentPreprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => SDTurbo2LatentPreprocessingProcessor$outboundSchema),
  ),
});

export function sdTurbo2LatentPreprocessingToJSON(
  sdTurbo2LatentPreprocessing: SDTurbo2LatentPreprocessing,
): string {
  return JSON.stringify(
    SDTurbo2LatentPreprocessing$outboundSchema.parse(
      sdTurbo2LatentPreprocessing,
    ),
  );
}

/** @internal */
export const SDTurbo2LatentPostprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof SDTurbo2LatentPostprocessingType
> = z.enum(SDTurbo2LatentPostprocessingType);

/** @internal */
export type SDTurbo2LatentPostprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const SDTurbo2LatentPostprocessingProcessor$outboundSchema:
  z.ZodMiniType<
    SDTurbo2LatentPostprocessingProcessor$Outbound,
    SDTurbo2LatentPostprocessingProcessor
  > = z.object({
    type: SDTurbo2LatentPostprocessingType$outboundSchema,
    enabled: z.optional(z.boolean()),
    params: z.optional(z.record(z.string(), z.any())),
  });

export function sdTurbo2LatentPostprocessingProcessorToJSON(
  sdTurbo2LatentPostprocessingProcessor: SDTurbo2LatentPostprocessingProcessor,
): string {
  return JSON.stringify(
    SDTurbo2LatentPostprocessingProcessor$outboundSchema.parse(
      sdTurbo2LatentPostprocessingProcessor,
    ),
  );
}

/** @internal */
export type SDTurbo2LatentPostprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<SDTurbo2LatentPostprocessingProcessor$Outbound>;
};

/** @internal */
export const SDTurbo2LatentPostprocessing$outboundSchema: z.ZodMiniType<
  SDTurbo2LatentPostprocessing$Outbound,
  SDTurbo2LatentPostprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => SDTurbo2LatentPostprocessingProcessor$outboundSchema),
  ),
});

export function sdTurbo2LatentPostprocessingToJSON(
  sdTurbo2LatentPostprocessing: SDTurbo2LatentPostprocessing,
): string {
  return JSON.stringify(
    SDTurbo2LatentPostprocessing$outboundSchema.parse(
      sdTurbo2LatentPostprocessing,
    ),
  );
}

/** @internal */
export const SDTurbo2ControlnetModelId$outboundSchema: z.ZodMiniEnum<
  typeof SDTurbo2ControlnetModelId
> = z.enum(SDTurbo2ControlnetModelId);

/** @internal */
export const SDTurbo2Preprocessor$outboundSchema: z.ZodMiniEnum<
  typeof SDTurbo2Preprocessor
> = z.enum(SDTurbo2Preprocessor);

/** @internal */
export type SDTurbo2Controlnet$Outbound = {
  model_id: string;
  conditioning_scale: number;
  preprocessor: string;
  preprocessor_params?: { [k: string]: any } | undefined;
  enabled: boolean;
  control_guidance_start?: number | undefined;
  control_guidance_end?: number | undefined;
};

/** @internal */
export const SDTurbo2Controlnet$outboundSchema: z.ZodMiniType<
  SDTurbo2Controlnet$Outbound,
  SDTurbo2Controlnet
> = z.pipe(
  z.object({
    modelId: SDTurbo2ControlnetModelId$outboundSchema,
    conditioningScale: z.number(),
    preprocessor: SDTurbo2Preprocessor$outboundSchema,
    preprocessorParams: z.optional(z.record(z.string(), z.any())),
    enabled: z.boolean(),
    controlGuidanceStart: z.optional(z.number()),
    controlGuidanceEnd: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      modelId: "model_id",
      conditioningScale: "conditioning_scale",
      preprocessorParams: "preprocessor_params",
      controlGuidanceStart: "control_guidance_start",
      controlGuidanceEnd: "control_guidance_end",
    });
  }),
);

export function sdTurbo2ControlnetToJSON(
  sdTurbo2Controlnet: SDTurbo2Controlnet,
): string {
  return JSON.stringify(
    SDTurbo2Controlnet$outboundSchema.parse(sdTurbo2Controlnet),
  );
}

/** @internal */
export type SDTurbo2$Outbound = {
  model_id: "stabilityai/sd-turbo";
  prompt?: string | Array<Array<string | number>> | undefined;
  prompt_interpolation_method?: string | undefined;
  normalize_prompt_weights?: boolean | undefined;
  normalize_seed_weights?: boolean | undefined;
  negative_prompt?: string | undefined;
  guidance_scale?: number | undefined;
  delta?: number | undefined;
  num_inference_steps?: number | undefined;
  t_index_list?: Array<number> | undefined;
  use_safety_checker?: boolean | undefined;
  width?: number | undefined;
  height?: number | undefined;
  lora_dict?: SDTurbo2LoraDict$Outbound | null | undefined;
  use_lcm_lora?: boolean | undefined;
  lcm_lora_id?: string | undefined;
  acceleration?: string | undefined;
  use_denoising_batch?: boolean | undefined;
  do_add_noise?: boolean | undefined;
  seed?: number | Array<Array<number | number>> | undefined;
  seed_interpolation_method?: string | undefined;
  enable_similar_image_filter?: boolean | undefined;
  similar_image_filter_threshold?: number | undefined;
  similar_image_filter_max_skip_frame?: number | undefined;
  skip_diffusion?: boolean | undefined;
  image_preprocessing?: SDTurbo2ImagePreprocessing$Outbound | undefined;
  image_postprocessing?: SDTurbo2ImagePostprocessing$Outbound | undefined;
  latent_preprocessing?: SDTurbo2LatentPreprocessing$Outbound | undefined;
  latent_postprocessing?: SDTurbo2LatentPostprocessing$Outbound | undefined;
  controlnets?: Array<SDTurbo2Controlnet$Outbound> | undefined;
};

/** @internal */
export const SDTurbo2$outboundSchema: z.ZodMiniType<
  SDTurbo2$Outbound,
  SDTurbo2
> = z.pipe(
  z.object({
    modelId: z.literal("stabilityai/sd-turbo"),
    prompt: z.optional(
      smartUnion([
        z.string(),
        z.array(z.array(smartUnion([z.string(), z.number()]))),
      ]),
    ),
    promptInterpolationMethod: z.optional(
      SDTurbo2PromptInterpolationMethod$outboundSchema,
    ),
    normalizePromptWeights: z.optional(z.boolean()),
    normalizeSeedWeights: z.optional(z.boolean()),
    negativePrompt: z.optional(z.string()),
    guidanceScale: z.optional(z.number()),
    delta: z.optional(z.number()),
    numInferenceSteps: z.optional(z.int()),
    tIndexList: z.optional(z.array(z.int())),
    useSafetyChecker: z.optional(z.boolean()),
    width: z.optional(z.int()),
    height: z.optional(z.int()),
    loraDict: z.optional(
      z.nullable(z.lazy(() => SDTurbo2LoraDict$outboundSchema)),
    ),
    useLcmLora: z.optional(z.boolean()),
    lcmLoraId: z.optional(z.string()),
    acceleration: z.optional(SDTurbo2Acceleration$outboundSchema),
    useDenoisingBatch: z.optional(z.boolean()),
    doAddNoise: z.optional(z.boolean()),
    seed: z.optional(
      smartUnion([
        z.int(),
        z.array(z.array(smartUnion([z.int(), z.number()]))),
      ]),
    ),
    seedInterpolationMethod: z.optional(
      SDTurbo2SeedInterpolationMethod$outboundSchema,
    ),
    enableSimilarImageFilter: z.optional(z.boolean()),
    similarImageFilterThreshold: z.optional(z.number()),
    similarImageFilterMaxSkipFrame: z.optional(z.int()),
    skipDiffusion: z.optional(z.boolean()),
    imagePreprocessing: z.optional(
      z.lazy(() => SDTurbo2ImagePreprocessing$outboundSchema),
    ),
    imagePostprocessing: z.optional(
      z.lazy(() => SDTurbo2ImagePostprocessing$outboundSchema),
    ),
    latentPreprocessing: z.optional(
      z.lazy(() => SDTurbo2LatentPreprocessing$outboundSchema),
    ),
    latentPostprocessing: z.optional(
      z.lazy(() => SDTurbo2LatentPostprocessing$outboundSchema),
    ),
    controlnets: z.optional(
      z.array(z.lazy(() => SDTurbo2Controlnet$outboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      modelId: "model_id",
      promptInterpolationMethod: "prompt_interpolation_method",
      normalizePromptWeights: "normalize_prompt_weights",
      normalizeSeedWeights: "normalize_seed_weights",
      negativePrompt: "negative_prompt",
      guidanceScale: "guidance_scale",
      numInferenceSteps: "num_inference_steps",
      tIndexList: "t_index_list",
      useSafetyChecker: "use_safety_checker",
      loraDict: "lora_dict",
      useLcmLora: "use_lcm_lora",
      lcmLoraId: "lcm_lora_id",
      useDenoisingBatch: "use_denoising_batch",
      doAddNoise: "do_add_noise",
      seedInterpolationMethod: "seed_interpolation_method",
      enableSimilarImageFilter: "enable_similar_image_filter",
      similarImageFilterThreshold: "similar_image_filter_threshold",
      similarImageFilterMaxSkipFrame: "similar_image_filter_max_skip_frame",
      skipDiffusion: "skip_diffusion",
      imagePreprocessing: "image_preprocessing",
      imagePostprocessing: "image_postprocessing",
      latentPreprocessing: "latent_preprocessing",
      latentPostprocessing: "latent_postprocessing",
    });
  }),
);

export function sdTurbo2ToJSON(sdTurbo2: SDTurbo2): string {
  return JSON.stringify(SDTurbo2$outboundSchema.parse(sdTurbo2));
}
