/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smartUnion.js";

export type SDTurboPrompt1 = string | number;

/**
 * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
 */
export type SDTurboPrompt2 = string | Array<Array<string | number>>;

/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export const SDTurboPromptInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export type SDTurboPromptInterpolationMethod = ClosedEnum<
  typeof SDTurboPromptInterpolationMethod
>;

/**
 * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
 */
export type SDTurboLoraDict = {};

/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export const SDTurboAcceleration = {
  None: "none",
  Xformers: "xformers",
  Tensorrt: "tensorrt",
} as const;
/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export type SDTurboAcceleration = ClosedEnum<typeof SDTurboAcceleration>;

export type SDTurboSeed1 = number | number;

/**
 * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
 */
export type SDTurboSeed2 = number | Array<Array<number | number>>;

/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export const SDTurboSeedInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export type SDTurboSeedInterpolationMethod = ClosedEnum<
  typeof SDTurboSeedInterpolationMethod
>;

export const SDTurboImagePreprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type SDTurboImagePreprocessingType = ClosedEnum<
  typeof SDTurboImagePreprocessingType
>;

export type SDTurboImagePreprocessingProcessor = {
  type: SDTurboImagePreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image preprocessor configurations for image processing
 */
export type SDTurboImagePreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<SDTurboImagePreprocessingProcessor>;
};

export const SDTurboImagePostprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type SDTurboImagePostprocessingType = ClosedEnum<
  typeof SDTurboImagePostprocessingType
>;

export type SDTurboImagePostprocessingProcessor = {
  type: SDTurboImagePostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image postprocessor configurations for image processing
 *
 * @remarks
 *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
 */
export type SDTurboImagePostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<SDTurboImagePostprocessingProcessor>;
};

export const SDTurboLatentPreprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type SDTurboLatentPreprocessingType = ClosedEnum<
  typeof SDTurboLatentPreprocessingType
>;

export type SDTurboLatentPreprocessingProcessor = {
  type: SDTurboLatentPreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent preprocessor configurations for latent processing
 */
export type SDTurboLatentPreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<SDTurboLatentPreprocessingProcessor>;
};

export const SDTurboLatentPostprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type SDTurboLatentPostprocessingType = ClosedEnum<
  typeof SDTurboLatentPostprocessingType
>;

export type SDTurboLatentPostprocessingProcessor = {
  type: SDTurboLatentPostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent postprocessor configurations for latent processing
 */
export type SDTurboLatentPostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<SDTurboLatentPostprocessingProcessor>;
};

/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export const SDTurboControlnetModelId = {
  ThibaudControlnetSd21OpenposeDiffusers:
    "thibaud/controlnet-sd21-openpose-diffusers",
  ThibaudControlnetSd21HedDiffusers: "thibaud/controlnet-sd21-hed-diffusers",
  ThibaudControlnetSd21CannyDiffusers:
    "thibaud/controlnet-sd21-canny-diffusers",
  ThibaudControlnetSd21DepthDiffusers:
    "thibaud/controlnet-sd21-depth-diffusers",
  ThibaudControlnetSd21ColorDiffusers:
    "thibaud/controlnet-sd21-color-diffusers",
  DaydreamliveTemporalNet2StableDiffusion21:
    "daydreamlive/TemporalNet2-stable-diffusion-2-1",
} as const;
/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export type SDTurboControlnetModelId = ClosedEnum<
  typeof SDTurboControlnetModelId
>;

/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export const SDTurboPreprocessor = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export type SDTurboPreprocessor = ClosedEnum<typeof SDTurboPreprocessor>;

export type SDTurboControlnet = {
  /**
   * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
   */
  modelId: SDTurboControlnetModelId;
  /**
   * Strength of the ControlNet's influence on generation. Higher values make the model follow the control signal more strictly. Typical range 0.0-1.0, where 0.0 disables the control and 1.0 applies full control. Default: 1.0
   */
  conditioningScale: number;
  /**
   * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
   */
  preprocessor: SDTurboPreprocessor;
  /**
   * Additional parameters for the preprocessor. For example, canny edge detection uses 'low_threshold' and 'high_threshold' values.
   */
  preprocessorParams?: { [k: string]: any } | undefined;
  /**
   * Whether this ControlNet is active. Disabled ControlNets are not loaded. Default: true
   */
  enabled: boolean;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance begins. 0.0 means guidance starts from the beginning.
   */
  controlGuidanceStart?: number | undefined;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance ends. 1.0 means guidance continues until the end.
   */
  controlGuidanceEnd?: number | undefined;
};

export type SDTurbo = {
  modelId: "stabilityai/sd-turbo";
  /**
   * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
   */
  prompt?: string | Array<Array<string | number>> | undefined;
  /**
   * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
   */
  promptInterpolationMethod?: SDTurboPromptInterpolationMethod | undefined;
  /**
   * Whether to normalize prompt weights to sum to 1.0 for consistent generation.
   */
  normalizePromptWeights?: boolean | undefined;
  /**
   * Whether to normalize seed weights to sum to 1.0 for consistent generation.
   */
  normalizeSeedWeights?: boolean | undefined;
  /**
   * Text describing what to avoid in the generated image.
   */
  negativePrompt?: string | undefined;
  /**
   * Strength of prompt adherence. Higher values make the model follow the prompt more strictly.
   */
  guidanceScale?: number | undefined;
  /**
   * Delta sets per-frame denoising progress: lower delta means steadier, less flicker but slower/softer; higher delta means faster, sharper but more flicker/artifacts (often reduce CFG).
   */
  delta?: number | undefined;
  /**
   * Builds the full denoising schedule (the 'grid' of possible refinement steps). Changing it changes what each step number (t_index_list value) means. Keep it fixed for a session and only adjust if you're deliberately redefining the schedule; if you do, proportionally remap your t_index_list. Typical range 10-100 with default being 50.
   */
  numInferenceSteps?: number | undefined;
  /**
   * The ordered list of step indices from the num_inference_steps schedule to execute per frame. Each index is one model pass, so latency scales with the list length. Higher indices (e.g., 40–49 on a 50-step grid) mainly polish and preserve structure (lower flicker), while lower indices (<20) rewrite structure (more flicker, creative). Values must be non-decreasing, and each between 0 and num_inference_steps.
   *
   * @remarks
   *
   * ⚠️ NOTE: t_index_list must have 1–4 elements, non-decreasing, and within [0, num_inference_steps]. The value should not go above 50.
   */
  tIndexList?: Array<number> | undefined;
  /**
   * Whether to use safety checker for content filtering
   */
  useSafetyChecker?: boolean | undefined;
  /**
   * Output image width in pixels. Must be divisible by 64 and between 384-1024.
   */
  width?: number | undefined;
  /**
   * Output image height in pixels. Must be divisible by 64 and between 384-1024.
   */
  height?: number | undefined;
  /**
   * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
   */
  loraDict?: SDTurboLoraDict | null | undefined;
  /**
   * Whether to use Latent Consistency Model LoRA for faster inference.
   */
  useLcmLora?: boolean | undefined;
  /**
   * Identifier for the LCM LoRA model to use. Example: "latent-consistency/lcm-lora-sdv1-5"
   */
  lcmLoraId?: string | undefined;
  /**
   * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
   */
  acceleration?: SDTurboAcceleration | undefined;
  /**
   * Whether to process multiple denoising steps in a single batch for efficiency.
   */
  useDenoisingBatch?: boolean | undefined;
  /**
   * Whether to add noise to input frames before processing. Enabling this slightly re-noises each frame to improve temporal stability, reduce ghosting/texture sticking, and prevent drift; disabling can yield sharper, lower-latency results but may increase flicker and artifact accumulation over time.
   */
  doAddNoise?: boolean | undefined;
  /**
   * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
   */
  seed?: number | Array<Array<number | number>> | undefined;
  /**
   * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
   */
  seedInterpolationMethod?: SDTurboSeedInterpolationMethod | undefined;
  /**
   * Whether to skip frames that are too similar to the previous output to reduce flicker.
   */
  enableSimilarImageFilter?: boolean | undefined;
  /**
   * Similarity threshold for the image filter. Higher values allow more variation between frames.
   */
  similarImageFilterThreshold?: number | undefined;
  /**
   * Maximum number of consecutive frames that can be skipped by the similarity filter.
   */
  similarImageFilterMaxSkipFrame?: number | undefined;
  /**
   * Whether to skip the diffusion process. Any ControlNets or diffusion-only parameters are ignored when enabled.
   *
   * @remarks
   *         Example use cases:
   *         - Stream the output of a preprocessor (e.g. live depth maps or pose skeletons),
   *         - Run post-processors like RealESRGAN upscaler on externally provided frames,
   *         - Warm a pipeline without paying the diffusion cost.
   *       ⚠️ NOTE: skip_diffusion is evaluated at pipeline creation time; switching mid-stream triggers a pipeline reload.
   */
  skipDiffusion?: boolean | undefined;
  /**
   * List of image preprocessor configurations for image processing
   */
  imagePreprocessing?: SDTurboImagePreprocessing | undefined;
  /**
   * List of image postprocessor configurations for image processing
   *
   * @remarks
   *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
   */
  imagePostprocessing?: SDTurboImagePostprocessing | undefined;
  /**
   * List of latent preprocessor configurations for latent processing
   */
  latentPreprocessing?: SDTurboLatentPreprocessing | undefined;
  /**
   * List of latent postprocessor configurations for latent processing
   */
  latentPostprocessing?: SDTurboLatentPostprocessing | undefined;
  /**
   * List of ControlNet configurations for guided generation. Each ControlNet provides different types of conditioning (pose, edges, depth, etc.). Dynamic updates limited to conditioning_scale changes only; cannot add new ControlNets or change model_id/preprocessor/params without reload.
   */
  controlnets?: Array<SDTurboControlnet> | undefined;
};

/** @internal */
export type SDTurboPrompt1$Outbound = string | number;

/** @internal */
export const SDTurboPrompt1$outboundSchema: z.ZodMiniType<
  SDTurboPrompt1$Outbound,
  SDTurboPrompt1
> = smartUnion([z.string(), z.number()]);

export function sdTurboPrompt1ToJSON(sdTurboPrompt1: SDTurboPrompt1): string {
  return JSON.stringify(SDTurboPrompt1$outboundSchema.parse(sdTurboPrompt1));
}

/** @internal */
export type SDTurboPrompt2$Outbound = string | Array<Array<string | number>>;

/** @internal */
export const SDTurboPrompt2$outboundSchema: z.ZodMiniType<
  SDTurboPrompt2$Outbound,
  SDTurboPrompt2
> = smartUnion([
  z.string(),
  z.array(z.array(smartUnion([z.string(), z.number()]))),
]);

export function sdTurboPrompt2ToJSON(sdTurboPrompt2: SDTurboPrompt2): string {
  return JSON.stringify(SDTurboPrompt2$outboundSchema.parse(sdTurboPrompt2));
}

/** @internal */
export const SDTurboPromptInterpolationMethod$outboundSchema: z.ZodMiniEnum<
  typeof SDTurboPromptInterpolationMethod
> = z.enum(SDTurboPromptInterpolationMethod);

/** @internal */
export type SDTurboLoraDict$Outbound = {};

/** @internal */
export const SDTurboLoraDict$outboundSchema: z.ZodMiniType<
  SDTurboLoraDict$Outbound,
  SDTurboLoraDict
> = z.object({});

export function sdTurboLoraDictToJSON(
  sdTurboLoraDict: SDTurboLoraDict,
): string {
  return JSON.stringify(SDTurboLoraDict$outboundSchema.parse(sdTurboLoraDict));
}

/** @internal */
export const SDTurboAcceleration$outboundSchema: z.ZodMiniEnum<
  typeof SDTurboAcceleration
> = z.enum(SDTurboAcceleration);

/** @internal */
export type SDTurboSeed1$Outbound = number | number;

/** @internal */
export const SDTurboSeed1$outboundSchema: z.ZodMiniType<
  SDTurboSeed1$Outbound,
  SDTurboSeed1
> = smartUnion([z.int(), z.number()]);

export function sdTurboSeed1ToJSON(sdTurboSeed1: SDTurboSeed1): string {
  return JSON.stringify(SDTurboSeed1$outboundSchema.parse(sdTurboSeed1));
}

/** @internal */
export type SDTurboSeed2$Outbound = number | Array<Array<number | number>>;

/** @internal */
export const SDTurboSeed2$outboundSchema: z.ZodMiniType<
  SDTurboSeed2$Outbound,
  SDTurboSeed2
> = smartUnion([z.int(), z.array(z.array(smartUnion([z.int(), z.number()])))]);

export function sdTurboSeed2ToJSON(sdTurboSeed2: SDTurboSeed2): string {
  return JSON.stringify(SDTurboSeed2$outboundSchema.parse(sdTurboSeed2));
}

/** @internal */
export const SDTurboSeedInterpolationMethod$outboundSchema: z.ZodMiniEnum<
  typeof SDTurboSeedInterpolationMethod
> = z.enum(SDTurboSeedInterpolationMethod);

/** @internal */
export const SDTurboImagePreprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof SDTurboImagePreprocessingType
> = z.enum(SDTurboImagePreprocessingType);

/** @internal */
export type SDTurboImagePreprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const SDTurboImagePreprocessingProcessor$outboundSchema: z.ZodMiniType<
  SDTurboImagePreprocessingProcessor$Outbound,
  SDTurboImagePreprocessingProcessor
> = z.object({
  type: SDTurboImagePreprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sdTurboImagePreprocessingProcessorToJSON(
  sdTurboImagePreprocessingProcessor: SDTurboImagePreprocessingProcessor,
): string {
  return JSON.stringify(
    SDTurboImagePreprocessingProcessor$outboundSchema.parse(
      sdTurboImagePreprocessingProcessor,
    ),
  );
}

/** @internal */
export type SDTurboImagePreprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<SDTurboImagePreprocessingProcessor$Outbound>;
};

/** @internal */
export const SDTurboImagePreprocessing$outboundSchema: z.ZodMiniType<
  SDTurboImagePreprocessing$Outbound,
  SDTurboImagePreprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => SDTurboImagePreprocessingProcessor$outboundSchema),
  ),
});

export function sdTurboImagePreprocessingToJSON(
  sdTurboImagePreprocessing: SDTurboImagePreprocessing,
): string {
  return JSON.stringify(
    SDTurboImagePreprocessing$outboundSchema.parse(sdTurboImagePreprocessing),
  );
}

/** @internal */
export const SDTurboImagePostprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof SDTurboImagePostprocessingType
> = z.enum(SDTurboImagePostprocessingType);

/** @internal */
export type SDTurboImagePostprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const SDTurboImagePostprocessingProcessor$outboundSchema: z.ZodMiniType<
  SDTurboImagePostprocessingProcessor$Outbound,
  SDTurboImagePostprocessingProcessor
> = z.object({
  type: SDTurboImagePostprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sdTurboImagePostprocessingProcessorToJSON(
  sdTurboImagePostprocessingProcessor: SDTurboImagePostprocessingProcessor,
): string {
  return JSON.stringify(
    SDTurboImagePostprocessingProcessor$outboundSchema.parse(
      sdTurboImagePostprocessingProcessor,
    ),
  );
}

/** @internal */
export type SDTurboImagePostprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<SDTurboImagePostprocessingProcessor$Outbound>;
};

/** @internal */
export const SDTurboImagePostprocessing$outboundSchema: z.ZodMiniType<
  SDTurboImagePostprocessing$Outbound,
  SDTurboImagePostprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => SDTurboImagePostprocessingProcessor$outboundSchema),
  ),
});

export function sdTurboImagePostprocessingToJSON(
  sdTurboImagePostprocessing: SDTurboImagePostprocessing,
): string {
  return JSON.stringify(
    SDTurboImagePostprocessing$outboundSchema.parse(sdTurboImagePostprocessing),
  );
}

/** @internal */
export const SDTurboLatentPreprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof SDTurboLatentPreprocessingType
> = z.enum(SDTurboLatentPreprocessingType);

/** @internal */
export type SDTurboLatentPreprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const SDTurboLatentPreprocessingProcessor$outboundSchema: z.ZodMiniType<
  SDTurboLatentPreprocessingProcessor$Outbound,
  SDTurboLatentPreprocessingProcessor
> = z.object({
  type: SDTurboLatentPreprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sdTurboLatentPreprocessingProcessorToJSON(
  sdTurboLatentPreprocessingProcessor: SDTurboLatentPreprocessingProcessor,
): string {
  return JSON.stringify(
    SDTurboLatentPreprocessingProcessor$outboundSchema.parse(
      sdTurboLatentPreprocessingProcessor,
    ),
  );
}

/** @internal */
export type SDTurboLatentPreprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<SDTurboLatentPreprocessingProcessor$Outbound>;
};

/** @internal */
export const SDTurboLatentPreprocessing$outboundSchema: z.ZodMiniType<
  SDTurboLatentPreprocessing$Outbound,
  SDTurboLatentPreprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => SDTurboLatentPreprocessingProcessor$outboundSchema),
  ),
});

export function sdTurboLatentPreprocessingToJSON(
  sdTurboLatentPreprocessing: SDTurboLatentPreprocessing,
): string {
  return JSON.stringify(
    SDTurboLatentPreprocessing$outboundSchema.parse(sdTurboLatentPreprocessing),
  );
}

/** @internal */
export const SDTurboLatentPostprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof SDTurboLatentPostprocessingType
> = z.enum(SDTurboLatentPostprocessingType);

/** @internal */
export type SDTurboLatentPostprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const SDTurboLatentPostprocessingProcessor$outboundSchema: z.ZodMiniType<
  SDTurboLatentPostprocessingProcessor$Outbound,
  SDTurboLatentPostprocessingProcessor
> = z.object({
  type: SDTurboLatentPostprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sdTurboLatentPostprocessingProcessorToJSON(
  sdTurboLatentPostprocessingProcessor: SDTurboLatentPostprocessingProcessor,
): string {
  return JSON.stringify(
    SDTurboLatentPostprocessingProcessor$outboundSchema.parse(
      sdTurboLatentPostprocessingProcessor,
    ),
  );
}

/** @internal */
export type SDTurboLatentPostprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<SDTurboLatentPostprocessingProcessor$Outbound>;
};

/** @internal */
export const SDTurboLatentPostprocessing$outboundSchema: z.ZodMiniType<
  SDTurboLatentPostprocessing$Outbound,
  SDTurboLatentPostprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => SDTurboLatentPostprocessingProcessor$outboundSchema),
  ),
});

export function sdTurboLatentPostprocessingToJSON(
  sdTurboLatentPostprocessing: SDTurboLatentPostprocessing,
): string {
  return JSON.stringify(
    SDTurboLatentPostprocessing$outboundSchema.parse(
      sdTurboLatentPostprocessing,
    ),
  );
}

/** @internal */
export const SDTurboControlnetModelId$outboundSchema: z.ZodMiniEnum<
  typeof SDTurboControlnetModelId
> = z.enum(SDTurboControlnetModelId);

/** @internal */
export const SDTurboPreprocessor$outboundSchema: z.ZodMiniEnum<
  typeof SDTurboPreprocessor
> = z.enum(SDTurboPreprocessor);

/** @internal */
export type SDTurboControlnet$Outbound = {
  model_id: string;
  conditioning_scale: number;
  preprocessor: string;
  preprocessor_params?: { [k: string]: any } | undefined;
  enabled: boolean;
  control_guidance_start?: number | undefined;
  control_guidance_end?: number | undefined;
};

/** @internal */
export const SDTurboControlnet$outboundSchema: z.ZodMiniType<
  SDTurboControlnet$Outbound,
  SDTurboControlnet
> = z.pipe(
  z.object({
    modelId: SDTurboControlnetModelId$outboundSchema,
    conditioningScale: z.number(),
    preprocessor: SDTurboPreprocessor$outboundSchema,
    preprocessorParams: z.optional(z.record(z.string(), z.any())),
    enabled: z.boolean(),
    controlGuidanceStart: z.optional(z.number()),
    controlGuidanceEnd: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      modelId: "model_id",
      conditioningScale: "conditioning_scale",
      preprocessorParams: "preprocessor_params",
      controlGuidanceStart: "control_guidance_start",
      controlGuidanceEnd: "control_guidance_end",
    });
  }),
);

export function sdTurboControlnetToJSON(
  sdTurboControlnet: SDTurboControlnet,
): string {
  return JSON.stringify(
    SDTurboControlnet$outboundSchema.parse(sdTurboControlnet),
  );
}

/** @internal */
export type SDTurbo$Outbound = {
  model_id: "stabilityai/sd-turbo";
  prompt?: string | Array<Array<string | number>> | undefined;
  prompt_interpolation_method?: string | undefined;
  normalize_prompt_weights?: boolean | undefined;
  normalize_seed_weights?: boolean | undefined;
  negative_prompt?: string | undefined;
  guidance_scale?: number | undefined;
  delta?: number | undefined;
  num_inference_steps?: number | undefined;
  t_index_list?: Array<number> | undefined;
  use_safety_checker?: boolean | undefined;
  width?: number | undefined;
  height?: number | undefined;
  lora_dict?: SDTurboLoraDict$Outbound | null | undefined;
  use_lcm_lora?: boolean | undefined;
  lcm_lora_id?: string | undefined;
  acceleration?: string | undefined;
  use_denoising_batch?: boolean | undefined;
  do_add_noise?: boolean | undefined;
  seed?: number | Array<Array<number | number>> | undefined;
  seed_interpolation_method?: string | undefined;
  enable_similar_image_filter?: boolean | undefined;
  similar_image_filter_threshold?: number | undefined;
  similar_image_filter_max_skip_frame?: number | undefined;
  skip_diffusion?: boolean | undefined;
  image_preprocessing?: SDTurboImagePreprocessing$Outbound | undefined;
  image_postprocessing?: SDTurboImagePostprocessing$Outbound | undefined;
  latent_preprocessing?: SDTurboLatentPreprocessing$Outbound | undefined;
  latent_postprocessing?: SDTurboLatentPostprocessing$Outbound | undefined;
  controlnets?: Array<SDTurboControlnet$Outbound> | undefined;
};

/** @internal */
export const SDTurbo$outboundSchema: z.ZodMiniType<SDTurbo$Outbound, SDTurbo> =
  z.pipe(
    z.object({
      modelId: z.literal("stabilityai/sd-turbo"),
      prompt: z.optional(
        smartUnion([
          z.string(),
          z.array(z.array(smartUnion([z.string(), z.number()]))),
        ]),
      ),
      promptInterpolationMethod: z.optional(
        SDTurboPromptInterpolationMethod$outboundSchema,
      ),
      normalizePromptWeights: z.optional(z.boolean()),
      normalizeSeedWeights: z.optional(z.boolean()),
      negativePrompt: z.optional(z.string()),
      guidanceScale: z.optional(z.number()),
      delta: z.optional(z.number()),
      numInferenceSteps: z.optional(z.int()),
      tIndexList: z.optional(z.array(z.int())),
      useSafetyChecker: z.optional(z.boolean()),
      width: z.optional(z.int()),
      height: z.optional(z.int()),
      loraDict: z.optional(
        z.nullable(z.lazy(() => SDTurboLoraDict$outboundSchema)),
      ),
      useLcmLora: z.optional(z.boolean()),
      lcmLoraId: z.optional(z.string()),
      acceleration: z.optional(SDTurboAcceleration$outboundSchema),
      useDenoisingBatch: z.optional(z.boolean()),
      doAddNoise: z.optional(z.boolean()),
      seed: z.optional(
        smartUnion([
          z.int(),
          z.array(z.array(smartUnion([z.int(), z.number()]))),
        ]),
      ),
      seedInterpolationMethod: z.optional(
        SDTurboSeedInterpolationMethod$outboundSchema,
      ),
      enableSimilarImageFilter: z.optional(z.boolean()),
      similarImageFilterThreshold: z.optional(z.number()),
      similarImageFilterMaxSkipFrame: z.optional(z.int()),
      skipDiffusion: z.optional(z.boolean()),
      imagePreprocessing: z.optional(
        z.lazy(() => SDTurboImagePreprocessing$outboundSchema),
      ),
      imagePostprocessing: z.optional(
        z.lazy(() => SDTurboImagePostprocessing$outboundSchema),
      ),
      latentPreprocessing: z.optional(
        z.lazy(() => SDTurboLatentPreprocessing$outboundSchema),
      ),
      latentPostprocessing: z.optional(
        z.lazy(() => SDTurboLatentPostprocessing$outboundSchema),
      ),
      controlnets: z.optional(
        z.array(z.lazy(() => SDTurboControlnet$outboundSchema)),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        modelId: "model_id",
        promptInterpolationMethod: "prompt_interpolation_method",
        normalizePromptWeights: "normalize_prompt_weights",
        normalizeSeedWeights: "normalize_seed_weights",
        negativePrompt: "negative_prompt",
        guidanceScale: "guidance_scale",
        numInferenceSteps: "num_inference_steps",
        tIndexList: "t_index_list",
        useSafetyChecker: "use_safety_checker",
        loraDict: "lora_dict",
        useLcmLora: "use_lcm_lora",
        lcmLoraId: "lcm_lora_id",
        useDenoisingBatch: "use_denoising_batch",
        doAddNoise: "do_add_noise",
        seedInterpolationMethod: "seed_interpolation_method",
        enableSimilarImageFilter: "enable_similar_image_filter",
        similarImageFilterThreshold: "similar_image_filter_threshold",
        similarImageFilterMaxSkipFrame: "similar_image_filter_max_skip_frame",
        skipDiffusion: "skip_diffusion",
        imagePreprocessing: "image_preprocessing",
        imagePostprocessing: "image_postprocessing",
        latentPreprocessing: "latent_preprocessing",
        latentPostprocessing: "latent_postprocessing",
      });
    }),
  );

export function sdTurboToJSON(sdTurbo: SDTurbo): string {
  return JSON.stringify(SDTurbo$outboundSchema.parse(sdTurbo));
}
