/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SDTurbo1Prompt1 = string | number;

/**
 * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
 */
export type SDTurbo1Prompt2 = string | Array<Array<string | number>>;

/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export const SDTurbo1PromptInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export type SDTurbo1PromptInterpolationMethod = OpenEnum<
  typeof SDTurbo1PromptInterpolationMethod
>;

/**
 * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
 */
export type SDTurbo1LoraDict = {};

/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export const SDTurbo1Acceleration = {
  None: "none",
  Xformers: "xformers",
  Tensorrt: "tensorrt",
} as const;
/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export type SDTurbo1Acceleration = OpenEnum<typeof SDTurbo1Acceleration>;

export type SDTurbo1Seed1 = number | number;

/**
 * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
 */
export type SDTurbo1Seed2 = number | Array<Array<number | number>>;

/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export const SDTurbo1SeedInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export type SDTurbo1SeedInterpolationMethod = OpenEnum<
  typeof SDTurbo1SeedInterpolationMethod
>;

export const SDTurbo1ImagePreprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type SDTurbo1ImagePreprocessingType = OpenEnum<
  typeof SDTurbo1ImagePreprocessingType
>;

export type SDTurbo1ImagePreprocessingProcessor = {
  type: SDTurbo1ImagePreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image preprocessor configurations for image processing
 */
export type SDTurbo1ImagePreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<SDTurbo1ImagePreprocessingProcessor>;
};

export const SDTurbo1ImagePostprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type SDTurbo1ImagePostprocessingType = OpenEnum<
  typeof SDTurbo1ImagePostprocessingType
>;

export type SDTurbo1ImagePostprocessingProcessor = {
  type: SDTurbo1ImagePostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image postprocessor configurations for image processing
 *
 * @remarks
 *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
 */
export type SDTurbo1ImagePostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<SDTurbo1ImagePostprocessingProcessor>;
};

export const SDTurbo1LatentPreprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type SDTurbo1LatentPreprocessingType = ClosedEnum<
  typeof SDTurbo1LatentPreprocessingType
>;

export type SDTurbo1LatentPreprocessingProcessor = {
  type: SDTurbo1LatentPreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent preprocessor configurations for latent processing
 */
export type SDTurbo1LatentPreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<SDTurbo1LatentPreprocessingProcessor>;
};

export const SDTurbo1LatentPostprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type SDTurbo1LatentPostprocessingType = ClosedEnum<
  typeof SDTurbo1LatentPostprocessingType
>;

export type SDTurbo1LatentPostprocessingProcessor = {
  type: SDTurbo1LatentPostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent postprocessor configurations for latent processing
 */
export type SDTurbo1LatentPostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<SDTurbo1LatentPostprocessingProcessor>;
};

/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export const SDTurbo1ControlnetModelId = {
  ThibaudControlnetSd21OpenposeDiffusers:
    "thibaud/controlnet-sd21-openpose-diffusers",
  ThibaudControlnetSd21HedDiffusers: "thibaud/controlnet-sd21-hed-diffusers",
  ThibaudControlnetSd21CannyDiffusers:
    "thibaud/controlnet-sd21-canny-diffusers",
  ThibaudControlnetSd21DepthDiffusers:
    "thibaud/controlnet-sd21-depth-diffusers",
  ThibaudControlnetSd21ColorDiffusers:
    "thibaud/controlnet-sd21-color-diffusers",
  DaydreamliveTemporalNet2StableDiffusion21:
    "daydreamlive/TemporalNet2-stable-diffusion-2-1",
} as const;
/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export type SDTurbo1ControlnetModelId = OpenEnum<
  typeof SDTurbo1ControlnetModelId
>;

/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export const SDTurbo1Preprocessor = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export type SDTurbo1Preprocessor = OpenEnum<typeof SDTurbo1Preprocessor>;

export type SDTurbo1Controlnet = {
  /**
   * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
   */
  modelId: SDTurbo1ControlnetModelId;
  /**
   * Strength of the ControlNet's influence on generation. Higher values make the model follow the control signal more strictly. Typical range 0.0-1.0, where 0.0 disables the control and 1.0 applies full control. Default: 1.0
   */
  conditioningScale: number;
  /**
   * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
   */
  preprocessor: SDTurbo1Preprocessor;
  /**
   * Additional parameters for the preprocessor. For example, canny edge detection uses 'low_threshold' and 'high_threshold' values.
   */
  preprocessorParams?: { [k: string]: any } | undefined;
  /**
   * Whether this ControlNet is active. Disabled ControlNets are not loaded. Default: true
   */
  enabled: boolean;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance begins. 0.0 means guidance starts from the beginning.
   */
  controlGuidanceStart?: number | undefined;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance ends. 1.0 means guidance continues until the end.
   */
  controlGuidanceEnd?: number | undefined;
};

export type SDTurbo1 = {
  modelId: "stabilityai/sd-turbo";
  /**
   * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
   */
  prompt?: string | Array<Array<string | number>> | undefined;
  /**
   * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
   */
  promptInterpolationMethod?: SDTurbo1PromptInterpolationMethod | undefined;
  /**
   * Whether to normalize prompt weights to sum to 1.0 for consistent generation.
   */
  normalizePromptWeights?: boolean | undefined;
  /**
   * Whether to normalize seed weights to sum to 1.0 for consistent generation.
   */
  normalizeSeedWeights?: boolean | undefined;
  /**
   * Text describing what to avoid in the generated image.
   */
  negativePrompt?: string | undefined;
  /**
   * Strength of prompt adherence. Higher values make the model follow the prompt more strictly.
   */
  guidanceScale?: number | undefined;
  /**
   * Delta sets per-frame denoising progress: lower delta means steadier, less flicker but slower/softer; higher delta means faster, sharper but more flicker/artifacts (often reduce CFG).
   */
  delta?: number | undefined;
  /**
   * Builds the full denoising schedule (the 'grid' of possible refinement steps). Changing it changes what each step number (t_index_list value) means. Keep it fixed for a session and only adjust if you're deliberately redefining the schedule; if you do, proportionally remap your t_index_list. Typical range 10-100 with default being 50.
   */
  numInferenceSteps?: number | undefined;
  /**
   * The ordered list of step indices from the num_inference_steps schedule to execute per frame. Each index is one model pass, so latency scales with the list length. Higher indices (e.g., 40–49 on a 50-step grid) mainly polish and preserve structure (lower flicker), while lower indices (<20) rewrite structure (more flicker, creative). Values must be non-decreasing, and each between 0 and num_inference_steps.
   *
   * @remarks
   *
   * ⚠️ NOTE: t_index_list must have 1–4 elements, non-decreasing, and within [0, num_inference_steps]. The value should not go above 50.
   */
  tIndexList?: Array<number> | undefined;
  /**
   * Whether to use safety checker for content filtering
   */
  useSafetyChecker?: boolean | undefined;
  /**
   * Output image width in pixels. Must be divisible by 64 and between 384-1024.
   */
  width?: number | undefined;
  /**
   * Output image height in pixels. Must be divisible by 64 and between 384-1024.
   */
  height?: number | undefined;
  /**
   * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
   */
  loraDict?: SDTurbo1LoraDict | null | undefined;
  /**
   * Whether to use Latent Consistency Model LoRA for faster inference.
   */
  useLcmLora?: boolean | undefined;
  /**
   * Identifier for the LCM LoRA model to use. Example: "latent-consistency/lcm-lora-sdv1-5"
   */
  lcmLoraId?: string | undefined;
  /**
   * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
   */
  acceleration?: SDTurbo1Acceleration | undefined;
  /**
   * Whether to process multiple denoising steps in a single batch for efficiency.
   */
  useDenoisingBatch?: boolean | undefined;
  /**
   * Whether to add noise to input frames before processing. Enabling this slightly re-noises each frame to improve temporal stability, reduce ghosting/texture sticking, and prevent drift; disabling can yield sharper, lower-latency results but may increase flicker and artifact accumulation over time.
   */
  doAddNoise?: boolean | undefined;
  /**
   * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
   */
  seed?: number | Array<Array<number | number>> | undefined;
  /**
   * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
   */
  seedInterpolationMethod?: SDTurbo1SeedInterpolationMethod | undefined;
  /**
   * Whether to skip frames that are too similar to the previous output to reduce flicker.
   */
  enableSimilarImageFilter?: boolean | undefined;
  /**
   * Similarity threshold for the image filter. Higher values allow more variation between frames.
   */
  similarImageFilterThreshold?: number | undefined;
  /**
   * Maximum number of consecutive frames that can be skipped by the similarity filter.
   */
  similarImageFilterMaxSkipFrame?: number | undefined;
  /**
   * Whether to skip the diffusion process. Any ControlNets or diffusion-only parameters are ignored when enabled.
   *
   * @remarks
   *         Example use cases:
   *         - Stream the output of a preprocessor (e.g. live depth maps or pose skeletons),
   *         - Run post-processors like RealESRGAN upscaler on externally provided frames,
   *         - Warm a pipeline without paying the diffusion cost.
   *       ⚠️ NOTE: skip_diffusion is evaluated at pipeline creation time; switching mid-stream triggers a pipeline reload.
   */
  skipDiffusion?: boolean | undefined;
  /**
   * List of image preprocessor configurations for image processing
   */
  imagePreprocessing?: SDTurbo1ImagePreprocessing | undefined;
  /**
   * List of image postprocessor configurations for image processing
   *
   * @remarks
   *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
   */
  imagePostprocessing?: SDTurbo1ImagePostprocessing | undefined;
  /**
   * List of latent preprocessor configurations for latent processing
   */
  latentPreprocessing?: SDTurbo1LatentPreprocessing | undefined;
  /**
   * List of latent postprocessor configurations for latent processing
   */
  latentPostprocessing?: SDTurbo1LatentPostprocessing | undefined;
  /**
   * List of ControlNet configurations for guided generation. Each ControlNet provides different types of conditioning (pose, edges, depth, etc.). Dynamic updates limited to conditioning_scale changes only; cannot add new ControlNets or change model_id/preprocessor/params without reload.
   */
  controlnets?: Array<SDTurbo1Controlnet> | undefined;
};

/** @internal */
export const SDTurbo1Prompt1$inboundSchema: z.ZodMiniType<
  SDTurbo1Prompt1,
  unknown
> = smartUnion([types.string(), types.number()]);

export function sdTurbo1Prompt1FromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1Prompt1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo1Prompt1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1Prompt1' from JSON`,
  );
}

/** @internal */
export const SDTurbo1Prompt2$inboundSchema: z.ZodMiniType<
  SDTurbo1Prompt2,
  unknown
> = smartUnion([
  types.string(),
  z.array(z.array(smartUnion([types.string(), types.number()]))),
]);

export function sdTurbo1Prompt2FromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1Prompt2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo1Prompt2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1Prompt2' from JSON`,
  );
}

/** @internal */
export const SDTurbo1PromptInterpolationMethod$inboundSchema: z.ZodMiniType<
  SDTurbo1PromptInterpolationMethod,
  unknown
> = openEnums.inboundSchema(SDTurbo1PromptInterpolationMethod);

/** @internal */
export const SDTurbo1LoraDict$inboundSchema: z.ZodMiniType<
  SDTurbo1LoraDict,
  unknown
> = z.object({});

export function sdTurbo1LoraDictFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1LoraDict, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo1LoraDict$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1LoraDict' from JSON`,
  );
}

/** @internal */
export const SDTurbo1Acceleration$inboundSchema: z.ZodMiniType<
  SDTurbo1Acceleration,
  unknown
> = openEnums.inboundSchema(SDTurbo1Acceleration);

/** @internal */
export const SDTurbo1Seed1$inboundSchema: z.ZodMiniType<
  SDTurbo1Seed1,
  unknown
> = smartUnion([types.number(), types.number()]);

export function sdTurbo1Seed1FromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1Seed1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo1Seed1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1Seed1' from JSON`,
  );
}

/** @internal */
export const SDTurbo1Seed2$inboundSchema: z.ZodMiniType<
  SDTurbo1Seed2,
  unknown
> = smartUnion([
  types.number(),
  z.array(z.array(smartUnion([types.number(), types.number()]))),
]);

export function sdTurbo1Seed2FromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1Seed2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo1Seed2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1Seed2' from JSON`,
  );
}

/** @internal */
export const SDTurbo1SeedInterpolationMethod$inboundSchema: z.ZodMiniType<
  SDTurbo1SeedInterpolationMethod,
  unknown
> = openEnums.inboundSchema(SDTurbo1SeedInterpolationMethod);

/** @internal */
export const SDTurbo1ImagePreprocessingType$inboundSchema: z.ZodMiniType<
  SDTurbo1ImagePreprocessingType,
  unknown
> = openEnums.inboundSchema(SDTurbo1ImagePreprocessingType);

/** @internal */
export const SDTurbo1ImagePreprocessingProcessor$inboundSchema: z.ZodMiniType<
  SDTurbo1ImagePreprocessingProcessor,
  unknown
> = z.object({
  type: SDTurbo1ImagePreprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdTurbo1ImagePreprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1ImagePreprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SDTurbo1ImagePreprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1ImagePreprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const SDTurbo1ImagePreprocessing$inboundSchema: z.ZodMiniType<
  SDTurbo1ImagePreprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => SDTurbo1ImagePreprocessingProcessor$inboundSchema),
  ),
});

export function sdTurbo1ImagePreprocessingFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1ImagePreprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo1ImagePreprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1ImagePreprocessing' from JSON`,
  );
}

/** @internal */
export const SDTurbo1ImagePostprocessingType$inboundSchema: z.ZodMiniType<
  SDTurbo1ImagePostprocessingType,
  unknown
> = openEnums.inboundSchema(SDTurbo1ImagePostprocessingType);

/** @internal */
export const SDTurbo1ImagePostprocessingProcessor$inboundSchema: z.ZodMiniType<
  SDTurbo1ImagePostprocessingProcessor,
  unknown
> = z.object({
  type: SDTurbo1ImagePostprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdTurbo1ImagePostprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1ImagePostprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SDTurbo1ImagePostprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1ImagePostprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const SDTurbo1ImagePostprocessing$inboundSchema: z.ZodMiniType<
  SDTurbo1ImagePostprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => SDTurbo1ImagePostprocessingProcessor$inboundSchema),
  ),
});

export function sdTurbo1ImagePostprocessingFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1ImagePostprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo1ImagePostprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1ImagePostprocessing' from JSON`,
  );
}

/** @internal */
export const SDTurbo1LatentPreprocessingType$inboundSchema: z.ZodMiniEnum<
  typeof SDTurbo1LatentPreprocessingType
> = z.enum(SDTurbo1LatentPreprocessingType);

/** @internal */
export const SDTurbo1LatentPreprocessingProcessor$inboundSchema: z.ZodMiniType<
  SDTurbo1LatentPreprocessingProcessor,
  unknown
> = z.object({
  type: SDTurbo1LatentPreprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdTurbo1LatentPreprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1LatentPreprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SDTurbo1LatentPreprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1LatentPreprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const SDTurbo1LatentPreprocessing$inboundSchema: z.ZodMiniType<
  SDTurbo1LatentPreprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => SDTurbo1LatentPreprocessingProcessor$inboundSchema),
  ),
});

export function sdTurbo1LatentPreprocessingFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1LatentPreprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo1LatentPreprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1LatentPreprocessing' from JSON`,
  );
}

/** @internal */
export const SDTurbo1LatentPostprocessingType$inboundSchema: z.ZodMiniEnum<
  typeof SDTurbo1LatentPostprocessingType
> = z.enum(SDTurbo1LatentPostprocessingType);

/** @internal */
export const SDTurbo1LatentPostprocessingProcessor$inboundSchema: z.ZodMiniType<
  SDTurbo1LatentPostprocessingProcessor,
  unknown
> = z.object({
  type: SDTurbo1LatentPostprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdTurbo1LatentPostprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1LatentPostprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SDTurbo1LatentPostprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1LatentPostprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const SDTurbo1LatentPostprocessing$inboundSchema: z.ZodMiniType<
  SDTurbo1LatentPostprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => SDTurbo1LatentPostprocessingProcessor$inboundSchema),
  ),
});

export function sdTurbo1LatentPostprocessingFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1LatentPostprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo1LatentPostprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1LatentPostprocessing' from JSON`,
  );
}

/** @internal */
export const SDTurbo1ControlnetModelId$inboundSchema: z.ZodMiniType<
  SDTurbo1ControlnetModelId,
  unknown
> = openEnums.inboundSchema(SDTurbo1ControlnetModelId);

/** @internal */
export const SDTurbo1Preprocessor$inboundSchema: z.ZodMiniType<
  SDTurbo1Preprocessor,
  unknown
> = openEnums.inboundSchema(SDTurbo1Preprocessor);

/** @internal */
export const SDTurbo1Controlnet$inboundSchema: z.ZodMiniType<
  SDTurbo1Controlnet,
  unknown
> = z.pipe(
  z.object({
    model_id: SDTurbo1ControlnetModelId$inboundSchema,
    conditioning_scale: types.number(),
    preprocessor: SDTurbo1Preprocessor$inboundSchema,
    preprocessor_params: types.optional(z.record(z.string(), z.any())),
    enabled: types.boolean(),
    control_guidance_start: types.optional(types.number()),
    control_guidance_end: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_id": "modelId",
      "conditioning_scale": "conditioningScale",
      "preprocessor_params": "preprocessorParams",
      "control_guidance_start": "controlGuidanceStart",
      "control_guidance_end": "controlGuidanceEnd",
    });
  }),
);

export function sdTurbo1ControlnetFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1Controlnet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo1Controlnet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1Controlnet' from JSON`,
  );
}

/** @internal */
export const SDTurbo1$inboundSchema: z.ZodMiniType<SDTurbo1, unknown> = z.pipe(
  z.object({
    model_id: types.literal("stabilityai/sd-turbo"),
    prompt: types.optional(
      smartUnion([
        types.string(),
        z.array(z.array(smartUnion([types.string(), types.number()]))),
      ]),
    ),
    prompt_interpolation_method: types.optional(
      SDTurbo1PromptInterpolationMethod$inboundSchema,
    ),
    normalize_prompt_weights: types.optional(types.boolean()),
    normalize_seed_weights: types.optional(types.boolean()),
    negative_prompt: types.optional(types.string()),
    guidance_scale: types.optional(types.number()),
    delta: types.optional(types.number()),
    num_inference_steps: types.optional(types.number()),
    t_index_list: types.optional(z.array(types.number())),
    use_safety_checker: types.optional(types.boolean()),
    width: types.optional(types.number()),
    height: types.optional(types.number()),
    lora_dict: z.optional(z.nullable(z.lazy(() =>
      SDTurbo1LoraDict$inboundSchema
    ))),
    use_lcm_lora: types.optional(types.boolean()),
    lcm_lora_id: types.optional(types.string()),
    acceleration: types.optional(SDTurbo1Acceleration$inboundSchema),
    use_denoising_batch: types.optional(types.boolean()),
    do_add_noise: types.optional(types.boolean()),
    seed: types.optional(
      smartUnion([
        types.number(),
        z.array(z.array(smartUnion([types.number(), types.number()]))),
      ]),
    ),
    seed_interpolation_method: types.optional(
      SDTurbo1SeedInterpolationMethod$inboundSchema,
    ),
    enable_similar_image_filter: types.optional(types.boolean()),
    similar_image_filter_threshold: types.optional(types.number()),
    similar_image_filter_max_skip_frame: types.optional(types.number()),
    skip_diffusion: types.optional(types.boolean()),
    image_preprocessing: types.optional(z.lazy(() =>
      SDTurbo1ImagePreprocessing$inboundSchema
    )),
    image_postprocessing: types.optional(z.lazy(() =>
      SDTurbo1ImagePostprocessing$inboundSchema
    )),
    latent_preprocessing: types.optional(z.lazy(() =>
      SDTurbo1LatentPreprocessing$inboundSchema
    )),
    latent_postprocessing: types.optional(z.lazy(() =>
      SDTurbo1LatentPostprocessing$inboundSchema
    )),
    controlnets: types.optional(z.array(z.lazy(() =>
      SDTurbo1Controlnet$inboundSchema
    ))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_id": "modelId",
      "prompt_interpolation_method": "promptInterpolationMethod",
      "normalize_prompt_weights": "normalizePromptWeights",
      "normalize_seed_weights": "normalizeSeedWeights",
      "negative_prompt": "negativePrompt",
      "guidance_scale": "guidanceScale",
      "num_inference_steps": "numInferenceSteps",
      "t_index_list": "tIndexList",
      "use_safety_checker": "useSafetyChecker",
      "lora_dict": "loraDict",
      "use_lcm_lora": "useLcmLora",
      "lcm_lora_id": "lcmLoraId",
      "use_denoising_batch": "useDenoisingBatch",
      "do_add_noise": "doAddNoise",
      "seed_interpolation_method": "seedInterpolationMethod",
      "enable_similar_image_filter": "enableSimilarImageFilter",
      "similar_image_filter_threshold": "similarImageFilterThreshold",
      "similar_image_filter_max_skip_frame": "similarImageFilterMaxSkipFrame",
      "skip_diffusion": "skipDiffusion",
      "image_preprocessing": "imagePreprocessing",
      "image_postprocessing": "imagePostprocessing",
      "latent_preprocessing": "latentPreprocessing",
      "latent_postprocessing": "latentPostprocessing",
    });
  }),
);

export function sdTurbo1FromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo1' from JSON`,
  );
}
