/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SDTurbo3Prompt1 = string | number;

/**
 * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
 */
export type SDTurbo3Prompt2 = string | Array<Array<string | number>>;

/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export const SDTurbo3PromptInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export type SDTurbo3PromptInterpolationMethod = OpenEnum<
  typeof SDTurbo3PromptInterpolationMethod
>;

/**
 * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
 */
export type SDTurbo3LoraDict = {};

/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export const SDTurbo3Acceleration = {
  None: "none",
  Xformers: "xformers",
  Tensorrt: "tensorrt",
} as const;
/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export type SDTurbo3Acceleration = OpenEnum<typeof SDTurbo3Acceleration>;

export type SDTurbo3Seed1 = number | number;

/**
 * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
 */
export type SDTurbo3Seed2 = number | Array<Array<number | number>>;

/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export const SDTurbo3SeedInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export type SDTurbo3SeedInterpolationMethod = OpenEnum<
  typeof SDTurbo3SeedInterpolationMethod
>;

export const SDTurbo3ImagePreprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type SDTurbo3ImagePreprocessingType = OpenEnum<
  typeof SDTurbo3ImagePreprocessingType
>;

export type SDTurbo3ImagePreprocessingProcessor = {
  type: SDTurbo3ImagePreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image preprocessor configurations for image processing
 */
export type SDTurbo3ImagePreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<SDTurbo3ImagePreprocessingProcessor>;
};

export const SDTurbo3ImagePostprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type SDTurbo3ImagePostprocessingType = OpenEnum<
  typeof SDTurbo3ImagePostprocessingType
>;

export type SDTurbo3ImagePostprocessingProcessor = {
  type: SDTurbo3ImagePostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image postprocessor configurations for image processing
 *
 * @remarks
 *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
 */
export type SDTurbo3ImagePostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<SDTurbo3ImagePostprocessingProcessor>;
};

export const SDTurbo3LatentPreprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type SDTurbo3LatentPreprocessingType = ClosedEnum<
  typeof SDTurbo3LatentPreprocessingType
>;

export type SDTurbo3LatentPreprocessingProcessor = {
  type: SDTurbo3LatentPreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent preprocessor configurations for latent processing
 */
export type SDTurbo3LatentPreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<SDTurbo3LatentPreprocessingProcessor>;
};

export const SDTurbo3LatentPostprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type SDTurbo3LatentPostprocessingType = ClosedEnum<
  typeof SDTurbo3LatentPostprocessingType
>;

export type SDTurbo3LatentPostprocessingProcessor = {
  type: SDTurbo3LatentPostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent postprocessor configurations for latent processing
 */
export type SDTurbo3LatentPostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<SDTurbo3LatentPostprocessingProcessor>;
};

/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export const SDTurbo3ControlnetModelId = {
  ThibaudControlnetSd21OpenposeDiffusers:
    "thibaud/controlnet-sd21-openpose-diffusers",
  ThibaudControlnetSd21HedDiffusers: "thibaud/controlnet-sd21-hed-diffusers",
  ThibaudControlnetSd21CannyDiffusers:
    "thibaud/controlnet-sd21-canny-diffusers",
  ThibaudControlnetSd21DepthDiffusers:
    "thibaud/controlnet-sd21-depth-diffusers",
  ThibaudControlnetSd21ColorDiffusers:
    "thibaud/controlnet-sd21-color-diffusers",
  DaydreamliveTemporalNet2StableDiffusion21:
    "daydreamlive/TemporalNet2-stable-diffusion-2-1",
} as const;
/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export type SDTurbo3ControlnetModelId = OpenEnum<
  typeof SDTurbo3ControlnetModelId
>;

/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export const SDTurbo3Preprocessor = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export type SDTurbo3Preprocessor = OpenEnum<typeof SDTurbo3Preprocessor>;

export type SDTurbo3Controlnet = {
  /**
   * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
   */
  modelId: SDTurbo3ControlnetModelId;
  /**
   * Strength of the ControlNet's influence on generation. Higher values make the model follow the control signal more strictly. Typical range 0.0-1.0, where 0.0 disables the control and 1.0 applies full control. Default: 1.0
   */
  conditioningScale: number;
  /**
   * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
   */
  preprocessor: SDTurbo3Preprocessor;
  /**
   * Additional parameters for the preprocessor. For example, canny edge detection uses 'low_threshold' and 'high_threshold' values.
   */
  preprocessorParams?: { [k: string]: any } | undefined;
  /**
   * Whether this ControlNet is active. Disabled ControlNets are not loaded. Default: true
   */
  enabled: boolean;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance begins. 0.0 means guidance starts from the beginning.
   */
  controlGuidanceStart?: number | undefined;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance ends. 1.0 means guidance continues until the end.
   */
  controlGuidanceEnd?: number | undefined;
};

export type SDTurbo3 = {
  modelId: "stabilityai/sd-turbo";
  /**
   * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
   */
  prompt?: string | Array<Array<string | number>> | undefined;
  /**
   * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
   */
  promptInterpolationMethod?: SDTurbo3PromptInterpolationMethod | undefined;
  /**
   * Whether to normalize prompt weights to sum to 1.0 for consistent generation.
   */
  normalizePromptWeights?: boolean | undefined;
  /**
   * Whether to normalize seed weights to sum to 1.0 for consistent generation.
   */
  normalizeSeedWeights?: boolean | undefined;
  /**
   * Text describing what to avoid in the generated image.
   */
  negativePrompt?: string | undefined;
  /**
   * Strength of prompt adherence. Higher values make the model follow the prompt more strictly.
   */
  guidanceScale?: number | undefined;
  /**
   * Delta sets per-frame denoising progress: lower delta means steadier, less flicker but slower/softer; higher delta means faster, sharper but more flicker/artifacts (often reduce CFG).
   */
  delta?: number | undefined;
  /**
   * Builds the full denoising schedule (the 'grid' of possible refinement steps). Changing it changes what each step number (t_index_list value) means. Keep it fixed for a session and only adjust if you're deliberately redefining the schedule; if you do, proportionally remap your t_index_list. Typical range 10-100 with default being 50.
   */
  numInferenceSteps?: number | undefined;
  /**
   * The ordered list of step indices from the num_inference_steps schedule to execute per frame. Each index is one model pass, so latency scales with the list length. Higher indices (e.g., 40–49 on a 50-step grid) mainly polish and preserve structure (lower flicker), while lower indices (<20) rewrite structure (more flicker, creative). Values must be non-decreasing, and each between 0 and num_inference_steps.
   *
   * @remarks
   *
   * ⚠️ NOTE: t_index_list must have 1–4 elements, non-decreasing, and within [0, num_inference_steps]. The value should not go above 50.
   */
  tIndexList?: Array<number> | undefined;
  /**
   * Whether to use safety checker for content filtering
   */
  useSafetyChecker?: boolean | undefined;
  /**
   * Output image width in pixels. Must be divisible by 64 and between 384-1024.
   */
  width?: number | undefined;
  /**
   * Output image height in pixels. Must be divisible by 64 and between 384-1024.
   */
  height?: number | undefined;
  /**
   * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
   */
  loraDict?: SDTurbo3LoraDict | null | undefined;
  /**
   * Whether to use Latent Consistency Model LoRA for faster inference.
   */
  useLcmLora?: boolean | undefined;
  /**
   * Identifier for the LCM LoRA model to use. Example: "latent-consistency/lcm-lora-sdv1-5"
   */
  lcmLoraId?: string | undefined;
  /**
   * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
   */
  acceleration?: SDTurbo3Acceleration | undefined;
  /**
   * Whether to process multiple denoising steps in a single batch for efficiency.
   */
  useDenoisingBatch?: boolean | undefined;
  /**
   * Whether to add noise to input frames before processing. Enabling this slightly re-noises each frame to improve temporal stability, reduce ghosting/texture sticking, and prevent drift; disabling can yield sharper, lower-latency results but may increase flicker and artifact accumulation over time.
   */
  doAddNoise?: boolean | undefined;
  /**
   * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
   */
  seed?: number | Array<Array<number | number>> | undefined;
  /**
   * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
   */
  seedInterpolationMethod?: SDTurbo3SeedInterpolationMethod | undefined;
  /**
   * Whether to skip frames that are too similar to the previous output to reduce flicker.
   */
  enableSimilarImageFilter?: boolean | undefined;
  /**
   * Similarity threshold for the image filter. Higher values allow more variation between frames.
   */
  similarImageFilterThreshold?: number | undefined;
  /**
   * Maximum number of consecutive frames that can be skipped by the similarity filter.
   */
  similarImageFilterMaxSkipFrame?: number | undefined;
  /**
   * Whether to skip the diffusion process. Any ControlNets or diffusion-only parameters are ignored when enabled.
   *
   * @remarks
   *         Example use cases:
   *         - Stream the output of a preprocessor (e.g. live depth maps or pose skeletons),
   *         - Run post-processors like RealESRGAN upscaler on externally provided frames,
   *         - Warm a pipeline without paying the diffusion cost.
   *       ⚠️ NOTE: skip_diffusion is evaluated at pipeline creation time; switching mid-stream triggers a pipeline reload.
   */
  skipDiffusion?: boolean | undefined;
  /**
   * List of image preprocessor configurations for image processing
   */
  imagePreprocessing?: SDTurbo3ImagePreprocessing | undefined;
  /**
   * List of image postprocessor configurations for image processing
   *
   * @remarks
   *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
   */
  imagePostprocessing?: SDTurbo3ImagePostprocessing | undefined;
  /**
   * List of latent preprocessor configurations for latent processing
   */
  latentPreprocessing?: SDTurbo3LatentPreprocessing | undefined;
  /**
   * List of latent postprocessor configurations for latent processing
   */
  latentPostprocessing?: SDTurbo3LatentPostprocessing | undefined;
  /**
   * List of ControlNet configurations for guided generation. Each ControlNet provides different types of conditioning (pose, edges, depth, etc.). Dynamic updates limited to conditioning_scale changes only; cannot add new ControlNets or change model_id/preprocessor/params without reload.
   */
  controlnets?: Array<SDTurbo3Controlnet> | undefined;
};

/** @internal */
export const SDTurbo3Prompt1$inboundSchema: z.ZodMiniType<
  SDTurbo3Prompt1,
  unknown
> = smartUnion([types.string(), types.number()]);

export function sdTurbo3Prompt1FromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3Prompt1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo3Prompt1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3Prompt1' from JSON`,
  );
}

/** @internal */
export const SDTurbo3Prompt2$inboundSchema: z.ZodMiniType<
  SDTurbo3Prompt2,
  unknown
> = smartUnion([
  types.string(),
  z.array(z.array(smartUnion([types.string(), types.number()]))),
]);

export function sdTurbo3Prompt2FromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3Prompt2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo3Prompt2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3Prompt2' from JSON`,
  );
}

/** @internal */
export const SDTurbo3PromptInterpolationMethod$inboundSchema: z.ZodMiniType<
  SDTurbo3PromptInterpolationMethod,
  unknown
> = openEnums.inboundSchema(SDTurbo3PromptInterpolationMethod);

/** @internal */
export const SDTurbo3LoraDict$inboundSchema: z.ZodMiniType<
  SDTurbo3LoraDict,
  unknown
> = z.object({});

export function sdTurbo3LoraDictFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3LoraDict, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo3LoraDict$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3LoraDict' from JSON`,
  );
}

/** @internal */
export const SDTurbo3Acceleration$inboundSchema: z.ZodMiniType<
  SDTurbo3Acceleration,
  unknown
> = openEnums.inboundSchema(SDTurbo3Acceleration);

/** @internal */
export const SDTurbo3Seed1$inboundSchema: z.ZodMiniType<
  SDTurbo3Seed1,
  unknown
> = smartUnion([types.number(), types.number()]);

export function sdTurbo3Seed1FromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3Seed1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo3Seed1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3Seed1' from JSON`,
  );
}

/** @internal */
export const SDTurbo3Seed2$inboundSchema: z.ZodMiniType<
  SDTurbo3Seed2,
  unknown
> = smartUnion([
  types.number(),
  z.array(z.array(smartUnion([types.number(), types.number()]))),
]);

export function sdTurbo3Seed2FromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3Seed2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo3Seed2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3Seed2' from JSON`,
  );
}

/** @internal */
export const SDTurbo3SeedInterpolationMethod$inboundSchema: z.ZodMiniType<
  SDTurbo3SeedInterpolationMethod,
  unknown
> = openEnums.inboundSchema(SDTurbo3SeedInterpolationMethod);

/** @internal */
export const SDTurbo3ImagePreprocessingType$inboundSchema: z.ZodMiniType<
  SDTurbo3ImagePreprocessingType,
  unknown
> = openEnums.inboundSchema(SDTurbo3ImagePreprocessingType);

/** @internal */
export const SDTurbo3ImagePreprocessingProcessor$inboundSchema: z.ZodMiniType<
  SDTurbo3ImagePreprocessingProcessor,
  unknown
> = z.object({
  type: SDTurbo3ImagePreprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdTurbo3ImagePreprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3ImagePreprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SDTurbo3ImagePreprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3ImagePreprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const SDTurbo3ImagePreprocessing$inboundSchema: z.ZodMiniType<
  SDTurbo3ImagePreprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => SDTurbo3ImagePreprocessingProcessor$inboundSchema),
  ),
});

export function sdTurbo3ImagePreprocessingFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3ImagePreprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo3ImagePreprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3ImagePreprocessing' from JSON`,
  );
}

/** @internal */
export const SDTurbo3ImagePostprocessingType$inboundSchema: z.ZodMiniType<
  SDTurbo3ImagePostprocessingType,
  unknown
> = openEnums.inboundSchema(SDTurbo3ImagePostprocessingType);

/** @internal */
export const SDTurbo3ImagePostprocessingProcessor$inboundSchema: z.ZodMiniType<
  SDTurbo3ImagePostprocessingProcessor,
  unknown
> = z.object({
  type: SDTurbo3ImagePostprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdTurbo3ImagePostprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3ImagePostprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SDTurbo3ImagePostprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3ImagePostprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const SDTurbo3ImagePostprocessing$inboundSchema: z.ZodMiniType<
  SDTurbo3ImagePostprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => SDTurbo3ImagePostprocessingProcessor$inboundSchema),
  ),
});

export function sdTurbo3ImagePostprocessingFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3ImagePostprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo3ImagePostprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3ImagePostprocessing' from JSON`,
  );
}

/** @internal */
export const SDTurbo3LatentPreprocessingType$inboundSchema: z.ZodMiniEnum<
  typeof SDTurbo3LatentPreprocessingType
> = z.enum(SDTurbo3LatentPreprocessingType);

/** @internal */
export const SDTurbo3LatentPreprocessingProcessor$inboundSchema: z.ZodMiniType<
  SDTurbo3LatentPreprocessingProcessor,
  unknown
> = z.object({
  type: SDTurbo3LatentPreprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdTurbo3LatentPreprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3LatentPreprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SDTurbo3LatentPreprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3LatentPreprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const SDTurbo3LatentPreprocessing$inboundSchema: z.ZodMiniType<
  SDTurbo3LatentPreprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => SDTurbo3LatentPreprocessingProcessor$inboundSchema),
  ),
});

export function sdTurbo3LatentPreprocessingFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3LatentPreprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo3LatentPreprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3LatentPreprocessing' from JSON`,
  );
}

/** @internal */
export const SDTurbo3LatentPostprocessingType$inboundSchema: z.ZodMiniEnum<
  typeof SDTurbo3LatentPostprocessingType
> = z.enum(SDTurbo3LatentPostprocessingType);

/** @internal */
export const SDTurbo3LatentPostprocessingProcessor$inboundSchema: z.ZodMiniType<
  SDTurbo3LatentPostprocessingProcessor,
  unknown
> = z.object({
  type: SDTurbo3LatentPostprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdTurbo3LatentPostprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3LatentPostprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SDTurbo3LatentPostprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3LatentPostprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const SDTurbo3LatentPostprocessing$inboundSchema: z.ZodMiniType<
  SDTurbo3LatentPostprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => SDTurbo3LatentPostprocessingProcessor$inboundSchema),
  ),
});

export function sdTurbo3LatentPostprocessingFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3LatentPostprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo3LatentPostprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3LatentPostprocessing' from JSON`,
  );
}

/** @internal */
export const SDTurbo3ControlnetModelId$inboundSchema: z.ZodMiniType<
  SDTurbo3ControlnetModelId,
  unknown
> = openEnums.inboundSchema(SDTurbo3ControlnetModelId);

/** @internal */
export const SDTurbo3Preprocessor$inboundSchema: z.ZodMiniType<
  SDTurbo3Preprocessor,
  unknown
> = openEnums.inboundSchema(SDTurbo3Preprocessor);

/** @internal */
export const SDTurbo3Controlnet$inboundSchema: z.ZodMiniType<
  SDTurbo3Controlnet,
  unknown
> = z.pipe(
  z.object({
    model_id: SDTurbo3ControlnetModelId$inboundSchema,
    conditioning_scale: types.number(),
    preprocessor: SDTurbo3Preprocessor$inboundSchema,
    preprocessor_params: types.optional(z.record(z.string(), z.any())),
    enabled: types.boolean(),
    control_guidance_start: types.optional(types.number()),
    control_guidance_end: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_id": "modelId",
      "conditioning_scale": "conditioningScale",
      "preprocessor_params": "preprocessorParams",
      "control_guidance_start": "controlGuidanceStart",
      "control_guidance_end": "controlGuidanceEnd",
    });
  }),
);

export function sdTurbo3ControlnetFromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3Controlnet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo3Controlnet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3Controlnet' from JSON`,
  );
}

/** @internal */
export const SDTurbo3$inboundSchema: z.ZodMiniType<SDTurbo3, unknown> = z.pipe(
  z.object({
    model_id: types.literal("stabilityai/sd-turbo"),
    prompt: types.optional(
      smartUnion([
        types.string(),
        z.array(z.array(smartUnion([types.string(), types.number()]))),
      ]),
    ),
    prompt_interpolation_method: types.optional(
      SDTurbo3PromptInterpolationMethod$inboundSchema,
    ),
    normalize_prompt_weights: types.optional(types.boolean()),
    normalize_seed_weights: types.optional(types.boolean()),
    negative_prompt: types.optional(types.string()),
    guidance_scale: types.optional(types.number()),
    delta: types.optional(types.number()),
    num_inference_steps: types.optional(types.number()),
    t_index_list: types.optional(z.array(types.number())),
    use_safety_checker: types.optional(types.boolean()),
    width: types.optional(types.number()),
    height: types.optional(types.number()),
    lora_dict: z.optional(z.nullable(z.lazy(() =>
      SDTurbo3LoraDict$inboundSchema
    ))),
    use_lcm_lora: types.optional(types.boolean()),
    lcm_lora_id: types.optional(types.string()),
    acceleration: types.optional(SDTurbo3Acceleration$inboundSchema),
    use_denoising_batch: types.optional(types.boolean()),
    do_add_noise: types.optional(types.boolean()),
    seed: types.optional(
      smartUnion([
        types.number(),
        z.array(z.array(smartUnion([types.number(), types.number()]))),
      ]),
    ),
    seed_interpolation_method: types.optional(
      SDTurbo3SeedInterpolationMethod$inboundSchema,
    ),
    enable_similar_image_filter: types.optional(types.boolean()),
    similar_image_filter_threshold: types.optional(types.number()),
    similar_image_filter_max_skip_frame: types.optional(types.number()),
    skip_diffusion: types.optional(types.boolean()),
    image_preprocessing: types.optional(z.lazy(() =>
      SDTurbo3ImagePreprocessing$inboundSchema
    )),
    image_postprocessing: types.optional(z.lazy(() =>
      SDTurbo3ImagePostprocessing$inboundSchema
    )),
    latent_preprocessing: types.optional(z.lazy(() =>
      SDTurbo3LatentPreprocessing$inboundSchema
    )),
    latent_postprocessing: types.optional(z.lazy(() =>
      SDTurbo3LatentPostprocessing$inboundSchema
    )),
    controlnets: types.optional(z.array(z.lazy(() =>
      SDTurbo3Controlnet$inboundSchema
    ))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_id": "modelId",
      "prompt_interpolation_method": "promptInterpolationMethod",
      "normalize_prompt_weights": "normalizePromptWeights",
      "normalize_seed_weights": "normalizeSeedWeights",
      "negative_prompt": "negativePrompt",
      "guidance_scale": "guidanceScale",
      "num_inference_steps": "numInferenceSteps",
      "t_index_list": "tIndexList",
      "use_safety_checker": "useSafetyChecker",
      "lora_dict": "loraDict",
      "use_lcm_lora": "useLcmLora",
      "lcm_lora_id": "lcmLoraId",
      "use_denoising_batch": "useDenoisingBatch",
      "do_add_noise": "doAddNoise",
      "seed_interpolation_method": "seedInterpolationMethod",
      "enable_similar_image_filter": "enableSimilarImageFilter",
      "similar_image_filter_threshold": "similarImageFilterThreshold",
      "similar_image_filter_max_skip_frame": "similarImageFilterMaxSkipFrame",
      "skip_diffusion": "skipDiffusion",
      "image_preprocessing": "imagePreprocessing",
      "image_postprocessing": "imagePostprocessing",
      "latent_preprocessing": "latentPreprocessing",
      "latent_postprocessing": "latentPostprocessing",
    });
  }),
);

export function sdTurbo3FromJSON(
  jsonString: string,
): SafeParseResult<SDTurbo3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDTurbo3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDTurbo3' from JSON`,
  );
}
