/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Sdxl3Prompt1 = string | number;

/**
 * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
 */
export type Sdxl3Prompt2 = string | Array<Array<string | number>>;

/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export const Sdxl3PromptInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export type Sdxl3PromptInterpolationMethod = OpenEnum<
  typeof Sdxl3PromptInterpolationMethod
>;

/**
 * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
 */
export type Sdxl3LoraDict = {};

/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export const Sdxl3Acceleration = {
  None: "none",
  Xformers: "xformers",
  Tensorrt: "tensorrt",
} as const;
/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export type Sdxl3Acceleration = OpenEnum<typeof Sdxl3Acceleration>;

export type Sdxl3Seed1 = number | number;

/**
 * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
 */
export type Sdxl3Seed2 = number | Array<Array<number | number>>;

/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export const Sdxl3SeedInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export type Sdxl3SeedInterpolationMethod = OpenEnum<
  typeof Sdxl3SeedInterpolationMethod
>;

export const Sdxl3ImagePreprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type Sdxl3ImagePreprocessingType = OpenEnum<
  typeof Sdxl3ImagePreprocessingType
>;

export type Sdxl3ImagePreprocessingProcessor = {
  type: Sdxl3ImagePreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image preprocessor configurations for image processing
 */
export type Sdxl3ImagePreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<Sdxl3ImagePreprocessingProcessor>;
};

export const Sdxl3ImagePostprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type Sdxl3ImagePostprocessingType = OpenEnum<
  typeof Sdxl3ImagePostprocessingType
>;

export type Sdxl3ImagePostprocessingProcessor = {
  type: Sdxl3ImagePostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image postprocessor configurations for image processing
 *
 * @remarks
 *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
 */
export type Sdxl3ImagePostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<Sdxl3ImagePostprocessingProcessor>;
};

export const Sdxl3LatentPreprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type Sdxl3LatentPreprocessingType = ClosedEnum<
  typeof Sdxl3LatentPreprocessingType
>;

export type Sdxl3LatentPreprocessingProcessor = {
  type: Sdxl3LatentPreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent preprocessor configurations for latent processing
 */
export type Sdxl3LatentPreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<Sdxl3LatentPreprocessingProcessor>;
};

export const Sdxl3LatentPostprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type Sdxl3LatentPostprocessingType = ClosedEnum<
  typeof Sdxl3LatentPostprocessingType
>;

export type Sdxl3LatentPostprocessingProcessor = {
  type: Sdxl3LatentPostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent postprocessor configurations for latent processing
 */
export type Sdxl3LatentPostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<Sdxl3LatentPostprocessingProcessor>;
};

/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export const Sdxl3ControlnetModelId = {
  XinsirControlnetDepthSdxl10: "xinsir/controlnet-depth-sdxl-1.0",
  XinsirControlnetCannySdxl10: "xinsir/controlnet-canny-sdxl-1.0",
  XinsirControlnetTileSdxl10: "xinsir/controlnet-tile-sdxl-1.0",
} as const;
/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export type Sdxl3ControlnetModelId = OpenEnum<typeof Sdxl3ControlnetModelId>;

/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export const Sdxl3Preprocessor = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export type Sdxl3Preprocessor = OpenEnum<typeof Sdxl3Preprocessor>;

export type Sdxl3Controlnet = {
  /**
   * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
   */
  modelId: Sdxl3ControlnetModelId;
  /**
   * Strength of the ControlNet's influence on generation. Higher values make the model follow the control signal more strictly. Typical range 0.0-1.0, where 0.0 disables the control and 1.0 applies full control. Default: 1.0
   */
  conditioningScale: number;
  /**
   * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
   */
  preprocessor: Sdxl3Preprocessor;
  /**
   * Preprocessor parameters
   */
  preprocessorParams?: { [k: string]: any } | undefined;
  /**
   * Whether this ControlNet is active. Disabled ControlNets are not loaded. Default: true
   */
  enabled: boolean;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance begins. 0.0 means guidance starts from the beginning.
   */
  controlGuidanceStart?: number | undefined;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance ends. 1.0 means guidance continues until the end.
   */
  controlGuidanceEnd?: number | undefined;
};

/**
 * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
 */
export const Sdxl3IpAdapterType = {
  Regular: "regular",
  Faceid: "faceid",
} as const;
/**
 * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
 */
export type Sdxl3IpAdapterType = OpenEnum<typeof Sdxl3IpAdapterType>;

/**
 * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
 */
export const Sdxl3WeightType = {
  Linear: "linear",
  EaseIn: "ease in",
  EaseOut: "ease out",
  EaseInOut: "ease in-out",
  ReverseInOut: "reverse in-out",
  WeakInput: "weak input",
  WeakOutput: "weak output",
  WeakMiddle: "weak middle",
  StrongMiddle: "strong middle",
  StyleTransfer: "style transfer",
  Composition: "composition",
  StrongStyleTransfer: "strong style transfer",
  StyleAndComposition: "style and composition",
  StyleTransferPrecise: "style transfer precise",
  CompositionPrecise: "composition precise",
} as const;
/**
 * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
 */
export type Sdxl3WeightType = OpenEnum<typeof Sdxl3WeightType>;

/**
 * IP adapter — Turns on IP-Adapter style conditioning and is fully hot-swappable. Available for SDXL, SDXL-faceid, SD1.5
 */
export type Sdxl3IpAdapter = {
  /**
   * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
   */
  type: Sdxl3IpAdapterType;
  /**
   * Whether IP adapter is enabled
   */
  enabled?: boolean | undefined;
  /**
   * Strength of IP adapter style conditioning
   */
  scale?: number | undefined;
  /**
   * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
   */
  weightType?: Sdxl3WeightType | undefined;
};

/**
 * Cached attention (StreamV2V) configuration. Enable cached attention to reuse key/value tensors across frames. ⚠️ NOTE: Enabling or disabling cached_attention requires a pipeline reload as it uses a different pipeline.
 */
export type Sdxl3CachedAttention = {
  /**
   * Whether this cached attention is active. Enable cached attention to reuse key/value tensors across frames.
   */
  enabled: boolean;
  /**
   * Number of frames retained in the attention cache. Number of historical K/V frames to retain. Limited by TensorRT engine exports.
   */
  maxFrames: number;
  /**
   * Cadence (number of frames) for refreshing cached key/value tensors i.e How often (in number of frames) to refresh the cache.
   *
   * @remarks
   *       It is now **frame-based** (not seconds). It accepts integers 1-240, representing how many frames elapse between cache refreshes.
   */
  interval: number;
};

export type Sdxl3 = {
  modelId: "stabilityai/sdxl-turbo";
  /**
   * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
   */
  prompt?: string | Array<Array<string | number>> | undefined;
  /**
   * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
   */
  promptInterpolationMethod?: Sdxl3PromptInterpolationMethod | undefined;
  /**
   * Whether to normalize prompt weights to sum to 1.0 for consistent generation.
   */
  normalizePromptWeights?: boolean | undefined;
  /**
   * Whether to normalize seed weights to sum to 1.0 for consistent generation.
   */
  normalizeSeedWeights?: boolean | undefined;
  /**
   * Text describing what to avoid in the generated image.
   */
  negativePrompt?: string | undefined;
  /**
   * Strength of prompt adherence. Higher values make the model follow the prompt more strictly.
   */
  guidanceScale?: number | undefined;
  /**
   * Delta sets per-frame denoising progress: lower delta means steadier, less flicker but slower/softer; higher delta means faster, sharper but more flicker/artifacts (often reduce CFG).
   */
  delta?: number | undefined;
  /**
   * Builds the full denoising schedule (the 'grid' of possible refinement steps). Changing it changes what each step number (t_index_list value) means. Keep it fixed for a session and only adjust if you're deliberately redefining the schedule; if you do, proportionally remap your t_index_list. Typical range 10-100 with default being 50.
   */
  numInferenceSteps?: number | undefined;
  /**
   * The ordered list of step indices from the num_inference_steps schedule to execute per frame. Each index is one model pass, so latency scales with the list length. Higher indices (e.g., 40–49 on a 50-step grid) mainly polish and preserve structure (lower flicker), while lower indices (<20) rewrite structure (more flicker, creative). Values must be non-decreasing, and each between 0 and num_inference_steps.
   *
   * @remarks
   *
   * ⚠️ NOTE: t_index_list must have 1–4 elements, non-decreasing, and within [0, num_inference_steps]. The value should not go above 50.
   */
  tIndexList?: Array<number> | undefined;
  /**
   * Whether to use safety checker for content filtering
   */
  useSafetyChecker?: boolean | undefined;
  /**
   * Output image width in pixels. Must be divisible by 64 and between 384-1024.
   */
  width?: number | undefined;
  /**
   * Output image height in pixels. Must be divisible by 64 and between 384-1024.
   */
  height?: number | undefined;
  /**
   * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
   */
  loraDict?: Sdxl3LoraDict | null | undefined;
  /**
   * Whether to use Latent Consistency Model LoRA for faster inference.
   */
  useLcmLora?: boolean | undefined;
  /**
   * Identifier for the LCM LoRA model to use. Example: "latent-consistency/lcm-lora-sdv1-5"
   */
  lcmLoraId?: string | undefined;
  /**
   * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
   */
  acceleration?: Sdxl3Acceleration | undefined;
  /**
   * Whether to process multiple denoising steps in a single batch for efficiency.
   */
  useDenoisingBatch?: boolean | undefined;
  /**
   * Whether to add noise to input frames before processing. Enabling this slightly re-noises each frame to improve temporal stability, reduce ghosting/texture sticking, and prevent drift; disabling can yield sharper, lower-latency results but may increase flicker and artifact accumulation over time.
   */
  doAddNoise?: boolean | undefined;
  /**
   * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
   */
  seed?: number | Array<Array<number | number>> | undefined;
  /**
   * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
   */
  seedInterpolationMethod?: Sdxl3SeedInterpolationMethod | undefined;
  /**
   * Whether to skip frames that are too similar to the previous output to reduce flicker.
   */
  enableSimilarImageFilter?: boolean | undefined;
  /**
   * Similarity threshold for the image filter. Higher values allow more variation between frames.
   */
  similarImageFilterThreshold?: number | undefined;
  /**
   * Maximum number of consecutive frames that can be skipped by the similarity filter.
   */
  similarImageFilterMaxSkipFrame?: number | undefined;
  /**
   * Whether to skip the diffusion process. Any ControlNets or diffusion-only parameters are ignored when enabled.
   *
   * @remarks
   *         Example use cases:
   *         - Stream the output of a preprocessor (e.g. live depth maps or pose skeletons),
   *         - Run post-processors like RealESRGAN upscaler on externally provided frames,
   *         - Warm a pipeline without paying the diffusion cost.
   *       ⚠️ NOTE: skip_diffusion is evaluated at pipeline creation time; switching mid-stream triggers a pipeline reload.
   */
  skipDiffusion?: boolean | undefined;
  /**
   * List of image preprocessor configurations for image processing
   */
  imagePreprocessing?: Sdxl3ImagePreprocessing | undefined;
  /**
   * List of image postprocessor configurations for image processing
   *
   * @remarks
   *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
   */
  imagePostprocessing?: Sdxl3ImagePostprocessing | undefined;
  /**
   * List of latent preprocessor configurations for latent processing
   */
  latentPreprocessing?: Sdxl3LatentPreprocessing | undefined;
  /**
   * List of latent postprocessor configurations for latent processing
   */
  latentPostprocessing?: Sdxl3LatentPostprocessing | undefined;
  /**
   * List of ControlNet configurations for guided generation. Each ControlNet provides different types of conditioning (pose, edges, depth, etc.). Dynamic updates limited to conditioning_scale changes only; cannot add new ControlNets or change model_id/preprocessor/params without reload.
   */
  controlnets?: Array<Sdxl3Controlnet> | undefined;
  /**
   * IP adapter — Turns on IP-Adapter style conditioning and is fully hot-swappable. Available for SDXL, SDXL-faceid, SD1.5
   */
  ipAdapter?: Sdxl3IpAdapter | undefined;
  /**
   * HTTPS URL or base64-encoded data URI (data:image/[type];base64,...) of the style image to use. Base64 images are automatically cached and uploaded to storage with content-based deduplication. Maximum size: 5MB. When set, the runtime downloads the image and configures the pipeline; if omitted, a default style image is used. For 'faceid' type, the image must contain a clear face. Available for SDXL, SDXL-faceid, SD1.5
   */
  ipAdapterStyleImageUrl?: string | undefined;
  /**
   * Cached attention (StreamV2V) configuration. Enable cached attention to reuse key/value tensors across frames. ⚠️ NOTE: Enabling or disabling cached_attention requires a pipeline reload as it uses a different pipeline.
   */
  cachedAttention?: Sdxl3CachedAttention | undefined;
};

/** @internal */
export const Sdxl3Prompt1$inboundSchema: z.ZodMiniType<Sdxl3Prompt1, unknown> =
  smartUnion([types.string(), types.number()]);

export function sdxl3Prompt1FromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3Prompt1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3Prompt1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3Prompt1' from JSON`,
  );
}

/** @internal */
export const Sdxl3Prompt2$inboundSchema: z.ZodMiniType<Sdxl3Prompt2, unknown> =
  smartUnion([
    types.string(),
    z.array(z.array(smartUnion([types.string(), types.number()]))),
  ]);

export function sdxl3Prompt2FromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3Prompt2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3Prompt2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3Prompt2' from JSON`,
  );
}

/** @internal */
export const Sdxl3PromptInterpolationMethod$inboundSchema: z.ZodMiniType<
  Sdxl3PromptInterpolationMethod,
  unknown
> = openEnums.inboundSchema(Sdxl3PromptInterpolationMethod);

/** @internal */
export const Sdxl3LoraDict$inboundSchema: z.ZodMiniType<
  Sdxl3LoraDict,
  unknown
> = z.object({});

export function sdxl3LoraDictFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3LoraDict, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3LoraDict$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3LoraDict' from JSON`,
  );
}

/** @internal */
export const Sdxl3Acceleration$inboundSchema: z.ZodMiniType<
  Sdxl3Acceleration,
  unknown
> = openEnums.inboundSchema(Sdxl3Acceleration);

/** @internal */
export const Sdxl3Seed1$inboundSchema: z.ZodMiniType<Sdxl3Seed1, unknown> =
  smartUnion([types.number(), types.number()]);

export function sdxl3Seed1FromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3Seed1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3Seed1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3Seed1' from JSON`,
  );
}

/** @internal */
export const Sdxl3Seed2$inboundSchema: z.ZodMiniType<Sdxl3Seed2, unknown> =
  smartUnion([
    types.number(),
    z.array(z.array(smartUnion([types.number(), types.number()]))),
  ]);

export function sdxl3Seed2FromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3Seed2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3Seed2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3Seed2' from JSON`,
  );
}

/** @internal */
export const Sdxl3SeedInterpolationMethod$inboundSchema: z.ZodMiniType<
  Sdxl3SeedInterpolationMethod,
  unknown
> = openEnums.inboundSchema(Sdxl3SeedInterpolationMethod);

/** @internal */
export const Sdxl3ImagePreprocessingType$inboundSchema: z.ZodMiniType<
  Sdxl3ImagePreprocessingType,
  unknown
> = openEnums.inboundSchema(Sdxl3ImagePreprocessingType);

/** @internal */
export const Sdxl3ImagePreprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sdxl3ImagePreprocessingProcessor,
  unknown
> = z.object({
  type: Sdxl3ImagePreprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdxl3ImagePreprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3ImagePreprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3ImagePreprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3ImagePreprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sdxl3ImagePreprocessing$inboundSchema: z.ZodMiniType<
  Sdxl3ImagePreprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sdxl3ImagePreprocessingProcessor$inboundSchema),
  ),
});

export function sdxl3ImagePreprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3ImagePreprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3ImagePreprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3ImagePreprocessing' from JSON`,
  );
}

/** @internal */
export const Sdxl3ImagePostprocessingType$inboundSchema: z.ZodMiniType<
  Sdxl3ImagePostprocessingType,
  unknown
> = openEnums.inboundSchema(Sdxl3ImagePostprocessingType);

/** @internal */
export const Sdxl3ImagePostprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sdxl3ImagePostprocessingProcessor,
  unknown
> = z.object({
  type: Sdxl3ImagePostprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdxl3ImagePostprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3ImagePostprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3ImagePostprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3ImagePostprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sdxl3ImagePostprocessing$inboundSchema: z.ZodMiniType<
  Sdxl3ImagePostprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sdxl3ImagePostprocessingProcessor$inboundSchema),
  ),
});

export function sdxl3ImagePostprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3ImagePostprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3ImagePostprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3ImagePostprocessing' from JSON`,
  );
}

/** @internal */
export const Sdxl3LatentPreprocessingType$inboundSchema: z.ZodMiniEnum<
  typeof Sdxl3LatentPreprocessingType
> = z.enum(Sdxl3LatentPreprocessingType);

/** @internal */
export const Sdxl3LatentPreprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sdxl3LatentPreprocessingProcessor,
  unknown
> = z.object({
  type: Sdxl3LatentPreprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdxl3LatentPreprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3LatentPreprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3LatentPreprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3LatentPreprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sdxl3LatentPreprocessing$inboundSchema: z.ZodMiniType<
  Sdxl3LatentPreprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sdxl3LatentPreprocessingProcessor$inboundSchema),
  ),
});

export function sdxl3LatentPreprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3LatentPreprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3LatentPreprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3LatentPreprocessing' from JSON`,
  );
}

/** @internal */
export const Sdxl3LatentPostprocessingType$inboundSchema: z.ZodMiniEnum<
  typeof Sdxl3LatentPostprocessingType
> = z.enum(Sdxl3LatentPostprocessingType);

/** @internal */
export const Sdxl3LatentPostprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sdxl3LatentPostprocessingProcessor,
  unknown
> = z.object({
  type: Sdxl3LatentPostprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdxl3LatentPostprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3LatentPostprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      Sdxl3LatentPostprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3LatentPostprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sdxl3LatentPostprocessing$inboundSchema: z.ZodMiniType<
  Sdxl3LatentPostprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sdxl3LatentPostprocessingProcessor$inboundSchema),
  ),
});

export function sdxl3LatentPostprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3LatentPostprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3LatentPostprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3LatentPostprocessing' from JSON`,
  );
}

/** @internal */
export const Sdxl3ControlnetModelId$inboundSchema: z.ZodMiniType<
  Sdxl3ControlnetModelId,
  unknown
> = openEnums.inboundSchema(Sdxl3ControlnetModelId);

/** @internal */
export const Sdxl3Preprocessor$inboundSchema: z.ZodMiniType<
  Sdxl3Preprocessor,
  unknown
> = openEnums.inboundSchema(Sdxl3Preprocessor);

/** @internal */
export const Sdxl3Controlnet$inboundSchema: z.ZodMiniType<
  Sdxl3Controlnet,
  unknown
> = z.pipe(
  z.object({
    model_id: Sdxl3ControlnetModelId$inboundSchema,
    conditioning_scale: types.number(),
    preprocessor: Sdxl3Preprocessor$inboundSchema,
    preprocessor_params: types.optional(z.record(z.string(), z.any())),
    enabled: types.boolean(),
    control_guidance_start: types.optional(types.number()),
    control_guidance_end: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_id": "modelId",
      "conditioning_scale": "conditioningScale",
      "preprocessor_params": "preprocessorParams",
      "control_guidance_start": "controlGuidanceStart",
      "control_guidance_end": "controlGuidanceEnd",
    });
  }),
);

export function sdxl3ControlnetFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3Controlnet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3Controlnet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3Controlnet' from JSON`,
  );
}

/** @internal */
export const Sdxl3IpAdapterType$inboundSchema: z.ZodMiniType<
  Sdxl3IpAdapterType,
  unknown
> = openEnums.inboundSchema(Sdxl3IpAdapterType);

/** @internal */
export const Sdxl3WeightType$inboundSchema: z.ZodMiniType<
  Sdxl3WeightType,
  unknown
> = openEnums.inboundSchema(Sdxl3WeightType);

/** @internal */
export const Sdxl3IpAdapter$inboundSchema: z.ZodMiniType<
  Sdxl3IpAdapter,
  unknown
> = z.pipe(
  z.object({
    type: z._default(Sdxl3IpAdapterType$inboundSchema, "regular"),
    enabled: types.optional(types.boolean()),
    scale: types.optional(types.number()),
    weight_type: types.optional(Sdxl3WeightType$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "weight_type": "weightType",
    });
  }),
);

export function sdxl3IpAdapterFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3IpAdapter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3IpAdapter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3IpAdapter' from JSON`,
  );
}

/** @internal */
export const Sdxl3CachedAttention$inboundSchema: z.ZodMiniType<
  Sdxl3CachedAttention,
  unknown
> = z.pipe(
  z.object({
    enabled: types.boolean(),
    max_frames: types.number(),
    interval: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "max_frames": "maxFrames",
    });
  }),
);

export function sdxl3CachedAttentionFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3CachedAttention, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3CachedAttention$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3CachedAttention' from JSON`,
  );
}

/** @internal */
export const Sdxl3$inboundSchema: z.ZodMiniType<Sdxl3, unknown> = z.pipe(
  z.object({
    model_id: types.literal("stabilityai/sdxl-turbo"),
    prompt: types.optional(
      smartUnion([
        types.string(),
        z.array(z.array(smartUnion([types.string(), types.number()]))),
      ]),
    ),
    prompt_interpolation_method: types.optional(
      Sdxl3PromptInterpolationMethod$inboundSchema,
    ),
    normalize_prompt_weights: types.optional(types.boolean()),
    normalize_seed_weights: types.optional(types.boolean()),
    negative_prompt: types.optional(types.string()),
    guidance_scale: types.optional(types.number()),
    delta: types.optional(types.number()),
    num_inference_steps: types.optional(types.number()),
    t_index_list: types.optional(z.array(types.number())),
    use_safety_checker: types.optional(types.boolean()),
    width: types.optional(types.number()),
    height: types.optional(types.number()),
    lora_dict: z.optional(
      z.nullable(z.lazy(() => Sdxl3LoraDict$inboundSchema)),
    ),
    use_lcm_lora: types.optional(types.boolean()),
    lcm_lora_id: types.optional(types.string()),
    acceleration: types.optional(Sdxl3Acceleration$inboundSchema),
    use_denoising_batch: types.optional(types.boolean()),
    do_add_noise: types.optional(types.boolean()),
    seed: types.optional(
      smartUnion([
        types.number(),
        z.array(z.array(smartUnion([types.number(), types.number()]))),
      ]),
    ),
    seed_interpolation_method: types.optional(
      Sdxl3SeedInterpolationMethod$inboundSchema,
    ),
    enable_similar_image_filter: types.optional(types.boolean()),
    similar_image_filter_threshold: types.optional(types.number()),
    similar_image_filter_max_skip_frame: types.optional(types.number()),
    skip_diffusion: types.optional(types.boolean()),
    image_preprocessing: types.optional(
      z.lazy(() => Sdxl3ImagePreprocessing$inboundSchema),
    ),
    image_postprocessing: types.optional(
      z.lazy(() => Sdxl3ImagePostprocessing$inboundSchema),
    ),
    latent_preprocessing: types.optional(
      z.lazy(() => Sdxl3LatentPreprocessing$inboundSchema),
    ),
    latent_postprocessing: types.optional(
      z.lazy(() => Sdxl3LatentPostprocessing$inboundSchema),
    ),
    controlnets: types.optional(
      z.array(z.lazy(() => Sdxl3Controlnet$inboundSchema)),
    ),
    ip_adapter: types.optional(z.lazy(() => Sdxl3IpAdapter$inboundSchema)),
    ip_adapter_style_image_url: types.optional(types.string()),
    cached_attention: types.optional(
      z.lazy(() => Sdxl3CachedAttention$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_id": "modelId",
      "prompt_interpolation_method": "promptInterpolationMethod",
      "normalize_prompt_weights": "normalizePromptWeights",
      "normalize_seed_weights": "normalizeSeedWeights",
      "negative_prompt": "negativePrompt",
      "guidance_scale": "guidanceScale",
      "num_inference_steps": "numInferenceSteps",
      "t_index_list": "tIndexList",
      "use_safety_checker": "useSafetyChecker",
      "lora_dict": "loraDict",
      "use_lcm_lora": "useLcmLora",
      "lcm_lora_id": "lcmLoraId",
      "use_denoising_batch": "useDenoisingBatch",
      "do_add_noise": "doAddNoise",
      "seed_interpolation_method": "seedInterpolationMethod",
      "enable_similar_image_filter": "enableSimilarImageFilter",
      "similar_image_filter_threshold": "similarImageFilterThreshold",
      "similar_image_filter_max_skip_frame": "similarImageFilterMaxSkipFrame",
      "skip_diffusion": "skipDiffusion",
      "image_preprocessing": "imagePreprocessing",
      "image_postprocessing": "imagePostprocessing",
      "latent_preprocessing": "latentPreprocessing",
      "latent_postprocessing": "latentPostprocessing",
      "ip_adapter": "ipAdapter",
      "ip_adapter_style_image_url": "ipAdapterStyleImageUrl",
      "cached_attention": "cachedAttention",
    });
  }),
);

export function sdxl3FromJSON(
  jsonString: string,
): SafeParseResult<Sdxl3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl3' from JSON`,
  );
}
