/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Sdxl1Prompt1 = string | number;

/**
 * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
 */
export type Sdxl1Prompt2 = string | Array<Array<string | number>>;

/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export const Sdxl1PromptInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export type Sdxl1PromptInterpolationMethod = OpenEnum<
  typeof Sdxl1PromptInterpolationMethod
>;

/**
 * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
 */
export type Sdxl1LoraDict = {};

/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export const Sdxl1Acceleration = {
  None: "none",
  Xformers: "xformers",
  Tensorrt: "tensorrt",
} as const;
/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export type Sdxl1Acceleration = OpenEnum<typeof Sdxl1Acceleration>;

export type Sdxl1Seed1 = number | number;

/**
 * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
 */
export type Sdxl1Seed2 = number | Array<Array<number | number>>;

/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export const Sdxl1SeedInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export type Sdxl1SeedInterpolationMethod = OpenEnum<
  typeof Sdxl1SeedInterpolationMethod
>;

export const Sdxl1ImagePreprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type Sdxl1ImagePreprocessingType = OpenEnum<
  typeof Sdxl1ImagePreprocessingType
>;

export type Sdxl1ImagePreprocessingProcessor = {
  type: Sdxl1ImagePreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image preprocessor configurations for image processing
 */
export type Sdxl1ImagePreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<Sdxl1ImagePreprocessingProcessor>;
};

export const Sdxl1ImagePostprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type Sdxl1ImagePostprocessingType = OpenEnum<
  typeof Sdxl1ImagePostprocessingType
>;

export type Sdxl1ImagePostprocessingProcessor = {
  type: Sdxl1ImagePostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image postprocessor configurations for image processing
 *
 * @remarks
 *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
 */
export type Sdxl1ImagePostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<Sdxl1ImagePostprocessingProcessor>;
};

export const Sdxl1LatentPreprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type Sdxl1LatentPreprocessingType = ClosedEnum<
  typeof Sdxl1LatentPreprocessingType
>;

export type Sdxl1LatentPreprocessingProcessor = {
  type: Sdxl1LatentPreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent preprocessor configurations for latent processing
 */
export type Sdxl1LatentPreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<Sdxl1LatentPreprocessingProcessor>;
};

export const Sdxl1LatentPostprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type Sdxl1LatentPostprocessingType = ClosedEnum<
  typeof Sdxl1LatentPostprocessingType
>;

export type Sdxl1LatentPostprocessingProcessor = {
  type: Sdxl1LatentPostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent postprocessor configurations for latent processing
 */
export type Sdxl1LatentPostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<Sdxl1LatentPostprocessingProcessor>;
};

/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export const Sdxl1ControlnetModelId = {
  XinsirControlnetDepthSdxl10: "xinsir/controlnet-depth-sdxl-1.0",
  XinsirControlnetCannySdxl10: "xinsir/controlnet-canny-sdxl-1.0",
  XinsirControlnetTileSdxl10: "xinsir/controlnet-tile-sdxl-1.0",
} as const;
/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export type Sdxl1ControlnetModelId = OpenEnum<typeof Sdxl1ControlnetModelId>;

/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export const Sdxl1Preprocessor = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export type Sdxl1Preprocessor = OpenEnum<typeof Sdxl1Preprocessor>;

export type Sdxl1Controlnet = {
  /**
   * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
   */
  modelId: Sdxl1ControlnetModelId;
  /**
   * Strength of the ControlNet's influence on generation. Higher values make the model follow the control signal more strictly. Typical range 0.0-1.0, where 0.0 disables the control and 1.0 applies full control. Default: 1.0
   */
  conditioningScale: number;
  /**
   * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
   */
  preprocessor: Sdxl1Preprocessor;
  /**
   * Preprocessor parameters
   */
  preprocessorParams?: { [k: string]: any } | undefined;
  /**
   * Whether this ControlNet is active. Disabled ControlNets are not loaded. Default: true
   */
  enabled: boolean;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance begins. 0.0 means guidance starts from the beginning.
   */
  controlGuidanceStart?: number | undefined;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance ends. 1.0 means guidance continues until the end.
   */
  controlGuidanceEnd?: number | undefined;
};

/**
 * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
 */
export const Sdxl1IpAdapterType = {
  Regular: "regular",
  Faceid: "faceid",
} as const;
/**
 * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
 */
export type Sdxl1IpAdapterType = OpenEnum<typeof Sdxl1IpAdapterType>;

/**
 * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
 */
export const Sdxl1WeightType = {
  Linear: "linear",
  EaseIn: "ease in",
  EaseOut: "ease out",
  EaseInOut: "ease in-out",
  ReverseInOut: "reverse in-out",
  WeakInput: "weak input",
  WeakOutput: "weak output",
  WeakMiddle: "weak middle",
  StrongMiddle: "strong middle",
  StyleTransfer: "style transfer",
  Composition: "composition",
  StrongStyleTransfer: "strong style transfer",
  StyleAndComposition: "style and composition",
  StyleTransferPrecise: "style transfer precise",
  CompositionPrecise: "composition precise",
} as const;
/**
 * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
 */
export type Sdxl1WeightType = OpenEnum<typeof Sdxl1WeightType>;

/**
 * IP adapter — Turns on IP-Adapter style conditioning and is fully hot-swappable. Available for SDXL, SDXL-faceid, SD1.5
 */
export type Sdxl1IpAdapter = {
  /**
   * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
   */
  type: Sdxl1IpAdapterType;
  /**
   * Whether IP adapter is enabled
   */
  enabled?: boolean | undefined;
  /**
   * Strength of IP adapter style conditioning
   */
  scale?: number | undefined;
  /**
   * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
   */
  weightType?: Sdxl1WeightType | undefined;
};

/**
 * Cached attention (StreamV2V) configuration. Enable cached attention to reuse key/value tensors across frames. ⚠️ NOTE: Enabling or disabling cached_attention requires a pipeline reload as it uses a different pipeline.
 */
export type Sdxl1CachedAttention = {
  /**
   * Whether this cached attention is active. Enable cached attention to reuse key/value tensors across frames.
   */
  enabled: boolean;
  /**
   * Number of frames retained in the attention cache. Number of historical K/V frames to retain. Limited by TensorRT engine exports.
   */
  maxFrames: number;
  /**
   * Cadence (number of frames) for refreshing cached key/value tensors i.e How often (in number of frames) to refresh the cache.
   *
   * @remarks
   *       It is now **frame-based** (not seconds). It accepts integers 1-240, representing how many frames elapse between cache refreshes.
   */
  interval: number;
};

export type Sdxl1 = {
  modelId: "stabilityai/sdxl-turbo";
  /**
   * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
   */
  prompt?: string | Array<Array<string | number>> | undefined;
  /**
   * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
   */
  promptInterpolationMethod?: Sdxl1PromptInterpolationMethod | undefined;
  /**
   * Whether to normalize prompt weights to sum to 1.0 for consistent generation.
   */
  normalizePromptWeights?: boolean | undefined;
  /**
   * Whether to normalize seed weights to sum to 1.0 for consistent generation.
   */
  normalizeSeedWeights?: boolean | undefined;
  /**
   * Text describing what to avoid in the generated image.
   */
  negativePrompt?: string | undefined;
  /**
   * Strength of prompt adherence. Higher values make the model follow the prompt more strictly.
   */
  guidanceScale?: number | undefined;
  /**
   * Delta sets per-frame denoising progress: lower delta means steadier, less flicker but slower/softer; higher delta means faster, sharper but more flicker/artifacts (often reduce CFG).
   */
  delta?: number | undefined;
  /**
   * Builds the full denoising schedule (the 'grid' of possible refinement steps). Changing it changes what each step number (t_index_list value) means. Keep it fixed for a session and only adjust if you're deliberately redefining the schedule; if you do, proportionally remap your t_index_list. Typical range 10-100 with default being 50.
   */
  numInferenceSteps?: number | undefined;
  /**
   * The ordered list of step indices from the num_inference_steps schedule to execute per frame. Each index is one model pass, so latency scales with the list length. Higher indices (e.g., 40–49 on a 50-step grid) mainly polish and preserve structure (lower flicker), while lower indices (<20) rewrite structure (more flicker, creative). Values must be non-decreasing, and each between 0 and num_inference_steps.
   *
   * @remarks
   *
   * ⚠️ NOTE: t_index_list must have 1–4 elements, non-decreasing, and within [0, num_inference_steps]. The value should not go above 50.
   */
  tIndexList?: Array<number> | undefined;
  /**
   * Whether to use safety checker for content filtering
   */
  useSafetyChecker?: boolean | undefined;
  /**
   * Output image width in pixels. Must be divisible by 64 and between 384-1024.
   */
  width?: number | undefined;
  /**
   * Output image height in pixels. Must be divisible by 64 and between 384-1024.
   */
  height?: number | undefined;
  /**
   * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
   */
  loraDict?: Sdxl1LoraDict | null | undefined;
  /**
   * Whether to use Latent Consistency Model LoRA for faster inference.
   */
  useLcmLora?: boolean | undefined;
  /**
   * Identifier for the LCM LoRA model to use. Example: "latent-consistency/lcm-lora-sdv1-5"
   */
  lcmLoraId?: string | undefined;
  /**
   * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
   */
  acceleration?: Sdxl1Acceleration | undefined;
  /**
   * Whether to process multiple denoising steps in a single batch for efficiency.
   */
  useDenoisingBatch?: boolean | undefined;
  /**
   * Whether to add noise to input frames before processing. Enabling this slightly re-noises each frame to improve temporal stability, reduce ghosting/texture sticking, and prevent drift; disabling can yield sharper, lower-latency results but may increase flicker and artifact accumulation over time.
   */
  doAddNoise?: boolean | undefined;
  /**
   * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
   */
  seed?: number | Array<Array<number | number>> | undefined;
  /**
   * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
   */
  seedInterpolationMethod?: Sdxl1SeedInterpolationMethod | undefined;
  /**
   * Whether to skip frames that are too similar to the previous output to reduce flicker.
   */
  enableSimilarImageFilter?: boolean | undefined;
  /**
   * Similarity threshold for the image filter. Higher values allow more variation between frames.
   */
  similarImageFilterThreshold?: number | undefined;
  /**
   * Maximum number of consecutive frames that can be skipped by the similarity filter.
   */
  similarImageFilterMaxSkipFrame?: number | undefined;
  /**
   * Whether to skip the diffusion process. Any ControlNets or diffusion-only parameters are ignored when enabled.
   *
   * @remarks
   *         Example use cases:
   *         - Stream the output of a preprocessor (e.g. live depth maps or pose skeletons),
   *         - Run post-processors like RealESRGAN upscaler on externally provided frames,
   *         - Warm a pipeline without paying the diffusion cost.
   *       ⚠️ NOTE: skip_diffusion is evaluated at pipeline creation time; switching mid-stream triggers a pipeline reload.
   */
  skipDiffusion?: boolean | undefined;
  /**
   * List of image preprocessor configurations for image processing
   */
  imagePreprocessing?: Sdxl1ImagePreprocessing | undefined;
  /**
   * List of image postprocessor configurations for image processing
   *
   * @remarks
   *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
   */
  imagePostprocessing?: Sdxl1ImagePostprocessing | undefined;
  /**
   * List of latent preprocessor configurations for latent processing
   */
  latentPreprocessing?: Sdxl1LatentPreprocessing | undefined;
  /**
   * List of latent postprocessor configurations for latent processing
   */
  latentPostprocessing?: Sdxl1LatentPostprocessing | undefined;
  /**
   * List of ControlNet configurations for guided generation. Each ControlNet provides different types of conditioning (pose, edges, depth, etc.). Dynamic updates limited to conditioning_scale changes only; cannot add new ControlNets or change model_id/preprocessor/params without reload.
   */
  controlnets?: Array<Sdxl1Controlnet> | undefined;
  /**
   * IP adapter — Turns on IP-Adapter style conditioning and is fully hot-swappable. Available for SDXL, SDXL-faceid, SD1.5
   */
  ipAdapter?: Sdxl1IpAdapter | undefined;
  /**
   * HTTPS URL or base64-encoded data URI (data:image/[type];base64,...) of the style image to use. Base64 images are automatically cached and uploaded to storage with content-based deduplication. Maximum size: 5MB. When set, the runtime downloads the image and configures the pipeline; if omitted, a default style image is used. For 'faceid' type, the image must contain a clear face. Available for SDXL, SDXL-faceid, SD1.5
   */
  ipAdapterStyleImageUrl?: string | undefined;
  /**
   * Cached attention (StreamV2V) configuration. Enable cached attention to reuse key/value tensors across frames. ⚠️ NOTE: Enabling or disabling cached_attention requires a pipeline reload as it uses a different pipeline.
   */
  cachedAttention?: Sdxl1CachedAttention | undefined;
};

/** @internal */
export const Sdxl1Prompt1$inboundSchema: z.ZodMiniType<Sdxl1Prompt1, unknown> =
  smartUnion([types.string(), types.number()]);

export function sdxl1Prompt1FromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1Prompt1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1Prompt1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1Prompt1' from JSON`,
  );
}

/** @internal */
export const Sdxl1Prompt2$inboundSchema: z.ZodMiniType<Sdxl1Prompt2, unknown> =
  smartUnion([
    types.string(),
    z.array(z.array(smartUnion([types.string(), types.number()]))),
  ]);

export function sdxl1Prompt2FromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1Prompt2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1Prompt2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1Prompt2' from JSON`,
  );
}

/** @internal */
export const Sdxl1PromptInterpolationMethod$inboundSchema: z.ZodMiniType<
  Sdxl1PromptInterpolationMethod,
  unknown
> = openEnums.inboundSchema(Sdxl1PromptInterpolationMethod);

/** @internal */
export const Sdxl1LoraDict$inboundSchema: z.ZodMiniType<
  Sdxl1LoraDict,
  unknown
> = z.object({});

export function sdxl1LoraDictFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1LoraDict, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1LoraDict$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1LoraDict' from JSON`,
  );
}

/** @internal */
export const Sdxl1Acceleration$inboundSchema: z.ZodMiniType<
  Sdxl1Acceleration,
  unknown
> = openEnums.inboundSchema(Sdxl1Acceleration);

/** @internal */
export const Sdxl1Seed1$inboundSchema: z.ZodMiniType<Sdxl1Seed1, unknown> =
  smartUnion([types.number(), types.number()]);

export function sdxl1Seed1FromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1Seed1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1Seed1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1Seed1' from JSON`,
  );
}

/** @internal */
export const Sdxl1Seed2$inboundSchema: z.ZodMiniType<Sdxl1Seed2, unknown> =
  smartUnion([
    types.number(),
    z.array(z.array(smartUnion([types.number(), types.number()]))),
  ]);

export function sdxl1Seed2FromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1Seed2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1Seed2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1Seed2' from JSON`,
  );
}

/** @internal */
export const Sdxl1SeedInterpolationMethod$inboundSchema: z.ZodMiniType<
  Sdxl1SeedInterpolationMethod,
  unknown
> = openEnums.inboundSchema(Sdxl1SeedInterpolationMethod);

/** @internal */
export const Sdxl1ImagePreprocessingType$inboundSchema: z.ZodMiniType<
  Sdxl1ImagePreprocessingType,
  unknown
> = openEnums.inboundSchema(Sdxl1ImagePreprocessingType);

/** @internal */
export const Sdxl1ImagePreprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sdxl1ImagePreprocessingProcessor,
  unknown
> = z.object({
  type: Sdxl1ImagePreprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdxl1ImagePreprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1ImagePreprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1ImagePreprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1ImagePreprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sdxl1ImagePreprocessing$inboundSchema: z.ZodMiniType<
  Sdxl1ImagePreprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sdxl1ImagePreprocessingProcessor$inboundSchema),
  ),
});

export function sdxl1ImagePreprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1ImagePreprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1ImagePreprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1ImagePreprocessing' from JSON`,
  );
}

/** @internal */
export const Sdxl1ImagePostprocessingType$inboundSchema: z.ZodMiniType<
  Sdxl1ImagePostprocessingType,
  unknown
> = openEnums.inboundSchema(Sdxl1ImagePostprocessingType);

/** @internal */
export const Sdxl1ImagePostprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sdxl1ImagePostprocessingProcessor,
  unknown
> = z.object({
  type: Sdxl1ImagePostprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdxl1ImagePostprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1ImagePostprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1ImagePostprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1ImagePostprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sdxl1ImagePostprocessing$inboundSchema: z.ZodMiniType<
  Sdxl1ImagePostprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sdxl1ImagePostprocessingProcessor$inboundSchema),
  ),
});

export function sdxl1ImagePostprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1ImagePostprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1ImagePostprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1ImagePostprocessing' from JSON`,
  );
}

/** @internal */
export const Sdxl1LatentPreprocessingType$inboundSchema: z.ZodMiniEnum<
  typeof Sdxl1LatentPreprocessingType
> = z.enum(Sdxl1LatentPreprocessingType);

/** @internal */
export const Sdxl1LatentPreprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sdxl1LatentPreprocessingProcessor,
  unknown
> = z.object({
  type: Sdxl1LatentPreprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdxl1LatentPreprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1LatentPreprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1LatentPreprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1LatentPreprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sdxl1LatentPreprocessing$inboundSchema: z.ZodMiniType<
  Sdxl1LatentPreprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sdxl1LatentPreprocessingProcessor$inboundSchema),
  ),
});

export function sdxl1LatentPreprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1LatentPreprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1LatentPreprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1LatentPreprocessing' from JSON`,
  );
}

/** @internal */
export const Sdxl1LatentPostprocessingType$inboundSchema: z.ZodMiniEnum<
  typeof Sdxl1LatentPostprocessingType
> = z.enum(Sdxl1LatentPostprocessingType);

/** @internal */
export const Sdxl1LatentPostprocessingProcessor$inboundSchema: z.ZodMiniType<
  Sdxl1LatentPostprocessingProcessor,
  unknown
> = z.object({
  type: Sdxl1LatentPostprocessingType$inboundSchema,
  enabled: types.optional(types.boolean()),
  params: types.optional(z.record(z.string(), z.any())),
});

export function sdxl1LatentPostprocessingProcessorFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1LatentPostprocessingProcessor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      Sdxl1LatentPostprocessingProcessor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1LatentPostprocessingProcessor' from JSON`,
  );
}

/** @internal */
export const Sdxl1LatentPostprocessing$inboundSchema: z.ZodMiniType<
  Sdxl1LatentPostprocessing,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  processors: z.array(
    z.lazy(() => Sdxl1LatentPostprocessingProcessor$inboundSchema),
  ),
});

export function sdxl1LatentPostprocessingFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1LatentPostprocessing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1LatentPostprocessing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1LatentPostprocessing' from JSON`,
  );
}

/** @internal */
export const Sdxl1ControlnetModelId$inboundSchema: z.ZodMiniType<
  Sdxl1ControlnetModelId,
  unknown
> = openEnums.inboundSchema(Sdxl1ControlnetModelId);

/** @internal */
export const Sdxl1Preprocessor$inboundSchema: z.ZodMiniType<
  Sdxl1Preprocessor,
  unknown
> = openEnums.inboundSchema(Sdxl1Preprocessor);

/** @internal */
export const Sdxl1Controlnet$inboundSchema: z.ZodMiniType<
  Sdxl1Controlnet,
  unknown
> = z.pipe(
  z.object({
    model_id: Sdxl1ControlnetModelId$inboundSchema,
    conditioning_scale: types.number(),
    preprocessor: Sdxl1Preprocessor$inboundSchema,
    preprocessor_params: types.optional(z.record(z.string(), z.any())),
    enabled: types.boolean(),
    control_guidance_start: types.optional(types.number()),
    control_guidance_end: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_id": "modelId",
      "conditioning_scale": "conditioningScale",
      "preprocessor_params": "preprocessorParams",
      "control_guidance_start": "controlGuidanceStart",
      "control_guidance_end": "controlGuidanceEnd",
    });
  }),
);

export function sdxl1ControlnetFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1Controlnet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1Controlnet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1Controlnet' from JSON`,
  );
}

/** @internal */
export const Sdxl1IpAdapterType$inboundSchema: z.ZodMiniType<
  Sdxl1IpAdapterType,
  unknown
> = openEnums.inboundSchema(Sdxl1IpAdapterType);

/** @internal */
export const Sdxl1WeightType$inboundSchema: z.ZodMiniType<
  Sdxl1WeightType,
  unknown
> = openEnums.inboundSchema(Sdxl1WeightType);

/** @internal */
export const Sdxl1IpAdapter$inboundSchema: z.ZodMiniType<
  Sdxl1IpAdapter,
  unknown
> = z.pipe(
  z.object({
    type: z._default(Sdxl1IpAdapterType$inboundSchema, "regular"),
    enabled: types.optional(types.boolean()),
    scale: types.optional(types.number()),
    weight_type: types.optional(Sdxl1WeightType$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "weight_type": "weightType",
    });
  }),
);

export function sdxl1IpAdapterFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1IpAdapter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1IpAdapter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1IpAdapter' from JSON`,
  );
}

/** @internal */
export const Sdxl1CachedAttention$inboundSchema: z.ZodMiniType<
  Sdxl1CachedAttention,
  unknown
> = z.pipe(
  z.object({
    enabled: types.boolean(),
    max_frames: types.number(),
    interval: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "max_frames": "maxFrames",
    });
  }),
);

export function sdxl1CachedAttentionFromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1CachedAttention, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1CachedAttention$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1CachedAttention' from JSON`,
  );
}

/** @internal */
export const Sdxl1$inboundSchema: z.ZodMiniType<Sdxl1, unknown> = z.pipe(
  z.object({
    model_id: types.literal("stabilityai/sdxl-turbo"),
    prompt: types.optional(
      smartUnion([
        types.string(),
        z.array(z.array(smartUnion([types.string(), types.number()]))),
      ]),
    ),
    prompt_interpolation_method: types.optional(
      Sdxl1PromptInterpolationMethod$inboundSchema,
    ),
    normalize_prompt_weights: types.optional(types.boolean()),
    normalize_seed_weights: types.optional(types.boolean()),
    negative_prompt: types.optional(types.string()),
    guidance_scale: types.optional(types.number()),
    delta: types.optional(types.number()),
    num_inference_steps: types.optional(types.number()),
    t_index_list: types.optional(z.array(types.number())),
    use_safety_checker: types.optional(types.boolean()),
    width: types.optional(types.number()),
    height: types.optional(types.number()),
    lora_dict: z.optional(
      z.nullable(z.lazy(() => Sdxl1LoraDict$inboundSchema)),
    ),
    use_lcm_lora: types.optional(types.boolean()),
    lcm_lora_id: types.optional(types.string()),
    acceleration: types.optional(Sdxl1Acceleration$inboundSchema),
    use_denoising_batch: types.optional(types.boolean()),
    do_add_noise: types.optional(types.boolean()),
    seed: types.optional(
      smartUnion([
        types.number(),
        z.array(z.array(smartUnion([types.number(), types.number()]))),
      ]),
    ),
    seed_interpolation_method: types.optional(
      Sdxl1SeedInterpolationMethod$inboundSchema,
    ),
    enable_similar_image_filter: types.optional(types.boolean()),
    similar_image_filter_threshold: types.optional(types.number()),
    similar_image_filter_max_skip_frame: types.optional(types.number()),
    skip_diffusion: types.optional(types.boolean()),
    image_preprocessing: types.optional(
      z.lazy(() => Sdxl1ImagePreprocessing$inboundSchema),
    ),
    image_postprocessing: types.optional(
      z.lazy(() => Sdxl1ImagePostprocessing$inboundSchema),
    ),
    latent_preprocessing: types.optional(
      z.lazy(() => Sdxl1LatentPreprocessing$inboundSchema),
    ),
    latent_postprocessing: types.optional(
      z.lazy(() => Sdxl1LatentPostprocessing$inboundSchema),
    ),
    controlnets: types.optional(
      z.array(z.lazy(() => Sdxl1Controlnet$inboundSchema)),
    ),
    ip_adapter: types.optional(z.lazy(() => Sdxl1IpAdapter$inboundSchema)),
    ip_adapter_style_image_url: types.optional(types.string()),
    cached_attention: types.optional(
      z.lazy(() => Sdxl1CachedAttention$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "model_id": "modelId",
      "prompt_interpolation_method": "promptInterpolationMethod",
      "normalize_prompt_weights": "normalizePromptWeights",
      "normalize_seed_weights": "normalizeSeedWeights",
      "negative_prompt": "negativePrompt",
      "guidance_scale": "guidanceScale",
      "num_inference_steps": "numInferenceSteps",
      "t_index_list": "tIndexList",
      "use_safety_checker": "useSafetyChecker",
      "lora_dict": "loraDict",
      "use_lcm_lora": "useLcmLora",
      "lcm_lora_id": "lcmLoraId",
      "use_denoising_batch": "useDenoisingBatch",
      "do_add_noise": "doAddNoise",
      "seed_interpolation_method": "seedInterpolationMethod",
      "enable_similar_image_filter": "enableSimilarImageFilter",
      "similar_image_filter_threshold": "similarImageFilterThreshold",
      "similar_image_filter_max_skip_frame": "similarImageFilterMaxSkipFrame",
      "skip_diffusion": "skipDiffusion",
      "image_preprocessing": "imagePreprocessing",
      "image_postprocessing": "imagePostprocessing",
      "latent_preprocessing": "latentPreprocessing",
      "latent_postprocessing": "latentPostprocessing",
      "ip_adapter": "ipAdapter",
      "ip_adapter_style_image_url": "ipAdapterStyleImageUrl",
      "cached_attention": "cachedAttention",
    });
  }),
);

export function sdxl1FromJSON(
  jsonString: string,
): SafeParseResult<Sdxl1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sdxl1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sdxl1' from JSON`,
  );
}
