/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smartUnion.js";

export type Sdxl2Prompt1 = string | number;

/**
 * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
 */
export type Sdxl2Prompt2 = string | Array<Array<string | number>>;

/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export const Sdxl2PromptInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
 */
export type Sdxl2PromptInterpolationMethod = ClosedEnum<
  typeof Sdxl2PromptInterpolationMethod
>;

/**
 * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
 */
export type Sdxl2LoraDict = {};

/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export const Sdxl2Acceleration = {
  None: "none",
  Xformers: "xformers",
  Tensorrt: "tensorrt",
} as const;
/**
 * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
 */
export type Sdxl2Acceleration = ClosedEnum<typeof Sdxl2Acceleration>;

export type Sdxl2Seed1 = number | number;

/**
 * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
 */
export type Sdxl2Seed2 = number | Array<Array<number | number>>;

/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export const Sdxl2SeedInterpolationMethod = {
  Linear: "linear",
  Slerp: "slerp",
} as const;
/**
 * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
 */
export type Sdxl2SeedInterpolationMethod = ClosedEnum<
  typeof Sdxl2SeedInterpolationMethod
>;

export const Sdxl2ImagePreprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type Sdxl2ImagePreprocessingType = ClosedEnum<
  typeof Sdxl2ImagePreprocessingType
>;

export type Sdxl2ImagePreprocessingProcessor = {
  type: Sdxl2ImagePreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image preprocessor configurations for image processing
 */
export type Sdxl2ImagePreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<Sdxl2ImagePreprocessingProcessor>;
};

export const Sdxl2ImagePostprocessingType = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
export type Sdxl2ImagePostprocessingType = ClosedEnum<
  typeof Sdxl2ImagePostprocessingType
>;

export type Sdxl2ImagePostprocessingProcessor = {
  type: Sdxl2ImagePostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of image postprocessor configurations for image processing
 *
 * @remarks
 *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
 */
export type Sdxl2ImagePostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of image processors to apply
   */
  processors: Array<Sdxl2ImagePostprocessingProcessor>;
};

export const Sdxl2LatentPreprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type Sdxl2LatentPreprocessingType = ClosedEnum<
  typeof Sdxl2LatentPreprocessingType
>;

export type Sdxl2LatentPreprocessingProcessor = {
  type: Sdxl2LatentPreprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent preprocessor configurations for latent processing
 */
export type Sdxl2LatentPreprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<Sdxl2LatentPreprocessingProcessor>;
};

export const Sdxl2LatentPostprocessingType = {
  LatentFeedback: "latent_feedback",
} as const;
export type Sdxl2LatentPostprocessingType = ClosedEnum<
  typeof Sdxl2LatentPostprocessingType
>;

export type Sdxl2LatentPostprocessingProcessor = {
  type: Sdxl2LatentPostprocessingType;
  /**
   * Whether this processor is active
   */
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/**
 * List of latent postprocessor configurations for latent processing
 */
export type Sdxl2LatentPostprocessing = {
  /**
   * Whether this processor config is active
   */
  enabled?: boolean | undefined;
  /**
   * List of latent processors to apply
   */
  processors: Array<Sdxl2LatentPostprocessingProcessor>;
};

/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export const Sdxl2ControlnetModelId = {
  XinsirControlnetDepthSdxl10: "xinsir/controlnet-depth-sdxl-1.0",
  XinsirControlnetCannySdxl10: "xinsir/controlnet-canny-sdxl-1.0",
  XinsirControlnetTileSdxl10: "xinsir/controlnet-tile-sdxl-1.0",
} as const;
/**
 * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
 */
export type Sdxl2ControlnetModelId = ClosedEnum<typeof Sdxl2ControlnetModelId>;

/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export const Sdxl2Preprocessor = {
  Blur: "blur",
  Canny: "canny",
  Depth: "depth",
  DepthTensorrt: "depth_tensorrt",
  External: "external",
  Feedback: "feedback",
  Hed: "hed",
  Lineart: "lineart",
  MediapipePose: "mediapipe_pose",
  MediapipeSegmentation: "mediapipe_segmentation",
  Openpose: "openpose",
  Passthrough: "passthrough",
  PoseTensorrt: "pose_tensorrt",
  RealesrganTrt: "realesrgan_trt",
  Sharpen: "sharpen",
  SoftEdge: "soft_edge",
  StandardLineart: "standard_lineart",
  TemporalNetTensorrt: "temporal_net_tensorrt",
  Upscale: "upscale",
} as const;
/**
 * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
 */
export type Sdxl2Preprocessor = ClosedEnum<typeof Sdxl2Preprocessor>;

export type Sdxl2Controlnet = {
  /**
   * ⚠️ NOTE: ControlNet model_ids must be unique. Additionally, they must be compatible with the selected base model.
   */
  modelId: Sdxl2ControlnetModelId;
  /**
   * Strength of the ControlNet's influence on generation. Higher values make the model follow the control signal more strictly. Typical range 0.0-1.0, where 0.0 disables the control and 1.0 applies full control. Default: 1.0
   */
  conditioningScale: number;
  /**
   * Preprocessor to apply to input frames before feeding to the ControlNet. Must be one of the supported preprocessors.
   */
  preprocessor: Sdxl2Preprocessor;
  /**
   * Preprocessor parameters
   */
  preprocessorParams?: { [k: string]: any } | undefined;
  /**
   * Whether this ControlNet is active. Disabled ControlNets are not loaded. Default: true
   */
  enabled: boolean;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance begins. 0.0 means guidance starts from the beginning.
   */
  controlGuidanceStart?: number | undefined;
  /**
   * Fraction of the denoising process (0.0-1.0) when ControlNet guidance ends. 1.0 means guidance continues until the end.
   */
  controlGuidanceEnd?: number | undefined;
};

/**
 * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
 */
export const Sdxl2IpAdapterType = {
  Regular: "regular",
  Faceid: "faceid",
} as const;
/**
 * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
 */
export type Sdxl2IpAdapterType = ClosedEnum<typeof Sdxl2IpAdapterType>;

/**
 * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
 */
export const Sdxl2WeightType = {
  Linear: "linear",
  EaseIn: "ease in",
  EaseOut: "ease out",
  EaseInOut: "ease in-out",
  ReverseInOut: "reverse in-out",
  WeakInput: "weak input",
  WeakOutput: "weak output",
  WeakMiddle: "weak middle",
  StrongMiddle: "strong middle",
  StyleTransfer: "style transfer",
  Composition: "composition",
  StrongStyleTransfer: "strong style transfer",
  StyleAndComposition: "style and composition",
  StyleTransferPrecise: "style transfer precise",
  CompositionPrecise: "composition precise",
} as const;
/**
 * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
 */
export type Sdxl2WeightType = ClosedEnum<typeof Sdxl2WeightType>;

/**
 * IP adapter — Turns on IP-Adapter style conditioning and is fully hot-swappable. Available for SDXL, SDXL-faceid, SD1.5
 */
export type Sdxl2IpAdapter = {
  /**
   * Type of IP adapter. Use 'faceid' for SDXL-faceid models, 'regular' for others
   */
  type?: Sdxl2IpAdapterType | undefined;
  /**
   * Whether IP adapter is enabled
   */
  enabled?: boolean | undefined;
  /**
   * Strength of IP adapter style conditioning
   */
  scale?: number | undefined;
  /**
   * Weight interpolation method for IP adapter style conditioning. Controls how the style influence changes throughout the generation process.
   */
  weightType?: Sdxl2WeightType | undefined;
};

/**
 * Cached attention (StreamV2V) configuration. Enable cached attention to reuse key/value tensors across frames. ⚠️ NOTE: Enabling or disabling cached_attention requires a pipeline reload as it uses a different pipeline.
 */
export type Sdxl2CachedAttention = {
  /**
   * Whether this cached attention is active. Enable cached attention to reuse key/value tensors across frames.
   */
  enabled: boolean;
  /**
   * Number of frames retained in the attention cache. Number of historical K/V frames to retain. Limited by TensorRT engine exports.
   */
  maxFrames: number;
  /**
   * Cadence (number of frames) for refreshing cached key/value tensors i.e How often (in number of frames) to refresh the cache.
   *
   * @remarks
   *       It is now **frame-based** (not seconds). It accepts integers 1-240, representing how many frames elapse between cache refreshes.
   */
  interval: number;
};

export type Sdxl2 = {
  modelId: "stabilityai/sdxl-turbo";
  /**
   * Text prompt describing the desired image. Can be a single string or weighted list of (prompt, weight) tuples.
   */
  prompt?: string | Array<Array<string | number>> | undefined;
  /**
   * Method for interpolating between multiple prompts. Slerp provides smoother transitions than linear.
   */
  promptInterpolationMethod?: Sdxl2PromptInterpolationMethod | undefined;
  /**
   * Whether to normalize prompt weights to sum to 1.0 for consistent generation.
   */
  normalizePromptWeights?: boolean | undefined;
  /**
   * Whether to normalize seed weights to sum to 1.0 for consistent generation.
   */
  normalizeSeedWeights?: boolean | undefined;
  /**
   * Text describing what to avoid in the generated image.
   */
  negativePrompt?: string | undefined;
  /**
   * Strength of prompt adherence. Higher values make the model follow the prompt more strictly.
   */
  guidanceScale?: number | undefined;
  /**
   * Delta sets per-frame denoising progress: lower delta means steadier, less flicker but slower/softer; higher delta means faster, sharper but more flicker/artifacts (often reduce CFG).
   */
  delta?: number | undefined;
  /**
   * Builds the full denoising schedule (the 'grid' of possible refinement steps). Changing it changes what each step number (t_index_list value) means. Keep it fixed for a session and only adjust if you're deliberately redefining the schedule; if you do, proportionally remap your t_index_list. Typical range 10-100 with default being 50.
   */
  numInferenceSteps?: number | undefined;
  /**
   * The ordered list of step indices from the num_inference_steps schedule to execute per frame. Each index is one model pass, so latency scales with the list length. Higher indices (e.g., 40–49 on a 50-step grid) mainly polish and preserve structure (lower flicker), while lower indices (<20) rewrite structure (more flicker, creative). Values must be non-decreasing, and each between 0 and num_inference_steps.
   *
   * @remarks
   *
   * ⚠️ NOTE: t_index_list must have 1–4 elements, non-decreasing, and within [0, num_inference_steps]. The value should not go above 50.
   */
  tIndexList?: Array<number> | undefined;
  /**
   * Whether to use safety checker for content filtering
   */
  useSafetyChecker?: boolean | undefined;
  /**
   * Output image width in pixels. Must be divisible by 64 and between 384-1024.
   */
  width?: number | undefined;
  /**
   * Output image height in pixels. Must be divisible by 64 and between 384-1024.
   */
  height?: number | undefined;
  /**
   * Dictionary mapping LoRA model paths to their weights for fine-tuning the base model.
   */
  loraDict?: Sdxl2LoraDict | null | undefined;
  /**
   * Whether to use Latent Consistency Model LoRA for faster inference.
   */
  useLcmLora?: boolean | undefined;
  /**
   * Identifier for the LCM LoRA model to use. Example: "latent-consistency/lcm-lora-sdv1-5"
   */
  lcmLoraId?: string | undefined;
  /**
   * Acceleration method for inference. Options: "none", "xformers", "tensorrt". TensorRT provides the best performance but requires engine compilation.
   */
  acceleration?: Sdxl2Acceleration | undefined;
  /**
   * Whether to process multiple denoising steps in a single batch for efficiency.
   */
  useDenoisingBatch?: boolean | undefined;
  /**
   * Whether to add noise to input frames before processing. Enabling this slightly re-noises each frame to improve temporal stability, reduce ghosting/texture sticking, and prevent drift; disabling can yield sharper, lower-latency results but may increase flicker and artifact accumulation over time.
   */
  doAddNoise?: boolean | undefined;
  /**
   * Random seed for generation. Can be a single integer or weighted list of (seed, weight) tuples.
   */
  seed?: number | Array<Array<number | number>> | undefined;
  /**
   * Method for interpolating between multiple seeds. Slerp provides smoother transitions than linear.
   */
  seedInterpolationMethod?: Sdxl2SeedInterpolationMethod | undefined;
  /**
   * Whether to skip frames that are too similar to the previous output to reduce flicker.
   */
  enableSimilarImageFilter?: boolean | undefined;
  /**
   * Similarity threshold for the image filter. Higher values allow more variation between frames.
   */
  similarImageFilterThreshold?: number | undefined;
  /**
   * Maximum number of consecutive frames that can be skipped by the similarity filter.
   */
  similarImageFilterMaxSkipFrame?: number | undefined;
  /**
   * Whether to skip the diffusion process. Any ControlNets or diffusion-only parameters are ignored when enabled.
   *
   * @remarks
   *         Example use cases:
   *         - Stream the output of a preprocessor (e.g. live depth maps or pose skeletons),
   *         - Run post-processors like RealESRGAN upscaler on externally provided frames,
   *         - Warm a pipeline without paying the diffusion cost.
   *       ⚠️ NOTE: skip_diffusion is evaluated at pipeline creation time; switching mid-stream triggers a pipeline reload.
   */
  skipDiffusion?: boolean | undefined;
  /**
   * List of image preprocessor configurations for image processing
   */
  imagePreprocessing?: Sdxl2ImagePreprocessing | undefined;
  /**
   * List of image postprocessor configurations for image processing
   *
   * @remarks
   *       ⚠️ NOTE: realesrgan_trt processor requires a restart to change because it affects resolution.
   */
  imagePostprocessing?: Sdxl2ImagePostprocessing | undefined;
  /**
   * List of latent preprocessor configurations for latent processing
   */
  latentPreprocessing?: Sdxl2LatentPreprocessing | undefined;
  /**
   * List of latent postprocessor configurations for latent processing
   */
  latentPostprocessing?: Sdxl2LatentPostprocessing | undefined;
  /**
   * List of ControlNet configurations for guided generation. Each ControlNet provides different types of conditioning (pose, edges, depth, etc.). Dynamic updates limited to conditioning_scale changes only; cannot add new ControlNets or change model_id/preprocessor/params without reload.
   */
  controlnets?: Array<Sdxl2Controlnet> | undefined;
  /**
   * IP adapter — Turns on IP-Adapter style conditioning and is fully hot-swappable. Available for SDXL, SDXL-faceid, SD1.5
   */
  ipAdapter?: Sdxl2IpAdapter | undefined;
  /**
   * HTTPS URL or base64-encoded data URI (data:image/[type];base64,...) of the style image to use. Base64 images are automatically cached and uploaded to storage with content-based deduplication. Maximum size: 5MB. When set, the runtime downloads the image and configures the pipeline; if omitted, a default style image is used. For 'faceid' type, the image must contain a clear face. Available for SDXL, SDXL-faceid, SD1.5
   */
  ipAdapterStyleImageUrl?: string | undefined;
  /**
   * Cached attention (StreamV2V) configuration. Enable cached attention to reuse key/value tensors across frames. ⚠️ NOTE: Enabling or disabling cached_attention requires a pipeline reload as it uses a different pipeline.
   */
  cachedAttention?: Sdxl2CachedAttention | undefined;
};

/** @internal */
export type Sdxl2Prompt1$Outbound = string | number;

/** @internal */
export const Sdxl2Prompt1$outboundSchema: z.ZodMiniType<
  Sdxl2Prompt1$Outbound,
  Sdxl2Prompt1
> = smartUnion([z.string(), z.number()]);

export function sdxl2Prompt1ToJSON(sdxl2Prompt1: Sdxl2Prompt1): string {
  return JSON.stringify(Sdxl2Prompt1$outboundSchema.parse(sdxl2Prompt1));
}

/** @internal */
export type Sdxl2Prompt2$Outbound = string | Array<Array<string | number>>;

/** @internal */
export const Sdxl2Prompt2$outboundSchema: z.ZodMiniType<
  Sdxl2Prompt2$Outbound,
  Sdxl2Prompt2
> = smartUnion([
  z.string(),
  z.array(z.array(smartUnion([z.string(), z.number()]))),
]);

export function sdxl2Prompt2ToJSON(sdxl2Prompt2: Sdxl2Prompt2): string {
  return JSON.stringify(Sdxl2Prompt2$outboundSchema.parse(sdxl2Prompt2));
}

/** @internal */
export const Sdxl2PromptInterpolationMethod$outboundSchema: z.ZodMiniEnum<
  typeof Sdxl2PromptInterpolationMethod
> = z.enum(Sdxl2PromptInterpolationMethod);

/** @internal */
export type Sdxl2LoraDict$Outbound = {};

/** @internal */
export const Sdxl2LoraDict$outboundSchema: z.ZodMiniType<
  Sdxl2LoraDict$Outbound,
  Sdxl2LoraDict
> = z.object({});

export function sdxl2LoraDictToJSON(sdxl2LoraDict: Sdxl2LoraDict): string {
  return JSON.stringify(Sdxl2LoraDict$outboundSchema.parse(sdxl2LoraDict));
}

/** @internal */
export const Sdxl2Acceleration$outboundSchema: z.ZodMiniEnum<
  typeof Sdxl2Acceleration
> = z.enum(Sdxl2Acceleration);

/** @internal */
export type Sdxl2Seed1$Outbound = number | number;

/** @internal */
export const Sdxl2Seed1$outboundSchema: z.ZodMiniType<
  Sdxl2Seed1$Outbound,
  Sdxl2Seed1
> = smartUnion([z.int(), z.number()]);

export function sdxl2Seed1ToJSON(sdxl2Seed1: Sdxl2Seed1): string {
  return JSON.stringify(Sdxl2Seed1$outboundSchema.parse(sdxl2Seed1));
}

/** @internal */
export type Sdxl2Seed2$Outbound = number | Array<Array<number | number>>;

/** @internal */
export const Sdxl2Seed2$outboundSchema: z.ZodMiniType<
  Sdxl2Seed2$Outbound,
  Sdxl2Seed2
> = smartUnion([z.int(), z.array(z.array(smartUnion([z.int(), z.number()])))]);

export function sdxl2Seed2ToJSON(sdxl2Seed2: Sdxl2Seed2): string {
  return JSON.stringify(Sdxl2Seed2$outboundSchema.parse(sdxl2Seed2));
}

/** @internal */
export const Sdxl2SeedInterpolationMethod$outboundSchema: z.ZodMiniEnum<
  typeof Sdxl2SeedInterpolationMethod
> = z.enum(Sdxl2SeedInterpolationMethod);

/** @internal */
export const Sdxl2ImagePreprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof Sdxl2ImagePreprocessingType
> = z.enum(Sdxl2ImagePreprocessingType);

/** @internal */
export type Sdxl2ImagePreprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const Sdxl2ImagePreprocessingProcessor$outboundSchema: z.ZodMiniType<
  Sdxl2ImagePreprocessingProcessor$Outbound,
  Sdxl2ImagePreprocessingProcessor
> = z.object({
  type: Sdxl2ImagePreprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sdxl2ImagePreprocessingProcessorToJSON(
  sdxl2ImagePreprocessingProcessor: Sdxl2ImagePreprocessingProcessor,
): string {
  return JSON.stringify(
    Sdxl2ImagePreprocessingProcessor$outboundSchema.parse(
      sdxl2ImagePreprocessingProcessor,
    ),
  );
}

/** @internal */
export type Sdxl2ImagePreprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<Sdxl2ImagePreprocessingProcessor$Outbound>;
};

/** @internal */
export const Sdxl2ImagePreprocessing$outboundSchema: z.ZodMiniType<
  Sdxl2ImagePreprocessing$Outbound,
  Sdxl2ImagePreprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => Sdxl2ImagePreprocessingProcessor$outboundSchema),
  ),
});

export function sdxl2ImagePreprocessingToJSON(
  sdxl2ImagePreprocessing: Sdxl2ImagePreprocessing,
): string {
  return JSON.stringify(
    Sdxl2ImagePreprocessing$outboundSchema.parse(sdxl2ImagePreprocessing),
  );
}

/** @internal */
export const Sdxl2ImagePostprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof Sdxl2ImagePostprocessingType
> = z.enum(Sdxl2ImagePostprocessingType);

/** @internal */
export type Sdxl2ImagePostprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const Sdxl2ImagePostprocessingProcessor$outboundSchema: z.ZodMiniType<
  Sdxl2ImagePostprocessingProcessor$Outbound,
  Sdxl2ImagePostprocessingProcessor
> = z.object({
  type: Sdxl2ImagePostprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sdxl2ImagePostprocessingProcessorToJSON(
  sdxl2ImagePostprocessingProcessor: Sdxl2ImagePostprocessingProcessor,
): string {
  return JSON.stringify(
    Sdxl2ImagePostprocessingProcessor$outboundSchema.parse(
      sdxl2ImagePostprocessingProcessor,
    ),
  );
}

/** @internal */
export type Sdxl2ImagePostprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<Sdxl2ImagePostprocessingProcessor$Outbound>;
};

/** @internal */
export const Sdxl2ImagePostprocessing$outboundSchema: z.ZodMiniType<
  Sdxl2ImagePostprocessing$Outbound,
  Sdxl2ImagePostprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => Sdxl2ImagePostprocessingProcessor$outboundSchema),
  ),
});

export function sdxl2ImagePostprocessingToJSON(
  sdxl2ImagePostprocessing: Sdxl2ImagePostprocessing,
): string {
  return JSON.stringify(
    Sdxl2ImagePostprocessing$outboundSchema.parse(sdxl2ImagePostprocessing),
  );
}

/** @internal */
export const Sdxl2LatentPreprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof Sdxl2LatentPreprocessingType
> = z.enum(Sdxl2LatentPreprocessingType);

/** @internal */
export type Sdxl2LatentPreprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const Sdxl2LatentPreprocessingProcessor$outboundSchema: z.ZodMiniType<
  Sdxl2LatentPreprocessingProcessor$Outbound,
  Sdxl2LatentPreprocessingProcessor
> = z.object({
  type: Sdxl2LatentPreprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sdxl2LatentPreprocessingProcessorToJSON(
  sdxl2LatentPreprocessingProcessor: Sdxl2LatentPreprocessingProcessor,
): string {
  return JSON.stringify(
    Sdxl2LatentPreprocessingProcessor$outboundSchema.parse(
      sdxl2LatentPreprocessingProcessor,
    ),
  );
}

/** @internal */
export type Sdxl2LatentPreprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<Sdxl2LatentPreprocessingProcessor$Outbound>;
};

/** @internal */
export const Sdxl2LatentPreprocessing$outboundSchema: z.ZodMiniType<
  Sdxl2LatentPreprocessing$Outbound,
  Sdxl2LatentPreprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => Sdxl2LatentPreprocessingProcessor$outboundSchema),
  ),
});

export function sdxl2LatentPreprocessingToJSON(
  sdxl2LatentPreprocessing: Sdxl2LatentPreprocessing,
): string {
  return JSON.stringify(
    Sdxl2LatentPreprocessing$outboundSchema.parse(sdxl2LatentPreprocessing),
  );
}

/** @internal */
export const Sdxl2LatentPostprocessingType$outboundSchema: z.ZodMiniEnum<
  typeof Sdxl2LatentPostprocessingType
> = z.enum(Sdxl2LatentPostprocessingType);

/** @internal */
export type Sdxl2LatentPostprocessingProcessor$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  params?: { [k: string]: any } | undefined;
};

/** @internal */
export const Sdxl2LatentPostprocessingProcessor$outboundSchema: z.ZodMiniType<
  Sdxl2LatentPostprocessingProcessor$Outbound,
  Sdxl2LatentPostprocessingProcessor
> = z.object({
  type: Sdxl2LatentPostprocessingType$outboundSchema,
  enabled: z.optional(z.boolean()),
  params: z.optional(z.record(z.string(), z.any())),
});

export function sdxl2LatentPostprocessingProcessorToJSON(
  sdxl2LatentPostprocessingProcessor: Sdxl2LatentPostprocessingProcessor,
): string {
  return JSON.stringify(
    Sdxl2LatentPostprocessingProcessor$outboundSchema.parse(
      sdxl2LatentPostprocessingProcessor,
    ),
  );
}

/** @internal */
export type Sdxl2LatentPostprocessing$Outbound = {
  enabled?: boolean | undefined;
  processors: Array<Sdxl2LatentPostprocessingProcessor$Outbound>;
};

/** @internal */
export const Sdxl2LatentPostprocessing$outboundSchema: z.ZodMiniType<
  Sdxl2LatentPostprocessing$Outbound,
  Sdxl2LatentPostprocessing
> = z.object({
  enabled: z.optional(z.boolean()),
  processors: z.array(
    z.lazy(() => Sdxl2LatentPostprocessingProcessor$outboundSchema),
  ),
});

export function sdxl2LatentPostprocessingToJSON(
  sdxl2LatentPostprocessing: Sdxl2LatentPostprocessing,
): string {
  return JSON.stringify(
    Sdxl2LatentPostprocessing$outboundSchema.parse(sdxl2LatentPostprocessing),
  );
}

/** @internal */
export const Sdxl2ControlnetModelId$outboundSchema: z.ZodMiniEnum<
  typeof Sdxl2ControlnetModelId
> = z.enum(Sdxl2ControlnetModelId);

/** @internal */
export const Sdxl2Preprocessor$outboundSchema: z.ZodMiniEnum<
  typeof Sdxl2Preprocessor
> = z.enum(Sdxl2Preprocessor);

/** @internal */
export type Sdxl2Controlnet$Outbound = {
  model_id: string;
  conditioning_scale: number;
  preprocessor: string;
  preprocessor_params?: { [k: string]: any } | undefined;
  enabled: boolean;
  control_guidance_start?: number | undefined;
  control_guidance_end?: number | undefined;
};

/** @internal */
export const Sdxl2Controlnet$outboundSchema: z.ZodMiniType<
  Sdxl2Controlnet$Outbound,
  Sdxl2Controlnet
> = z.pipe(
  z.object({
    modelId: Sdxl2ControlnetModelId$outboundSchema,
    conditioningScale: z.number(),
    preprocessor: Sdxl2Preprocessor$outboundSchema,
    preprocessorParams: z.optional(z.record(z.string(), z.any())),
    enabled: z.boolean(),
    controlGuidanceStart: z.optional(z.number()),
    controlGuidanceEnd: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      modelId: "model_id",
      conditioningScale: "conditioning_scale",
      preprocessorParams: "preprocessor_params",
      controlGuidanceStart: "control_guidance_start",
      controlGuidanceEnd: "control_guidance_end",
    });
  }),
);

export function sdxl2ControlnetToJSON(
  sdxl2Controlnet: Sdxl2Controlnet,
): string {
  return JSON.stringify(Sdxl2Controlnet$outboundSchema.parse(sdxl2Controlnet));
}

/** @internal */
export const Sdxl2IpAdapterType$outboundSchema: z.ZodMiniEnum<
  typeof Sdxl2IpAdapterType
> = z.enum(Sdxl2IpAdapterType);

/** @internal */
export const Sdxl2WeightType$outboundSchema: z.ZodMiniEnum<
  typeof Sdxl2WeightType
> = z.enum(Sdxl2WeightType);

/** @internal */
export type Sdxl2IpAdapter$Outbound = {
  type: string;
  enabled?: boolean | undefined;
  scale?: number | undefined;
  weight_type?: string | undefined;
};

/** @internal */
export const Sdxl2IpAdapter$outboundSchema: z.ZodMiniType<
  Sdxl2IpAdapter$Outbound,
  Sdxl2IpAdapter
> = z.pipe(
  z.object({
    type: z._default(Sdxl2IpAdapterType$outboundSchema, "regular"),
    enabled: z.optional(z.boolean()),
    scale: z.optional(z.number()),
    weightType: z.optional(Sdxl2WeightType$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      weightType: "weight_type",
    });
  }),
);

export function sdxl2IpAdapterToJSON(sdxl2IpAdapter: Sdxl2IpAdapter): string {
  return JSON.stringify(Sdxl2IpAdapter$outboundSchema.parse(sdxl2IpAdapter));
}

/** @internal */
export type Sdxl2CachedAttention$Outbound = {
  enabled: boolean;
  max_frames: number;
  interval: number;
};

/** @internal */
export const Sdxl2CachedAttention$outboundSchema: z.ZodMiniType<
  Sdxl2CachedAttention$Outbound,
  Sdxl2CachedAttention
> = z.pipe(
  z.object({
    enabled: z.boolean(),
    maxFrames: z.int(),
    interval: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      maxFrames: "max_frames",
    });
  }),
);

export function sdxl2CachedAttentionToJSON(
  sdxl2CachedAttention: Sdxl2CachedAttention,
): string {
  return JSON.stringify(
    Sdxl2CachedAttention$outboundSchema.parse(sdxl2CachedAttention),
  );
}

/** @internal */
export type Sdxl2$Outbound = {
  model_id: "stabilityai/sdxl-turbo";
  prompt?: string | Array<Array<string | number>> | undefined;
  prompt_interpolation_method?: string | undefined;
  normalize_prompt_weights?: boolean | undefined;
  normalize_seed_weights?: boolean | undefined;
  negative_prompt?: string | undefined;
  guidance_scale?: number | undefined;
  delta?: number | undefined;
  num_inference_steps?: number | undefined;
  t_index_list?: Array<number> | undefined;
  use_safety_checker?: boolean | undefined;
  width?: number | undefined;
  height?: number | undefined;
  lora_dict?: Sdxl2LoraDict$Outbound | null | undefined;
  use_lcm_lora?: boolean | undefined;
  lcm_lora_id?: string | undefined;
  acceleration?: string | undefined;
  use_denoising_batch?: boolean | undefined;
  do_add_noise?: boolean | undefined;
  seed?: number | Array<Array<number | number>> | undefined;
  seed_interpolation_method?: string | undefined;
  enable_similar_image_filter?: boolean | undefined;
  similar_image_filter_threshold?: number | undefined;
  similar_image_filter_max_skip_frame?: number | undefined;
  skip_diffusion?: boolean | undefined;
  image_preprocessing?: Sdxl2ImagePreprocessing$Outbound | undefined;
  image_postprocessing?: Sdxl2ImagePostprocessing$Outbound | undefined;
  latent_preprocessing?: Sdxl2LatentPreprocessing$Outbound | undefined;
  latent_postprocessing?: Sdxl2LatentPostprocessing$Outbound | undefined;
  controlnets?: Array<Sdxl2Controlnet$Outbound> | undefined;
  ip_adapter?: Sdxl2IpAdapter$Outbound | undefined;
  ip_adapter_style_image_url?: string | undefined;
  cached_attention?: Sdxl2CachedAttention$Outbound | undefined;
};

/** @internal */
export const Sdxl2$outboundSchema: z.ZodMiniType<Sdxl2$Outbound, Sdxl2> = z
  .pipe(
    z.object({
      modelId: z.literal("stabilityai/sdxl-turbo"),
      prompt: z.optional(
        smartUnion([
          z.string(),
          z.array(z.array(smartUnion([z.string(), z.number()]))),
        ]),
      ),
      promptInterpolationMethod: z.optional(
        Sdxl2PromptInterpolationMethod$outboundSchema,
      ),
      normalizePromptWeights: z.optional(z.boolean()),
      normalizeSeedWeights: z.optional(z.boolean()),
      negativePrompt: z.optional(z.string()),
      guidanceScale: z.optional(z.number()),
      delta: z.optional(z.number()),
      numInferenceSteps: z.optional(z.int()),
      tIndexList: z.optional(z.array(z.int())),
      useSafetyChecker: z.optional(z.boolean()),
      width: z.optional(z.int()),
      height: z.optional(z.int()),
      loraDict: z.optional(
        z.nullable(z.lazy(() => Sdxl2LoraDict$outboundSchema)),
      ),
      useLcmLora: z.optional(z.boolean()),
      lcmLoraId: z.optional(z.string()),
      acceleration: z.optional(Sdxl2Acceleration$outboundSchema),
      useDenoisingBatch: z.optional(z.boolean()),
      doAddNoise: z.optional(z.boolean()),
      seed: z.optional(
        smartUnion([
          z.int(),
          z.array(z.array(smartUnion([z.int(), z.number()]))),
        ]),
      ),
      seedInterpolationMethod: z.optional(
        Sdxl2SeedInterpolationMethod$outboundSchema,
      ),
      enableSimilarImageFilter: z.optional(z.boolean()),
      similarImageFilterThreshold: z.optional(z.number()),
      similarImageFilterMaxSkipFrame: z.optional(z.int()),
      skipDiffusion: z.optional(z.boolean()),
      imagePreprocessing: z.optional(
        z.lazy(() => Sdxl2ImagePreprocessing$outboundSchema),
      ),
      imagePostprocessing: z.optional(
        z.lazy(() => Sdxl2ImagePostprocessing$outboundSchema),
      ),
      latentPreprocessing: z.optional(
        z.lazy(() => Sdxl2LatentPreprocessing$outboundSchema),
      ),
      latentPostprocessing: z.optional(
        z.lazy(() => Sdxl2LatentPostprocessing$outboundSchema),
      ),
      controlnets: z.optional(
        z.array(z.lazy(() => Sdxl2Controlnet$outboundSchema)),
      ),
      ipAdapter: z.optional(z.lazy(() => Sdxl2IpAdapter$outboundSchema)),
      ipAdapterStyleImageUrl: z.optional(z.string()),
      cachedAttention: z.optional(
        z.lazy(() => Sdxl2CachedAttention$outboundSchema),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        modelId: "model_id",
        promptInterpolationMethod: "prompt_interpolation_method",
        normalizePromptWeights: "normalize_prompt_weights",
        normalizeSeedWeights: "normalize_seed_weights",
        negativePrompt: "negative_prompt",
        guidanceScale: "guidance_scale",
        numInferenceSteps: "num_inference_steps",
        tIndexList: "t_index_list",
        useSafetyChecker: "use_safety_checker",
        loraDict: "lora_dict",
        useLcmLora: "use_lcm_lora",
        lcmLoraId: "lcm_lora_id",
        useDenoisingBatch: "use_denoising_batch",
        doAddNoise: "do_add_noise",
        seedInterpolationMethod: "seed_interpolation_method",
        enableSimilarImageFilter: "enable_similar_image_filter",
        similarImageFilterThreshold: "similar_image_filter_threshold",
        similarImageFilterMaxSkipFrame: "similar_image_filter_max_skip_frame",
        skipDiffusion: "skip_diffusion",
        imagePreprocessing: "image_preprocessing",
        imagePostprocessing: "image_postprocessing",
        latentPreprocessing: "latent_preprocessing",
        latentPostprocessing: "latent_postprocessing",
        ipAdapter: "ip_adapter",
        ipAdapterStyleImageUrl: "ip_adapter_style_image_url",
        cachedAttention: "cached_attention",
      });
    }),
  );

export function sdxl2ToJSON(sdxl2: Sdxl2): string {
  return JSON.stringify(Sdxl2$outboundSchema.parse(sdxl2));
}
